# Data distribution analysis

In [1]:
import pandas as pd
import altair as alt
import numpy as np
import os

alt.data_transformers.enable("vegafusion")

tracks_path = os.path.join('..', 'dataset', 'tracks.csv')
dataset_path = os.path.join('..', 'dataset', 'cleaned_tracks.csv')
artists_path = os.path.join('..', 'dataset', 'artists.csv')

df_cleaned = pd.read_csv(dataset_path, sep=',')
df_tracks = pd.read_csv(tracks_path, sep=',')
df_artists = pd.read_csv(artists_path, sep=';')

## Univariant distribution analysis

In [2]:
def analyze_distribution(df, col, title, color_histo, bins=40):
    
    chart_data = df[[col, 'title', 'name_artist']].dropna().copy()
    chart_data[col] = pd.to_numeric(chart_data[col], errors='coerce')
    
    hist = alt.Chart(chart_data).mark_bar(opacity=0.7, color=color_histo).encode(
        x=alt.X(col, bin=alt.Bin(maxbins=bins), title=title),
        y=alt.Y('count()', title='Count'),
        tooltip=[alt.Tooltip(col, bin=True), 'count()']
    ).properties(title=f'Distribution of Tracks by {title}', width=800, height=300)
    
    box = alt.Chart(chart_data).mark_boxplot().encode(
        x=alt.X(col, title=title),
        tooltip=[alt.Tooltip(f'min({col})'), alt.Tooltip(f'max({col})')]
    ).properties(width=800, height=100)
    
    display(hist & box)
    
    print(f"Top 10 Highest {title}:")
    display(chart_data.sort_values(by=col, ascending=False).head(10))
    
    print(f"Bottom 10 Lowest {title}:")
    display(chart_data.sort_values(by=col, ascending=True).head(10))

## n_sentences

In [3]:
analyze_distribution(df_tracks, 'n_sentences', 'n_sentences', 'blue')

alt.VConcatChart(...)

Top 10 Highest n_sentences:

      n_sentences                                       title     name_artist
5353        437.0                        Nostalgia istantanea  Dargen D’Amico
5535        430.0      Nostalgia Istantanea (Under-21 MashUp)  Dargen D’Amico
5366        328.0  Nostalgia istantanea (Variazioni sul tema)  Dargen D’Amico
8302        326.0                              Madtadone 2013          MadMan
5409        295.0                     Non Sono Più Innamorato  Dargen D’Amico
8277        276.0                              Madtadone 2018          MadMan
1996        262.0                         Niente Di Personale     Fabri Fibra
6305        242.0                                Medley ragga        99 Posse
8312        234.0                              Madtadone 2011          MadMan
8308        234.0                              Madtadone 2012          MadMan

Bottom 10 Lowest n_sentences:

,n_sentences,title,name_artist
7453,1.0,Beef,DrefGold
4166,1.0,Una sera a Basiano,Bassi Maestro
4169,1.0,Buoni propositi,Bassi Maestro
4171,1.0,Click,Bassi Maestro
9790,1.0,Intro,Salmo
3510,1.0,Spaghetti Funk (Versione Shakerata Strumentale),Articolo 31
3508,1.0,Il mio viaggio,Articolo 31
1626,1.0,La Valigia - Strumentale,Piotta
3515,1.0,Beat Box (Per Improvvisare),Articolo 31
3514,1.0,Così mi tieni (Strumentale),Articolo 31

No issue found in the number of sentences, as the top ones are really long songs, while the ones with only one sentence are songs which in reality do not contain lyrics, or contain all the lyrics in the same line. Those are already handled in the tracks_analysis analysis.

## n_tokens

In [4]:
analyze_distribution(df_tracks, 'n_tokens', 'n_tokens', 'blue')

alt.VConcatChart(...)

Top 10 Highest n_tokens:

      n_tokens                                       title     name_artist
5353    3089.0                        Nostalgia istantanea  Dargen D’Amico
5535    3076.0      Nostalgia Istantanea (Under-21 MashUp)  Dargen D’Amico
8302    2949.0                              Madtadone 2013          MadMan
5366    2918.0  Nostalgia istantanea (Variazioni sul tema)  Dargen D’Amico
8277    2365.0                              Madtadone 2018          MadMan
8308    2245.0                              Madtadone 2012          MadMan
8312    2232.0                              Madtadone 2011          MadMan
5409    2187.0                     Non Sono Più Innamorato  Dargen D’Amico
1996    1900.0                         Niente Di Personale     Fabri Fibra
4519    1794.0                 Freestyle Lavanderie Ramone            Ensi

Bottom 10 Lowest n_tokens:

      n_tokens                               title        name_artist
5758       3.0                               Twist              Shade
3662       3.0                               Laura              Neffa
9181       3.0                               Intro  Colle Der Fomento
3666       3.0                               Intro              Neffa
8854       3.0  Non esistono risposte intelligenti           Highsnob
7453       3.0                                Beef           DrefGold
4482       3.0                             Joyride              Ghali
4171       3.0                               Click      Bassi Maestro
3631       3.0                          Tentazioni              Neffa
9443       3.0                          Fannullone       Samuel Costa

Consistent results with n_sentences. As we'll see, there's an high correlation between those two features.

## tokens_per_sent

In [5]:
analyze_distribution(df_tracks, 'tokens_per_sent', 'tokens_per_sent', 'blue')

alt.VConcatChart(...)

Top 10 Highest tokens_per_sent:

      tokens_per_sent                              title    name_artist
7001       400.000000                Meteoriti (english)        Mr.Rain
1968       283.000000                            Cin Cin        La Pina
1975       148.666667                     Pronte A Tutto        La Pina
3639       108.000000                  0 tempo e 0 vento          Neffa
7886        88.250000                          Bombtrack    Noyz Narcos
9225        74.000000                  La Vita Dei Gaggi      Sottotono
9237        70.888889                       24h Non Stop      Sottotono
4312        64.875000  20 anni (tutto cambia tranne Bax)  Bassi Maestro
9241        63.166667                Nel Jet Set Del Rap      Sottotono
9873        60.000000                      Se ti girassi       Tormento

Bottom 10 Lowest tokens_per_sent:

,tokens_per_sent,title,name_artist
1982,1.500000,Intro,La Pina
3998,1.636364,Sssaasss,Caparezza
758,1.666667,Intro (Dinamite),Babaman
3586,1.800000,Crociera,Neffa
3484,2.000000,Cantico Errante Di Due D.J. Notturni,Articolo 31
2671,2.000000,Nobiltà Di Strada (Intro),Inoki
4330,2.000000,Why?,Bassi Maestro
9178,2.181818,Pornorockers,Colle Der Fomento
10628,2.333333,Intro (Fuori di Qua!),Mondo Marcio
9598,2.476190,NOI FACCIAMO IL CONTRARIO (CELEBRAZIONE EUCARI...,Dani Faiv

Some of those high values might come from lyrics that are contained in a "single sentence". Let's find out which ones of them have n_sentences == 1

In [6]:
long_single_sentence_tracks = df_cleaned[
    (df_cleaned['tokens_per_sent'] > 15) & 
    (df_cleaned['n_sentences'] == 1)
]

print(f"Found {len(long_single_sentence_tracks)} tracks with > 15 tokens/sent and only 1 sentence:")
cols_to_show = ['title', 'name_artist', 'tokens_per_sent', 'n_sentences', 'n_tokens']
display(long_single_sentence_tracks[cols_to_show].sort_values(by='tokens_per_sent', ascending=False))

Found 5 tracks with > 15 tokens/sent and only 1 sentence:

                    title  name_artist  tokens_per_sent  n_sentences  n_tokens
6995  Meteoriti (english)      Mr.Rain            400.0            1       400
1967              Cin Cin      La Pina            283.0            1       283
3637    0 tempo e 0 vento        Neffa            108.0            1       108
7889         Interlude #2  Noyz Narcos             19.0            1        19
497               Come Me        Lazza             16.0            1        16

Not only there are track with n_sentences == 1 (the n_sentences will be recomputed in the python script to clean data), but from this analysis we found out that there are other tracks with no lyrics (As Interlude #2), but in the lyrics field there's a string "La produzione..." instead of the string, describing who produced the songs. Those instances, along with the "{n} Contributor/s{title}" will be treated in the tracks_analysis (lyrics).

## char_per_tok

In [7]:
analyze_distribution(df_tracks, 'char_per_tok', 'char_per_tok', 'blue')

alt.VConcatChart(...)

Top 10 Highest char_per_tok:

      char_per_tok                     title        name_artist
9178     12.000000              Pornorockers  Colle Der Fomento
4482     10.666667                   Joyride              Ghali
8182     10.500000  Introducing Avantguardia             Shablo
9443     10.333333                Fannullone       Samuel Costa
8184     10.250000              Superstition             Shablo
8181     10.000000               Skyscrapers             Shablo
3631      9.666667                Tentazioni              Neffa
5146      9.666667                INTERMEZZO          M¥SS KETA
7875      9.666667                Interludio        Noyz Narcos
4353      9.500000     Constatazione Servile      Bassi Maestro

Bottom 10 Lowest char_per_tok:

       char_per_tok                   title    name_artist
3999       2.000000        Profilo psichico      Caparezza
3586       2.750000                Crociera          Neffa
3473       2.769231             Fatti In Là    Articolo 31
10243      2.792453            Applausi Rmx         Caneda
10161      2.800000                  Unpodi         Caneda
7173       2.915888  Non Mi Va (Interludio)       Gemitaiz
10316      2.918685              Masterchef         Caneda
10326      2.927948             Ladro di te         Caneda
8510       2.935961                  PAVONE  Achille Lauro
8425       2.937965                     Blu  Achille Lauro

## lexical_density

In [8]:
analyze_distribution(df_tracks, 'lexical_density', 'lexical_density', 'blue')

alt.VConcatChart(...)

Top 10 Highest lexical_density:

      lexical_density                            title        name_artist
4045         1.000000          The duck with pantapony          Caparezza
3998         1.000000                         Sssaasss          Caparezza
3172         1.000000                   K.O. Freestyle      Sfera Ebbasta
9178         1.000000                     Pornorockers  Colle Der Fomento
8357         0.990060  Ne se obrushtai / Не се обръщай             MadMan
5760         0.985119                             Бары              Shade
6001         0.942559                   Loco Loco Loco           Bushwaka
5085         0.940476               #FIGHECOMEILPANICO          M¥SS KETA
5414         0.908163      Zafferano Vulcano Siciliano     Dargen D’Amico
5101         0.902098                            GOLEM          M¥SS KETA

Bottom 10 Lowest lexical_density:

,lexical_density,title,name_artist
5528,0.000000,Bobby’s Back to Houston,Dargen D’Amico
8164,0.000000,What About The Meaning,Shablo
3999,0.009524,Profilo psichico,Caparezza
7890,0.111732,Money & Egos,Noyz Narcos
301,0.124031,Mad world con le righe delle lacrime sulle guance,thasup
3641,0.125000,Funky mirandola,Neffa
10343,0.149321,Tekila,Caneda
9748,0.170854,Doomsday,Salmo
3649,0.176923,Tutto Tu,Neffa
6156,0.180758,Papercuts,J-Ax

By analyzing some of the tracks, there seems to be a lot of errors. As the mean difference and variance of the original lexical_density and the one computed is small (check tracks_analysis), the one computed will take place.

In [9]:
import re

def compute_lexical_density_regex(lyrics):
    if pd.isna(lyrics):
        return 0
    
    all_tokens = re.findall(r"[^\W\d_]+(?:['’-][^\W\d_]+)*", lyrics.lower(), flags=re.UNICODE)
    
    all_words = all_tokens 
    
    total_words = len(all_words)
    if total_words == 0:
        return 0
    
    unique_words = len(set(all_words)) # Count of unique words
    
    return unique_words / total_words

df_cleaned['computed_lexical_density'] = df_cleaned['lyrics'].apply(compute_lexical_density_regex)

analyze_distribution(df_cleaned, 'computed_lexical_density', 'computed_lexical_density', 'blue')

alt.VConcatChart(...)

Top 10 Highest computed_lexical_density:

,computed_lexical_density,title,name_artist
3158,1.0,Squali*,Sfera Ebbasta
3995,1.0,Mors mea tacci tua,Caparezza
11147,1.0,Album Trailer 3,Marracash
8848,1.0,Non esistono risposte intelligenti,Highsnob
5654,1.0,Classifiche*,Geolier
6981,1.0,Intro,Mr.Rain
4040,1.0,Niente Paura (Outro),Caparezza
10620,1.0,Intro (Fuori di Qua!),Mondo Marcio
3584,1.0,Crociera,Neffa
1304,1.0,Abu Dhabi*,Capo Plaza

Bottom 10 Lowest computed_lexical_density:

      computed_lexical_density                       title    name_artist
61                         0.0               Punk 'a Piana  Rosa Chemical
7019                       0.0                OUTRO [2024]        Mr.Rain
7021                       0.0            Intro (Memories)        Mr.Rain
9889                       0.0       Artisti (Strumentale)       Tormento
8157                       0.0      Chessplaying This Dame         Shablo
8155                       0.0             Timeless Spirit         Shablo
6638                       0.0  Ombre Cinesi (Strumentale)        Don Joe
7890                       0.0                Interlude #3    Noyz Narcos
4003                       0.0                     Tii-Yan      Caparezza
7869                       0.0                  Interludio    Noyz Narcos

Tracks with values == 1 are short tracks, while the one with values == 0 have no lyrics.

## avg_token_per_clause

In [10]:
analyze_distribution(df_tracks, 'avg_token_per_clause', 'avg_token_per_clause', 'blue')

alt.VConcatChart(...)

Top 10 Highest avg_token_per_clause:

       avg_token_per_clause                            title    name_artist
8357                  660.0  Ne se obrushtai / Не се обръщай         MadMan
10316                 618.0                       Masterchef         Caneda
5760                  505.0                             Бары          Shade
5071                  470.0                        IN GABBIA      M¥SS KETA
2945                  423.0                    Funeral Party   Rose Villain
8533                  370.0                             FOXY  Achille Lauro
5070                  333.5                   BURQA DI GUCCI      M¥SS KETA
8158                  311.0                Pimper’s Paradise         Shablo
5068                  259.0              MILANO SUSHI & COCA      M¥SS KETA
5079                  226.0                 LE FAREMO SAPERE      M¥SS KETA

Bottom 10 Lowest avg_token_per_clause:

,avg_token_per_clause,title,name_artist
3663,0.0,Alpha 2000,Neffa
3666,0.0,Intro,Neffa
3662,0.0,Laura,Neffa
65,0.0,C. A. S.,Rosa Chemical
68,0.0,Luciano Pavarotty // Glock,Rosa Chemical
61,0.0,Punk ’a Piana,Rosa Chemical
3999,0.0,Profilo psichico,Caparezza
3998,0.0,Sssaasss,Caparezza
3511,0.0,Spaghetti Funk (Strumentale),Articolo 31
3510,0.0,Spaghetti Funk (Versione Shakerata Strumentale),Articolo 31

The avg_token_per_clause value for the track "Ne se obrushtai" will be recomputed by hand, as it's not worth to install a SpaCy russian model only for one track (506 / 128 = 3,95). For the others top 2% of values, they will be recomputed using SpaCy.

In [11]:
threshold_top_1_percent = df_tracks['avg_token_per_clause'].quantile(0.98)

print(f"The smallest of the top 2% of values (98th percentile) is: {threshold_top_1_percent}")

analyze_distribution(df_cleaned, 'avg_token_per_clause', 'avg_token_per_clause', 'blue')

The smallest of the top 2% of values (98th percentile) is: 15.688978328173361

alt.VConcatChart(...)

Top 10 Highest avg_token_per_clause:

       avg_token_per_clause                            title    name_artist
8351                  660.0  Ne se obrushtai / Не се обръщай         MadMan
10308                 618.0                       Masterchef         Caneda
5755                  505.0                             Бары          Shade
5066                  470.0                        IN GABBIA      M¥SS KETA
2944                  423.0                    Funeral Party   Rose Villain
8527                  370.0                             FOXY  Achille Lauro
5065                  333.5                   BURQA DI GUCCI      M¥SS KETA
8152                  311.0                Pimper's Paradise         Shablo
5063                  259.0              MILANO SUSHI & COCA      M¥SS KETA
5074                  226.0                 LE FAREMO SAPERE      M¥SS KETA

Bottom 10 Lowest avg_token_per_clause:

,avg_token_per_clause,title,name_artist
8162,0.0,She's Dope,Shablo
3506,0.0,Il mio viaggio,Articolo 31
3508,0.0,Spaghetti Funk (Versione Shakerata Strumentale),Articolo 31
3509,0.0,Spaghetti Funk (Strumentale),Articolo 31
3512,0.0,Così mi tieni (Strumentale),Articolo 31
3513,0.0,Beat Box (Per Improvvisare),Articolo 31
3514,0.0,Funkytarro (Versione strumentale),Articolo 31
3515,0.0,Cavalieri senza Re (Versione strumentale),Articolo 31
7019,0.0,OUTRO [2024],Mr.Rain
7021,0.0,Intro (Memories),Mr.Rain

### bpm

In [12]:
analyze_distribution(df_tracks, 'bpm', 'bpm', 'darkred')

alt.VConcatChart(...)

Top 10 Highest bpm:

          bpm                                    title  name_artist
8317   738.27                           Madtadone 2015       MadMan
4620   191.41                            Carta E Penna      Mistico
2996   184.57                                 ADDERALL  Rondodasosa
971    184.57                           Ruggine E Ossa          Guè
358    184.57                  L’ERBA VOGLIO (Geordie)        Lazza
3574   184.57                               Wicked Man        Neffa
1828   184.57                   Selezione All’Ingresso    Club Dogo
10009  184.57                                Kooda RMX        Shiva
9995   184.57                             Milano Ovest        Shiva
9246   184.57  Ti bacio ancora mentre dormi (Acoustic)    Sottotono

Bottom 10 Lowest bpm:

         bpm                title name_artist
6708   59.97         Guardo Fuori       Nesli
5109   59.99          BLING BLING   M¥SS KETA
4784   60.01     Nonostante Tutto       Vacca
9228   63.00  Amarti, Rispettarti   Sottotono
4882   63.62                In Tv       Vacca
6298   64.19      Povera Vita Mia    99 Posse
2443   66.03   Se parlassi con te    Mistaman
3656   66.86               Realtà       Neffa
7668   67.47            Sintonia*    Tony Boy
10182  67.50      C’Era Una Volta      Caneda

tracks with btm under 250 are most likely correct, Madtadone 2015 by MadMan have an error value which will be set to NaN

In [13]:
bpm_threshold = 250 

condition = df_tracks['bpm'] > bpm_threshold

print(f"removing {condition.sum()} tracks with BPM > {bpm_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'bpm']])

df_tracks.loc[condition, 'bpm'] = np.nan

analyze_distribution(df_tracks, 'bpm', 'bpm', 'darkred')

removing 1 tracks with BPM > 250:

            id           title name_artist     bpm
8317  TR591502  Madtadone 2015      MadMan  738.27

alt.VConcatChart(...)

Top 10 Highest bpm:

         bpm                 title  name_artist
4620  191.41         Carta E Penna      Mistico
3574  184.57            Wicked Man        Neffa
192   184.57             Vivo Così         Alfa
8082  184.57         Forever alone         Coez
2184  184.57             Freestyle  Fabri Fibra
8977  184.57  Dissotterracci n. 21      Rancore
6288  184.57        Pagherete caro     99 Posse
2996  184.57              ADDERALL  Rondodasosa
628   184.57      Brambo Freestyle       Nerone
2118  184.57           Fuori Norma  Fabri Fibra

Bottom 10 Lowest bpm:

         bpm                title name_artist
6708   59.97         Guardo Fuori       Nesli
5109   59.99          BLING BLING   M¥SS KETA
4784   60.01     Nonostante Tutto       Vacca
9228   63.00  Amarti, Rispettarti   Sottotono
4882   63.62                In Tv       Vacca
6298   64.19      Povera Vita Mia    99 Posse
2443   66.03   Se parlassi con te    Mistaman
3656   66.86               Realtà       Neffa
7668   67.47            Sintonia*    Tony Boy
10182  67.50      C’Era Una Volta      Caneda

### centroid

In [14]:
analyze_distribution(df_tracks, 'centroid', 'centroid', 'darkblue')

alt.VConcatChart(...)

Top 10 Highest centroid:

      centroid                title     name_artist
8332    0.2982  Una Più Del Diavolo          MadMan
8339    0.2643   Notti Di Provincia          MadMan
9401    0.2596             Drive By          Papa V
1084    0.2509              Cartier             Guè
5031    0.2421        Dimmi Come Fa          Il Tre
8344    0.2417         La Rinascita          MadMan
6626    0.2410          Guarda bene         Don Joe
9080    0.2397       Branco di iene  Dark Polo Gang
1057    0.2383       Il Sesto Senso             Guè
6617    0.2352   Il resto del mondo         Don Joe

Bottom 10 Lowest centroid:

       centroid                 title    name_artist
8317     0.0000        Madtadone 2015         MadMan
4882     0.0004                 In Tv          Vacca
3159     0.0148               Squali*  Sfera Ebbasta
1951     0.0322         Le Mie Amiche        La Pina
365      0.0386  -3 (PERDERE IL VOLO)          Lazza
3574     0.0391            Wicked Man          Neffa
5072     0.0396       100 ROSE PER TE      M¥SS KETA
7669     0.0397              Spin it*       Tony Boy
10148    0.0400     Back In Blood RMX          Shiva
2692     0.0472             Disstacco        Eva Rea

Remove tracks with near-zero centroid (likely errors)

In [15]:
centroid_min_threshold = 0.001 

condition = df_tracks['centroid'] < centroid_min_threshold

print(f"Removing {condition.sum()} tracks with Centroid < {centroid_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'centroid']])

df_tracks.loc[condition, 'centroid'] = np.nan

Removing 2 tracks with Centroid < 0.001:

            id           title name_artist  centroid
4882  TR508832           In Tv       Vacca    0.0004
8317  TR591502  Madtadone 2015      MadMan    0.0000

### rolloff

In [16]:
analyze_distribution(df_tracks, 'rolloff', 'rolloff', 'darkgreen')

alt.VConcatChart(...)

Top 10 Highest rolloff:

        rolloff                title     name_artist
8332  8635.9542  Una Più Del Diavolo          MadMan
8339  6602.6082   Notti Di Provincia          MadMan
254   6209.2182   COVID-19 Freestyle          thasup
55    5476.3469    BRITISH PROV 2014   Rosa Chemical
1084  5311.0667              Cartier             Guè
1057  5257.4073       Il Sesto Senso             Guè
4671  5179.1962       2020 Freestyle          Madame
9080  5082.3203       Branco di iene  Dark Polo Gang
9401  4728.1250             Drive By          Papa V
3176  4710.7121            Ice Cream   Sfera Ebbasta

Bottom 10 Lowest rolloff:

       rolloff                 title    name_artist
8317    0.0000        Madtadone 2015         MadMan
4882   14.4718                 In Tv          Vacca
7550  132.3839         Fino a domani       Tony Boy
3159  140.7022               Squali*  Sfera Ebbasta
2776  223.4683                   187      Doll Kill
7578  228.5769                 Si si       Tony Boy
365   234.6066  -3 (PERDERE IL VOLO)          Lazza
261   250.7364             Veri Fra*         thasup
5146  251.9674            INTERMEZZO      M¥SS KETA
3564  258.8036         El Chico Loco          Neffa

Remove tracks with near-zero rolloff (outliers have values near 0 Hz).

In [17]:
rolloff_min_threshold = 20.0 

condition = df_tracks['rolloff'] < rolloff_min_threshold

print(f"Removing {condition.sum()} tracks with Rolloff < {rolloff_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'rolloff']])

df_tracks.loc[condition, 'rolloff'] = np.nan

Removing 2 tracks with Rolloff < 20.0:

            id           title name_artist  rolloff
4882  TR508832           In Tv       Vacca  14.4718
8317  TR591502  Madtadone 2015      MadMan   0.0000

### flux

In [18]:
analyze_distribution(df_tracks, 'flux', 'flux', 'darkorange')

alt.VConcatChart(...)

Top 10 Highest flux:

        flux                        title   name_artist
3515  1.9285  Beat Box (Per Improvvisare)   Articolo 31
9441  1.8700                         KLK!  Samuel Costa
9570  1.8439                       Rapido     Dani Faiv
295   1.8344                    Wickedboi        thasup
9439  1.7944                    PICAPOLLO  Samuel Costa
7091  1.7860                   Fuck/Peace      Gemitaiz
497   1.7739                      Come Me         Lazza
4816  1.7278                  Lady Sexxxy         Vacca
6325  1.7249                    La Scelta      99 Posse
4850  1.7182              Cosa Vuoi Da Me         Vacca

Bottom 10 Lowest flux:

         flux                 title     name_artist
4882   0.0000                 In Tv           Vacca
8317   0.0000        Madtadone 2015          MadMan
3159   0.1893               Squali*   Sfera Ebbasta
8816   0.3108             Balaclava        Highsnob
8834   0.4026               Rooftop        Highsnob
5517   0.5742               40 anni  Dargen D’Amico
10630  0.5954     Patto col diavolo    Mondo Marcio
2216   0.7251          2031 (Intro)     Fabri Fibra
1575   0.7549              Overture          Piotta
8030   0.7696  Le parole più grandi            Coez

Remove tracks with 0 spectral flux.

In [19]:
flux_min_threshold = 0.001

condition = df_tracks['flux'] < flux_min_threshold

print(f"Removing {condition.sum()} tracks with Flux < {flux_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'flux']])

df_tracks.loc[condition, 'flux'] = np.nan

Removing 2 tracks with Flux < 0.001:

            id           title name_artist  flux
4882  TR508832           In Tv       Vacca   0.0
8317  TR591502  Madtadone 2015      MadMan   0.0

### flatness

In [20]:
analyze_distribution(df_tracks, 'flatness', 'flatness', 'purple')

alt.VConcatChart(...)

Top 10 Highest flatness:

      flatness              title        name_artist
8317    1.0000     Madtadone 2015             MadMan
4882    0.9992              In Tv              Vacca
3159    0.9941            Squali*      Sfera Ebbasta
7895    0.9875       Interlude #2        Noyz Narcos
6692    0.9811              Oltre              Nesli
181     0.9807  COVID19 FREESTYLE               Alfa
7658    0.9796  Alla mia maniera*           Tony Boy
2028    0.9789    E Tu Ci Convivi        Fabri Fibra
9162    0.9788       Cinque a uno  Colle Der Fomento
6082    0.9785           S.N.O.B.               J-Ax

Bottom 10 Lowest flatness:

       flatness                                         title   name_artist
8816     0.1094                                     Balaclava      Highsnob
10969    0.1707                  Faccio Brutto (2nd Roof RMX)         Fedez
10970    0.1764  Pensavo fosse amore e invece... (Roofio RMX)         Fedez
8332     0.1841                           Una Più Del Diavolo        MadMan
7357     0.1884                  Haterproof (Detto Fatto RMX)      Gemitaiz
10315    0.1929                                Troppo piccola        Caneda
6428     0.1951                                          Casa        Entics
10661    0.1968                                   Uno a Cento  Mondo Marcio
1380     0.1983                                  Benji & Fede       Skioffi
6387     0.2014                                   Fresh flash        Entics

based on those values alone, it's hard to say if some of those outliers are errors, so in this preprocessing step nothing will be done

### spectral_complexity

In [21]:
analyze_distribution(df_tracks, 'spectral_complexity', 'spectral_complexity', 'hotpink')

alt.VConcatChart(...)

Top 10 Highest spectral_complexity:

       spectral_complexity                title  name_artist
177                61.2225         Alfa (Intro)         Alfa
6070               56.9958      Miss & Mr. Hyde         J-Ax
7504               54.4348           Plenilunio        Slait
3391               54.2955      SoldiSoldiSoldi  Articolo 31
3413               54.0795  LA FIERA DEL CRINGE  Articolo 31
6113               53.9999         Sono di moda         J-Ax
10923              53.9990        Santa Madonna        Fedez
5757               53.6906           Brain Suck        Shade
8823               53.5247         No Boyfriend     Highsnob
6109               53.0098            Reci-divo         J-Ax

Bottom 10 Lowest spectral_complexity:

,spectral_complexity,title,name_artist
8317,0.0000,Madtadone 2015,MadMan
4882,0.0000,In Tv,Vacca
10969,0.3083,Faccio Brutto (2nd Roof RMX),Fedez
8834,0.3816,Rooftop,Highsnob
8161,0.6682,Timeless Spirit,Shablo
10970,0.9473,Pensavo fosse amore e invece... (Roofio RMX),Fedez
1099,0.9565,MM & Guè Pequeno,Guè
10656,1.2338,Freestyle,Mondo Marcio
3684,1.2534,Chiedi Chiedi,Frankie hi-nrg mc
8799,1.3735,Fisher Price,Highsnob

Remove tracks with 0 spectral complexity.

In [22]:
complexity_min_threshold = 0.001

condition = df_tracks['spectral_complexity'] < complexity_min_threshold

print(f"Removing {condition.sum()} tracks with Spectral Complexity < {complexity_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'spectral_complexity']])

df_tracks.loc[condition, 'spectral_complexity'] = np.nan

Removing 2 tracks with Spectral Complexity < 0.001:

            id           title name_artist  spectral_complexity
4882  TR508832           In Tv       Vacca                  0.0
8317  TR591502  Madtadone 2015      MadMan                  0.0

### rms

In [23]:
analyze_distribution(df_tracks, 'rms', 'rms', 'yellowgreen')

alt.VConcatChart(...)

Top 10 Highest rms:

          rms                    title     name_artist
10731  0.6219       Non tornare a casa   Fred De Palma
177    0.5916             Alfa (Intro)            Alfa
7578   0.5273                    Si si        Tony Boy
7550   0.4712            Fino a domani        Tony Boy
9788   0.4561             Vuoto (2007)           Salmo
9554   0.4487                  POPCORN       Dani Faiv
9854   0.4454          The Bootyshaker        Tormento
252    0.4407  6 1 akkollino freestyle          thasup
5487   0.4273            Ode Con Creta  Dargen D’Amico
10070  0.4221                 100 OPPS           Shiva

Bottom 10 Lowest rms:

          rms                                         title        name_artist
8317   0.0000                                Madtadone 2015             MadMan
4882   0.0000                                         In Tv              Vacca
8834   0.0041                                       Rooftop           Highsnob
1099   0.0085                              MM & Guè Pequeno                Guè
10969  0.0093                  Faccio Brutto (2nd Roof RMX)              Fedez
10656  0.0103                                     Freestyle       Mondo Marcio
10970  0.0106  Pensavo fosse amore e invece... (Roofio RMX)              Fedez
3684   0.0112                                 Chiedi Chiedi  Frankie hi-nrg mc
8161   0.0114                               Timeless Spirit             Shablo
7025   0.0123                                  OUTRO [2024]            Mr.Rain

Remove tracks with 0 RMS (silence)

In [24]:
rms_min_threshold = 0.0001

condition = df_tracks['rms'] < rms_min_threshold

print(f"Removing {condition.sum()} tracks with RMS < {rms_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'rms']])

df_tracks.loc[condition, 'rms'] = np.nan

Removing 2 tracks with RMS < 0.0001:

            id           title name_artist  rms
4882  TR508832           In Tv       Vacca  0.0
8317  TR591502  Madtadone 2015      MadMan  0.0

### zcr

In [25]:
analyze_distribution(df_tracks, 'zcr', 'zcr', 'darkturquoise')

alt.VConcatChart(...)

Top 10 Highest zcr:

         zcr                title     name_artist
8332  0.2683  Una Più Del Diavolo          MadMan
8339  0.2158   Notti Di Provincia          MadMan
254   0.2050   COVID-19 Freestyle          thasup
55    0.1856    BRITISH PROV 2014   Rosa Chemical
8978  0.1778        Rifletti Bene         Rancore
9080  0.1692       Branco di iene  Dark Polo Gang
1057  0.1673       Il Sesto Senso             Guè
4671  0.1629       2020 Freestyle          Madame
1084  0.1564              Cartier             Guè
3176  0.1476            Ice Cream   Sfera Ebbasta

Bottom 10 Lowest zcr:

          zcr                 title    name_artist
8317   0.0000        Madtadone 2015         MadMan
4882   0.0000                 In Tv          Vacca
3159   0.0083               Squali*  Sfera Ebbasta
1951   0.0106         Le Mie Amiche        La Pina
365    0.0117  -3 (PERDERE IL VOLO)          Lazza
261    0.0118             Veri Fra*         thasup
7550   0.0136         Fino a domani       Tony Boy
10148  0.0138     Back In Blood RMX          Shiva
3564   0.0147         El Chico Loco          Neffa
368    0.0155              Silenzio          Lazza

Remove tracks with 0 ZCR.

In [26]:
zcr_min_threshold = 0.001

condition = df_tracks['zcr'] < zcr_min_threshold

print(f"Removing {condition.sum()} tracks with ZCR < {zcr_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'zcr']])

df_tracks.loc[condition, 'zcr'] = np.nan

Removing 2 tracks with ZCR < 0.001:

            id           title name_artist  zcr
4882  TR508832           In Tv       Vacca  0.0
8317  TR591502  Madtadone 2015      MadMan  0.0

### pitch

In [27]:
analyze_distribution(df_tracks, 'pitch', 'pitch', 'tan')

alt.VConcatChart(...)

Top 10 Highest pitch:

          pitch                        title        name_artist
5068  3993.0203          MILANO SUSHI & COCA          M¥SS KETA
8430  3813.9158                CCL (Prequel)      Achille Lauro
7022  3804.6853                  Talent Show            Mr.Rain
3515  3793.3868  Beat Box (Per Improvvisare)        Articolo 31
28    3779.4293                   Ramoscelli      Rosa Chemical
6282  3760.3648                Ripetutamente           99 Posse
6325  3744.9862                    La Scelta           99 Posse
3696  3733.1982            Calma... Calma...  Frankie hi-nrg mc
6644  3723.3517   Ombre Cinesi (Strumentale)            Don Joe
3721  3701.5820            O Tempora O Mores  Frankie hi-nrg mc

Bottom 10 Lowest pitch:

           pitch              title    name_artist
8317      0.0000     Madtadone 2015         MadMan
4882      2.8762              In Tv          Vacca
3159    491.2475            Squali*  Sfera Ebbasta
7025    814.3465       OUTRO [2024]        Mr.Rain
5243    849.8850              Intro          Luchè
10630  1006.4606  Patto col diavolo   Mondo Marcio
6782   1016.7426         L’Eternità          Nesli
10334  1020.8130   Il peggior night         Caneda
10325  1051.3296         Strichnina         Caneda
8516   1054.5274    Malato Di Vuoto  Achille Lauro

Remove tracks with low pitch value (most likely errors).

In [28]:
pitch_min_threshold = 3

condition = df_tracks['pitch'] < pitch_min_threshold

print(f"Removing {condition.sum()} tracks with Pitch < {pitch_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'pitch']])

df_tracks.loc[condition, 'pitch'] = np.nan

Removing 2 tracks with Pitch < 3:

            id           title name_artist   pitch
4882  TR508832           In Tv       Vacca  2.8762
8317  TR591502  Madtadone 2015      MadMan  0.0000

### loudness

In [29]:
analyze_distribution(df_tracks, 'loudness', 'loudness', 'silver')

alt.VConcatChart(...)

Top 10 Highest loudness:

       loudness                    title     name_artist
177     81.9478             Alfa (Intro)            Alfa
7578    70.6590                    Si si        Tony Boy
10731   69.7137       Non tornare a casa   Fred De Palma
7550    61.5836            Fino a domani        Tony Boy
9788    61.0195             Vuoto (2007)           Salmo
252     58.9279  6 1 akkollino freestyle          thasup
9554    58.4856                  POPCORN       Dani Faiv
9854    58.0158          The Bootyshaker        Tormento
10070   54.2572                 100 OPPS           Shiva
5487    54.1857            Ode Con Creta  Dargen D’Amico

Bottom 10 Lowest loudness:

,loudness,title,name_artist
4882,0.0000,In Tv,Vacca
8317,0.0000,Madtadone 2015,MadMan
8834,0.2030,Rooftop,Highsnob
10969,0.3390,Faccio Brutto (2nd Roof RMX),Fedez
1099,0.3712,MM & Guè Pequeno,Guè
10970,0.3980,Pensavo fosse amore e invece... (Roofio RMX),Fedez
10656,0.4179,Freestyle,Mondo Marcio
3684,0.4360,Chiedi Chiedi,Frankie hi-nrg mc
8161,0.4364,Timeless Spirit,Shablo
7025,0.5082,OUTRO [2024],Mr.Rain

Remove tracks with 0 Loudness.

In [30]:
loudness_min_threshold = 0.001

condition = df_tracks['loudness'] < loudness_min_threshold

print(f"Removing {condition.sum()} tracks with Loudness < {loudness_min_threshold}:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'loudness']])

df_tracks.loc[condition, 'loudness'] = np.nan

Removing 2 tracks with Loudness < 0.001:

            id           title name_artist  loudness
4882  TR508832           In Tv       Vacca       0.0
8317  TR591502  Madtadone 2015      MadMan       0.0

## Missing data analysis

In [31]:
def prepare_missing_data(df, dataset_name):
    if df is None:
        return pd.DataFrame()
    
    total_rows = len(df)
    missing_counts = df.isnull().sum()
    present_counts = df.notnull().sum()
    
    df_missing = pd.DataFrame({
        'Column': missing_counts.index,
        'Count': missing_counts.values,
        'Status': 'Missing',
        'Dataset': dataset_name
    })
    
    df_present = pd.DataFrame({
        'Column': present_counts.index,
        'Count': present_counts.values,
        'Status': 'Present',
        'Dataset': dataset_name
    })
    
    combined = pd.concat([df_missing, df_present])
    
    combined['Percentage'] = combined['Count'] / total_rows
    
    return combined

viz_data_tracks = prepare_missing_data(df_tracks, 'Tracks')
viz_data_artists = prepare_missing_data(df_artists, 'Artists')
full_viz_data = pd.concat([viz_data_tracks, viz_data_artists])

base = alt.Chart(full_viz_data).encode(
    x=alt.X('Percentage', axis=alt.Axis(format='%'), title='Percentage'),
    y=alt.Y('Column', sort=alt.EncodingSortField(field='Percentage', op='min', order='ascending'), title=None),
    tooltip=[
        'Column', 
        'Status', 
        alt.Tooltip('Count', format=','), 
        alt.Tooltip('Percentage', format='.1%')
    ]
)

# Create the stacked bars
bars = base.mark_bar().encode(
    color=alt.Color(
        'Status', 
        scale=alt.Scale(domain=['Present', 'Missing'], range=['#4c78a8', '#e45756']),
        legend=alt.Legend(title="Data Status")
    ),
    order=alt.Order('Status', sort='ascending') # Ensure consistent stacking order
)

# Facet the chart into two columns (one for Tracks, one for Artists)
# We use resolve_scale(y='independent') so each chart shows its own columns
chart = bars.properties(
    width=400,
    height=600  # Taller height to accommodate many columns
).facet(
    column=alt.Column('Dataset', title='Dataset missing data', sort=['Tracks', 'Artists'])
).resolve_scale(
    y='independent' 
)

display(chart)

alt.FacetChart(...)

## Correlation Analysis of Tracks Data

This section performs a correlation analysis on the `cleaned_tracks.csv` dataset, which contains cleaned data from the previous analysis steps.

The focus will be on identifying relationships between numerical variables (audio features, lyrics statistics, track popularity).

We filter the dataframe to include only relevant numerical columns for correlation analysis (grouped by type for clarity).

In [32]:
df_tracks = pd.read_csv(dataset_path, sep=',')

numerical_cols = [
    #metadata
    'popularity', 
    'stats_pageviews',
    'duration_ms',
    
    #audio features
    'bpm', 
    'centroid', 
    'rolloff', 
    'flux', 
    'rms', 
    'zcr', 
    'flatness', 
    'spectral_complexity', 
    'pitch', 
    'loudness',
    
    #lyrics stats
    'n_sentences', 
    'n_tokens', 
    'tokens_per_sent', 
    'char_per_tok', 
    'lexical_density', 
    'avg_token_per_clause',
    'swear_IT',
    'swear_EN'
]

cols_to_use = [col for col in numerical_cols if col in df_tracks.columns]

df_corr = df_tracks[cols_to_use].copy()

#ensure all data is numeric (coercing errors if any remain)
for col in df_corr.columns:
    df_corr[col] = pd.to_numeric(df_corr[col], errors='coerce')

print(f"selected {len(df_corr.columns)} numerical columns for analysis.")

selected 21 numerical columns for analysis.

We use the Pearson correlation coefficient to measure linear relationships. To visualize this in Altair (which requires long-format data), we will also transform the matrix and mask the upper triangle.

In [33]:
#calculate standard correlation matrix
corr_matrix = df_corr.corr()

#display the top 5 positive correlations (excluding self-correlation)
print("Top 5 Positive Correlations:")
c = corr_matrix.abs()
s = c.unstack()
so = s.sort_values(kind="quicksort", ascending=False)
print(so[so < 1.0].head(10)) #top 5 pairs (duplicates appear twice)

Top 5 Positive Correlations:
rms          loudness       0.995586
loudness     rms            0.995586
rolloff      zcr            0.969082
zcr          rolloff        0.969082
n_tokens     n_sentences    0.868337
n_sentences  n_tokens       0.868337
zcr          centroid       0.864166
centroid     zcr            0.864166
             rolloff        0.775364
rolloff      centroid       0.775364
dtype: float64

We now plot the correlation matrix using Altair.

In [34]:
#prepare data for altair
corr_long = corr_matrix.stack().reset_index()
corr_long.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_long['Correlation_Label'] = corr_long['Correlation'].apply(lambda x: f"{x:.2f}")

base = alt.Chart(corr_long).encode(
    x=alt.X('Variable 2', title=None, sort=cols_to_use),
    y=alt.Y('Variable 1', title=None, sort=cols_to_use)
)

heatmap = base.mark_rect().encode(
    color=alt.Color(
        'Correlation',
        scale=alt.Scale(scheme='redblue', domain=[-1, 1]),
        legend=alt.Legend(title="Correlation")
    ),
    tooltip=['Variable 1', 'Variable 2', alt.Tooltip('Correlation', format='.2f')]
)

text = base.mark_text(size=8).encode(
    text='Correlation_Label',
    color=alt.condition(
        alt.expr.abs(alt.datum.Correlation) > 0.5,  #if absolute correlation is high
        alt.value('white'),                    #use white text
        alt.value('black')                     #else use black text
    )
)

chart = (heatmap + text).properties(
    title='Pearson correlation matrix (audio features, lyrics stats, metadata)',
    width=800,
    height=800
)

chart.interactive()

alt.LayerChart(...)

using a 0.9 threshold, then we could delete one of the columns between rolloff and zcr, and one of the columns between loudness and rms:
- rolloff will be kept over zcr, as the rolloff is a specific frequency below which a certain percentage of the total spectral energy lies, while zcr is the rate at which the signal changes sign (Higher ZCR means noisier or more percussive sounds), so zcr is more sensitive to noise.
- loudness will be kept over rms, as the loudness is measured in decibels (dB), which is a logarithmic scale that matches how human ears perceive volume changes. rms is linear, so its distribution can be skewed (loudness, being logarithmic, follows a more Gaussian distribution).