# Data distribution analysis

In [1]:
import pandas as pd
import altair as alt
import numpy as np
import os

alt.data_transformers.enable("vegafusion")

tracks_path = os.path.join('..', 'dataset', 'tracks.csv')
dataset_path = os.path.join('..', 'dataset', 'cleaned_tracks.csv')
artists_path = os.path.join('..', 'dataset', 'artists.csv')

df_tracks = pd.read_csv(tracks_path, sep=',')
df_artists = pd.read_csv(artists_path, sep=';')

## Univariant distribution analysis

In [41]:
def analyze_distribution(df, col, title, color_histo, bins=40):
    
    chart_data = df[[col, 'title', 'name_artist']].dropna().copy()
    chart_data[col] = pd.to_numeric(chart_data[col], errors='coerce')
    
    hist = alt.Chart(chart_data).mark_bar(opacity=0.7, color=color_histo).encode(
        x=alt.X(col, bin=alt.Bin(maxbins=bins), title=title),
        y=alt.Y('count()', title='Count'),
        tooltip=[alt.Tooltip(col, bin=True), 'count()']
    ).properties(title=f'Distribution of Tracks by {title}', width=800, height=300)
    
    box = alt.Chart(chart_data).mark_boxplot().encode(
        x=alt.X(col, title=title),
        tooltip=[alt.Tooltip(f'min({col})'), alt.Tooltip(f'max({col})')]
    ).properties(width=800, height=100)
    
    display(hist & box)
    
    print(f"Top 10 Highest {title}:")
    display(chart_data.sort_values(by=col, ascending=False).head(10))
    
    print(f"Bottom 10 Lowest {title}:")
    display(chart_data.sort_values(by=col, ascending=True).head(10))

### bpm

In [42]:
analyze_distribution(df_tracks, 'bpm', 'bpm', 'darkred')

alt.VConcatChart(...)

Top 10 Highest bpm:

         bpm                      title    name_artist
4617  191.41              Carta E Penna        Mistico
4048  184.57  Prologo Di Un Fonoromanzo      Caparezza
8971  184.57       Dissotterracci n. 21        Rancore
5193  184.57                 Lieto fine          Luchè
2507  184.57               The Banfator       Mistaman
8457  184.57        Hollywood Boulevard  Achille Lauro
1827  184.57     Selezione All'Ingresso      Club Dogo
8076  184.57              Forever alone           Coez
4168  184.57                  Classe 73  Bassi Maestro
3572  184.57                 Wicked Man          Neffa

Bottom 10 Lowest bpm:

         bpm                           title name_artist
6702   59.97                    Guardo Fuori       Nesli
5104   59.99                     BLING BLING   M¥SS KETA
4779   60.01                Nonostante Tutto       Vacca
9222   63.00             Amarti, Rispettarti   Sottotono
6293   64.19                 Povera Vita Mia    99 Posse
2442   66.03              Se parlassi con te    Mistaman
3654   66.86                          Realtà       Neffa
7662   67.47                       Sintonia*    Tony Boy
10174  67.50                 C'Era Una Volta      Caneda
4596   67.52  DOMANI FREESTYLE COLLECTION #1        Ensi

while the other tracks have reasonable bmp values, Madtadone 2015 by MadMan have an error value which will be set to NaN

In [4]:
condition = (df_tracks['id'] == 'TR591502')
print("removed error track:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'bpm']])
df_tracks.loc[condition, 'bpm'] = np.nan

analyze_distribution(df_tracks, 'bpm', 'bpm', 'darkred')

removed error track:

            id           title name_artist     bpm
8317  TR591502  Madtadone 2015      MadMan  738.27

alt.VConcatChart(...)

### centroid

In [5]:
analyze_distribution(df_tracks, 'centroid', 'centroid', 'darkblue')

alt.VConcatChart(...)

the same track in the bpm analysis have also an error value in the spectral centroid, as well as another track named 'In Tv'. 'Una Più Del Diavolo' might be an outlier, as there are more MadMan songs with high spectral centroid.

In [7]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error centroid from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'centroid']])

df_tracks.loc[condition, 'centroid'] = np.nan

Removed error centroid from tracks:

            id           title name_artist  centroid
4882  TR508832           In Tv       Vacca    0.0004
8317  TR591502  Madtadone 2015      MadMan    0.0000

### rolloff

In [8]:
analyze_distribution(df_tracks, 'rolloff', 'rolloff', 'darkgreen')

alt.VConcatChart(...)

the same tracks in the spectral centroid analysis have also an error value in the spectral rolloff. 'Una Più Del Diavolo' might be again an outlier, as there are more MadMan songs with high spectral centroid.

In [10]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error rolloff from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'rolloff']])

df_tracks.loc[condition, 'rolloff'] = np.nan

Removed error rolloff from tracks:

            id           title name_artist  rolloff
4882  TR508832           In Tv       Vacca  14.4718
8317  TR591502  Madtadone 2015      MadMan   0.0000

### flux

In [11]:
analyze_distribution(df_tracks, 'flux', 'flux', 'darkorange')

alt.VConcatChart(...)

the same tracks in the spectral rolloff analysis have also an error value in the spectral flux.

### flatness

In [13]:
analyze_distribution(df_tracks, 'flatness', 'flatness', 'purple')

alt.VConcatChart(...)

based on those values alone, it's hard to say if some of those outliers are errors, so in this preprocessing step nothing will be done

### spectral_complexity

In [15]:
analyze_distribution(df_tracks, 'spectral_complexity', 'spectral_complexity', 'hotpink')

alt.VConcatChart(...)

the same tracks in the spectral flux analysis have also an error value in the spectral complexity.

In [17]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error spectral_complexity from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'spectral_complexity']])

df_tracks.loc[condition, 'spectral_complexity'] = np.nan

Removed error spectral_complexity from tracks:

            id           title name_artist  spectral_complexity
4882  TR508832           In Tv       Vacca                  0.0
8317  TR591502  Madtadone 2015      MadMan                  0.0

### rms

In [18]:
analyze_distribution(df_tracks, 'rms', 'rms', 'yellowgreen')

alt.VConcatChart(...)

the same tracks in the spectral complexity analysis have also an error value in the root mean square

In [20]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error rms from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'rms']])

df_tracks.loc[condition, 'rms'] = np.nan

Removed error rms from tracks:

            id           title name_artist  rms
4882  TR508832           In Tv       Vacca  0.0
8317  TR591502  Madtadone 2015      MadMan  0.0

### zcr

In [21]:
analyze_distribution(df_tracks, 'zcr', 'zcr', 'darkturquoise')

alt.VConcatChart(...)

the same tracks in the root mean square analysis have also an error value in the zero crossing rate

In [23]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error zcr from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'zcr']])

df_tracks.loc[condition, 'zcr'] = np.nan

Removed error zcr from tracks:

            id           title name_artist  zcr
4882  TR508832           In Tv       Vacca  0.0
8317  TR591502  Madtadone 2015      MadMan  0.0

### pitch

In [24]:
analyze_distribution(df_tracks, 'pitch', 'pitch', 'tan')

alt.VConcatChart(...)

the same tracks in the zero crossing rate analysis have also an error value in the pitch

In [26]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error pitch from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'pitch']])

df_tracks.loc[condition, 'pitch'] = np.nan

Removed error pitch from tracks:

            id           title name_artist   pitch
4882  TR508832           In Tv       Vacca  2.8762
8317  TR591502  Madtadone 2015      MadMan  0.0000

### loudness

In [27]:
analyze_distribution(df_tracks, 'loudness', 'loudness', 'silver')

alt.VConcatChart(...)

the same tracks in the pitch analysis have also an error value in the loudness

In [29]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df_tracks['id'].isin(ids_to_fix)

print("Removed error loudness from tracks:")
display(df_tracks[condition][['id', 'title', 'name_artist', 'loudness']])

df_tracks.loc[condition, 'loudness'] = np.nan

Removed error loudness from tracks:

            id           title name_artist  loudness
4882  TR508832           In Tv       Vacca       0.0
8317  TR591502  Madtadone 2015      MadMan       0.0

## Missing data analysis

In [30]:
def prepare_missing_data(df, dataset_name):
    if df is None:
        return pd.DataFrame()
    
    total_rows = len(df)
    missing_counts = df.isnull().sum()
    present_counts = df.notnull().sum()
    
    df_missing = pd.DataFrame({
        'Column': missing_counts.index,
        'Count': missing_counts.values,
        'Status': 'Missing',
        'Dataset': dataset_name
    })
    
    df_present = pd.DataFrame({
        'Column': present_counts.index,
        'Count': present_counts.values,
        'Status': 'Present',
        'Dataset': dataset_name
    })
    
    combined = pd.concat([df_missing, df_present])
    
    combined['Percentage'] = combined['Count'] / total_rows
    
    return combined

viz_data_tracks = prepare_missing_data(df_tracks, 'Tracks')
viz_data_artists = prepare_missing_data(df_artists, 'Artists')
full_viz_data = pd.concat([viz_data_tracks, viz_data_artists])

base = alt.Chart(full_viz_data).encode(
    x=alt.X('Percentage', axis=alt.Axis(format='%'), title='Percentage'),
    y=alt.Y('Column', sort=alt.EncodingSortField(field='Percentage', op='min', order='ascending'), title=None),
    tooltip=[
        'Column', 
        'Status', 
        alt.Tooltip('Count', format=','), 
        alt.Tooltip('Percentage', format='.1%')
    ]
)

# Create the stacked bars
bars = base.mark_bar().encode(
    color=alt.Color(
        'Status', 
        scale=alt.Scale(domain=['Present', 'Missing'], range=['#4c78a8', '#e45756']),
        legend=alt.Legend(title="Data Status")
    ),
    order=alt.Order('Status', sort='ascending') # Ensure consistent stacking order
)

# Facet the chart into two columns (one for Tracks, one for Artists)
# We use resolve_scale(y='independent') so each chart shows its own columns
chart = bars.properties(
    width=400,
    height=600  # Taller height to accommodate many columns
).facet(
    column=alt.Column('Dataset', title='Dataset missing data', sort=['Tracks', 'Artists'])
).resolve_scale(
    y='independent' 
)

display(chart)

alt.FacetChart(...)

## Correlation Analysis of Tracks Data

This section performs a correlation analysis on the `cleaned_tracks.csv` dataset, which contains cleaned data from the previous analysis steps.

The focus will be on identifying relationships between numerical variables (audio features, lyrics statistics, track popularity).

We filter the dataframe to include only relevant numerical columns for correlation analysis (grouped by type for clarity).

In [31]:
df_tracks = pd.read_csv(dataset_path, sep=',')

numerical_cols = [
    #metadata
    'popularity', 
    'stats_pageviews',
    'duration_ms',
    
    #audio features
    'bpm', 
    'centroid', 
    'rolloff', 
    'flux', 
    'rms', 
    'zcr', 
    'flatness', 
    'spectral_complexity', 
    'pitch', 
    'loudness',
    
    #lyrics stats
    'n_sentences', 
    'n_tokens', 
    'tokens_per_sent', 
    'char_per_tok', 
    'lexical_density', 
    'avg_token_per_clause',
    'swear_IT',
    'swear_EN'
]

cols_to_use = [col for col in numerical_cols if col in df_tracks.columns]

df_corr = df_tracks[cols_to_use].copy()

#ensure all data is numeric (coercing errors if any remain)
for col in df_corr.columns:
    df_corr[col] = pd.to_numeric(df_corr[col], errors='coerce')

print(f"selected {len(df_corr.columns)} numerical columns for analysis.")

selected 21 numerical columns for analysis.

We use the Pearson correlation coefficient to measure linear relationships. To visualize this in Altair (which requires long-format data), we will also transform the matrix and mask the upper triangle.

In [32]:
#calculate standard correlation matrix
corr_matrix = df_corr.corr()

#display the top 5 positive correlations (excluding self-correlation)
print("Top 5 Positive Correlations:")
c = corr_matrix.abs()
s = c.unstack()
so = s.sort_values(kind="quicksort", ascending=False)
print(so[so < 1.0].head(10)) #top 5 pairs (duplicates appear twice)

Top 5 Positive Correlations:
rms          loudness       0.995586
loudness     rms            0.995586
rolloff      zcr            0.969082
zcr          rolloff        0.969082
n_tokens     n_sentences    0.868337
n_sentences  n_tokens       0.868337
zcr          centroid       0.864166
centroid     zcr            0.864166
             rolloff        0.775364
rolloff      centroid       0.775364
dtype: float64

We now plot the correlation matrix using Altair.

In [33]:
#prepare data for altair
corr_long = corr_matrix.stack().reset_index()
corr_long.columns = ['Variable 1', 'Variable 2', 'Correlation']

corr_long['Correlation_Label'] = corr_long['Correlation'].apply(lambda x: f"{x:.2f}")

base = alt.Chart(corr_long).encode(
    x=alt.X('Variable 2', title=None, sort=cols_to_use),
    y=alt.Y('Variable 1', title=None, sort=cols_to_use)
)

heatmap = base.mark_rect().encode(
    color=alt.Color(
        'Correlation',
        scale=alt.Scale(scheme='redblue', domain=[-1, 1]),
        legend=alt.Legend(title="Correlation")
    ),
    tooltip=['Variable 1', 'Variable 2', alt.Tooltip('Correlation', format='.2f')]
)

text = base.mark_text(size=8).encode(
    text='Correlation_Label',
    color=alt.condition(
        alt.expr.abs(alt.datum.Correlation) > 0.5,  #if absolute correlation is high
        alt.value('white'),                    #use white text
        alt.value('black')                     #else use black text
    )
)

chart = (heatmap + text).properties(
    title='Pearson correlation matrix (audio features, lyrics stats, metadata)',
    width=800,
    height=800
)

chart.interactive()

alt.LayerChart(...)

using a 0.9 threshold, then we could delete one of the columns between rolloff and zcr, and one of the columns between loudness and rms:
- rolloff will be kept over zcr, as the rolloff is a specific frequency below which a certain percentage of the total spectral energy lies, while zcr is the rate at which the signal changes sign (Higher ZCR means noisier or more percussive sounds), so zcr is more sensitive to noise.
- loudness will be kept over rms, as the loudness is measured in decibels (dB), which is a logarithmic scale that matches how human ears perceive volume changes. rms is linear, so its distribution can be skewed (loudness, being logarithmic, follows a more Gaussian distribution).