## Tracks data analysis

Let's assert tracks data analysis by taking a first inspection of the track dataset

In [1]:
import pandas as pd
import altair as alt
from os import path
import numpy as np
import re
import spacy
import warnings
from langdetect import detect, DetectorFactory
from langdetect.lang_detect_exception import LangDetectException

alt.data_transformers.enable("vegafusion")

dataset_path = path.join('..', 'dataset', 'tracks.csv')
df = pd.read_csv(dataset_path, sep=',')

DetectorFactory.seed = 0

def load_spacy_models():
    models_tokenizers = {}
    models_pos_taggers = {}
    
    #lightweight spacy models
    try:
        nlp_it_light = spacy.load('it_core_news_sm', 
                                  disable=['parser', 'tagger', 'ner', 'lemmatizer'])
        nlp_it_light.add_pipe('sentencizer')
        models_tokenizers['it'] = nlp_it_light
        
        nlp_en_light = spacy.load('en_core_web_sm', 
                                  disable=['parser', 'tagger', 'ner', 'lemmatizer'])
        nlp_en_light.add_pipe('sentencizer')
        models_tokenizers['en'] = nlp_en_light
        
    except (IOError, ImportError):
        print("Error: spaCy lightweight models not found")
        return None, None

    #POS tagging models (slower since we keep tagger and parser enabled)
    try:
        models_pos_taggers['it'] = spacy.load('it_core_news_sm', 
                                             disable=['ner', 'lemmatizer'])
        
        models_pos_taggers['en'] = spacy.load('en_core_web_sm', 
                                             disable=['ner', 'lemmatizer'])
        
    except (IOError, ImportError):
        print("Error: spaCy POS models not found")
        return None, None

    return models_tokenizers, models_pos_taggers

models_tokenizers, models_pos_taggers = load_spacy_models()

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11166 entries, 0 to 11165
Data columns (total 45 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    11166 non-null  object
 1   id_artist             11166 non-null  object
 2   name_artist           11166 non-null  object
 3   full_title            11166 non-null  object
 4   title                 11166 non-null  object
 5   featured_artists      3517 non-null   object
 6   primary_artist        11166 non-null  object
 7   language              11061 non-null  object
 8   album                 9652 non-null   object
 9   stats_pageviews       4642 non-null   float64
 10  swear_IT              11166 non-null  int64
 11  swear_EN              11166 non-null  int64
 12  swear_IT_words        11166 non-null  object
 13  swear_EN_words        11166 non-null  object
 14  year                  10766 non-null  object
 15  month                 9969 non-null   float64
 16  day                   9843 non-null   float64
 17  n_sentences           11090 non-null  float64
 18  n_tokens              11090 non-null  float64
 19  tokens_per_sent       11090 non-null  float64
 20  char_per_tok          11090 non-null  float64
 21  lexical_density       11090 non-null  float64
 22  avg_token_per_clause  11090 non-null  float64
 23  bpm                   11102 non-null  float64
 24  centroid              11102 non-null  float64
 25  rolloff               11102 non-null  float64
 26  flux                  11102 non-null  float64
 27  rms                   11102 non-null  float64
 28  zcr                   11102 non-null  float64
 29  flatness              11102 non-null  float64
 30  spectral_complexity   11102 non-null  float64
 31  pitch                 11102 non-null  float64
 32  loudness              11102 non-null  float64
 33  album_name            11088 non-null  object
 34  album_release_date    11088 non-null  object
 35  album_type            11088 non-null  object
 36  disc_number           11088 non-null  float64
 37  track_number          11088 non-null  float64
 38  duration_ms           11088 non-null  float64
 39  explicit              11088 non-null  object
 40  popularity            11164 non-null  object
 41  album_image           11088 non-null  object
 42  id_album              11088 non-null  object
 43  lyrics                11163 non-null  object
 44  modified_popularity   11166 non-null  bool
dtypes: bool(1), float64(22), int64(2), object(20)
memory usage: 3.8+ MB

year, month, day, n_sentence, n_tokens, disc_numer, track_number, popularity should all be Int64 (or at least float64: year and popularity are object), explicit should be bool

validation helper function checking expected types validity

In [3]:
def check_type_validity(value, expected_type):
    return not isinstance(value, expected_type)

before the analysis, let's strip the string columns from any invisible unicode characters:

In [4]:
cols_to_strip = [
    "album_name", "album_type", "album_image",
    "id_album", "id", "id_artist", "name_artist", "full_title",
    "title", "featured_artists", "primary_artist", "language", "album"
]

zero_width_pattern = r"[\u200b\u200c\u200d\uFEFF]"

nbsp_pattern = r"[\xa0]"

for col in cols_to_strip:
    if col in df.columns:
        #strip only non empty rows
        non_null_mask = df[col].notna()
        
        df.loc[non_null_mask, col] = (
            df.loc[non_null_mask, col]
            .astype(str)
            .str.replace(zero_width_pattern, "", regex=True)
            .str.replace(nbsp_pattern, " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

print("string columns have been stripped and cleaned")

string columns have been stripped and cleaned

### id

In [5]:
invalid_elems = df[df['id'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['id'])

nan_indexes = df.index[df['id'].isna()].tolist()
print(f"number of missing values in id: {len(nan_indexes)}")

unique_ids = df['id'].nunique()
print(f"number of unique ids: {unique_ids}")

Series([], Name: id, dtype: object)
number of missing values in id: 0
number of unique ids: 11093

there are no missing id values in the dataset.
all the ids are strings with the following format "TR{unique_num_id}".
there are less unique ids than the number of rows (11093 < 11166), let's check if they come from duplicate songs or there are different songs with the same id

In [6]:
not_unique_ids = df['id'].value_counts()
not_unique_ids = not_unique_ids[not_unique_ids > 1]
print(f"there are {len(not_unique_ids)} not unique ids:")
print(not_unique_ids)

not_unique_ids_list = not_unique_ids.index.tolist()

identical_duplicates = []
different_duplicates = []
mixed_duplicates = [] #ids with both identical and different rows

for dup_id in not_unique_ids_list:
    duplicate_rows = df[df['id'] == dup_id]
    num_occurrences = len(duplicate_rows)
    
    unique_songs = duplicate_rows[['name_artist', 'title']].drop_duplicates()
    num_unique = len(unique_songs)

    if num_unique == 1:
        identical_duplicates.append(dup_id) #duplicate rows
    elif num_unique == num_occurrences:
        different_duplicates.append(dup_id) #different songs
    else:
        mixed_duplicates.append(dup_id) #duplicate rows and different songs

print(f"{len(identical_duplicates)} come from duplicate songs, ",
      f"{len(different_duplicates)} come from different songs with the same id, ",
      f"{len(mixed_duplicates)} have both duplicate and different songs")

there are 71 not unique ids:
id
TR367132    4
TR978886    2
TR987615    2
TR690925    2
TR772702    2
           ..
TR245683    2
TR903275    2
TR679972    2
TR247772    2
TR261964    2
Name: count, Length: 71, dtype: int64
0 come from duplicate songs,  70 come from different songs with the same id,  1 have both duplicate and different songs

of the 71 not unique ids, 70 refers to different songs, meaning that there are no duplicate songs respect to those ids, but there are ids which refers to multiple songs.

by analyzing more in depth the case with both duplicate and different songs:

In [7]:
for dup_id in mixed_duplicates: #iterating for a "general" solution, but in this case wouldn't be necessary
    duplicate_artist_song = df[df['id'] == dup_id]
    unique_songs = duplicate_artist_song[['name_artist', 'title']].drop_duplicates()
    print(f"for id {dup_id}, there are {len(unique_songs)} unique songs:")
    
    for idx, row in unique_songs.iterrows():
        song_rows = duplicate_artist_song[
            (duplicate_artist_song['name_artist'] == row['name_artist']) &
            (duplicate_artist_song['title'] == row['title'])]
        
        print(f"\t- '{row['title']}' by artist: {row['name_artist']}, occuring {len(song_rows)} times")
        
        if len(song_rows) != 1: #more than one occurrence
            first_row = song_rows.iloc[0]
            all_identical = True
            differing_columns = []

            for col in song_rows.columns:
                unique_values = song_rows[col].nunique()
                if unique_values > 1:
                    all_identical = False
                    differing_columns.append(col)
            
            if not all_identical:
                print(f"\t\tdiffering columns: {differing_columns}\n")
                
                #for col in differing_columns: #uncomment this for see values of different rows
                        #values = song_rows[col].tolist()
                        #print(f"\t\t• {col}:")
                        #for i, val in enumerate(values):
                            #print(f"\t\t\tRow {i+1}: {val}")

for id TR367132, there are 2 unique songs:
	- 'BUGIE' by artist: Madame, occuring 2 times
		differing columns: ['year', 'album_name', 'album_release_date', 'album_type', 'track_number', 'duration_ms', 'popularity', 'album_image', 'id_album']

	- 'sentimi' by artist: Madame, occuring 2 times
		differing columns: ['album_name', 'album_release_date', 'album_type', 'track_number', 'duration_ms', 'popularity', 'album_image', 'id_album']

so that id not only refers to 2 different songs, but each occurrence of the song (2) has different values. based on the values of different rows, it's possible to cut the additional wrong records

In [8]:
ids_to_fix = ['TR367132']
condition = df['id'].isin(ids_to_fix)

print("showing same tracks record:")
display(df[condition][['id', 'title', 'name_artist', 'year', 'album_name', 'album_release_date', 'album_type', 'track_number', 'duration_ms', 'popularity', 'album_image', 'id_album']])

showing same tracks record:

,id,title,name_artist,year,album_name,album_release_date,album_type,track_number,duration_ms,popularity,album_image,id_album
4627,TR367132,BUGIE,Madame,1927,MADAME,2021-06-03,album,6.0,171602.0,48.0,https://i.scdn.co/image/ab67616d0000b2733ccb55...,ALB468764
4628,TR367132,BUGIE,Madame,2021.0,sentimi,2020-04-24,single,1.0,187660.0,42.0,https://i.scdn.co/image/ab67616d0000b27343c750...,ALB590629
4647,TR367132,sentimi,Madame,2020.0,MADAME,2021-06-03,album,6.0,171602.0,48.0,https://i.scdn.co/image/ab67616d0000b2733ccb55...,ALB468764
4648,TR367132,sentimi,Madame,2020.0,sentimi,2020-04-24,single,1.0,187660.0,42.0,https://i.scdn.co/image/ab67616d0000b27343c750...,ALB590629

based on informations found online, sentimi is a single made in 2020, while bugie is a track released in the album madame in the year 2021

In [9]:
mask = (
    ((df["title"].str.lower() == "bugie") & (df["album_name"].str.lower() != "madame")) |
    ((df["title"].str.lower() == "sentimi") & (df["album_name"].str.lower() != "sentimi"))
)

df = df.loc[~mask].copy()

df.loc[
    (df["title"].str.lower() == "bugie") &
    (df["album_name"].str.lower() == "madame"),
    "year"
] = 2021

df.reset_index(drop=True, inplace=True)

ids_to_fix = ['TR367132']
condition = df['id'].isin(ids_to_fix)

print("showing same tracks record:")
display(df[condition][['id', 'title', 'name_artist', 'year', 'album_name', 'album_release_date', 'album_type', 'track_number', 'duration_ms', 'popularity', 'album_image', 'id_album']])

showing same tracks record:

,id,title,name_artist,year,album_name,album_release_date,album_type,track_number,duration_ms,popularity,album_image,id_album
4624,TR367132,BUGIE,Madame,2021,MADAME,2021-06-03,album,6.0,171602.0,48.0,https://i.scdn.co/image/ab67616d0000b2733ccb55...,ALB468764
4643,TR367132,sentimi,Madame,2020.0,sentimi,2020-04-24,single,1.0,187660.0,42.0,https://i.scdn.co/image/ab67616d0000b27343c750...,ALB590629

let's now fix the duplicate track ids in the dataset

In [10]:
existing_numbers = (
    df['id']
    .dropna()
    .str.extract(r'TR(\d+)')[0]
    .dropna()
    .astype(int)
)

max_existing_num = existing_numbers.max()

existing_ids = set(df['id'].dropna())

new_ids_assigned = {}

#iterate over duplicated IDs
for dup_id in not_unique_ids_list:
    
    dup_indices = df.index[df['id'] == dup_id].tolist()

    #keep the first occurrence unchanged, update the others
    for i, idx in enumerate(dup_indices):
        if i == 0:
            continue 
        #generate a new ID
        while True:
            max_existing_num += 1
            new_id = f"TR{max_existing_num}"
            if new_id not in existing_ids:
                break
                
        df.at[idx, 'id'] = new_id
        existing_ids.add(new_id)
        new_ids_assigned[idx] = new_id

print(f"assigned {len(new_ids_assigned)} new IDs to duplicates")

assigned 71 new IDs to duplicates

### id_artist

In [11]:
invalid_elems = df[df['id_artist'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['id_artist'])

nan_indexes = df.index[df['id_artist'].isna()].tolist()
print(f"number of missing values in id_artist: {len(nan_indexes)}")

id_to_names = df.groupby('id_artist')['name_artist'].nunique()
multiple_names = id_to_names[id_to_names > 1]

if len(multiple_names) == 0:
    print("each id_artist corresponds to exactly one name_artist")

Series([], Name: id_artist, dtype: object)
number of missing values in id_artist: 0
each id_artist corresponds to exactly one name_artist

there are no missing id_artist values in the dataset. all the id_artists are strings with the following format "ART{unique_num_id}". each id_artist corresponds to exactly one name_artist

### name_artist

In [12]:
invalid_elems = df[df['name_artist'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['name_artist'])

nan_indexes = df.index[df['name_artist'].isna()].tolist()
print(f"number of missing values in name_artist: {len(nan_indexes)}")

name_to_ids  = df.groupby('name_artist')['id_artist'].nunique()
multiple_ids  = name_to_ids [name_to_ids  > 1]

if len(multiple_names) == 0:
    print("each name_artist corresponds to exactly one id_artist")

Series([], Name: name_artist, dtype: object)
number of missing values in name_artist: 0
each name_artist corresponds to exactly one id_artist

there are no missing name_artist values in the dataset. all the name_artists are strings with the following format "ART{unique_num_id}". each name_artist corresponds to exactly one id_artist

### full_title

In [13]:
invalid_elems = df[df['full_title'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['full_title'])

nan_indexes = df.index[df['full_title'].isna()].tolist()
print(f"number of missing values in full_title: {len(nan_indexes)}")

Series([], Name: full_title, dtype: object)
number of missing values in full_title: 0

there are no missing full_title values in the dataset. 
all the full_titles are strings with the following format: "{title} by {primary_artist} (Ft. {name_artist_1}, {...}, {name_artist_n-1} & {name_artist_n})". let's check if name_artist is inside every full title

In [14]:
#normalizing non-breaking space and quotes
df['full_title'] = (df['full_title']
                    .str.replace('\xa0', ' ', regex=False)    #non-breaking space
                    .str.replace('\u2019', "'", regex=False)  #right single quote
                    .str.replace('\u2018', "'", regex=False)  #left single quote
                    .str.replace('\u201c', '"', regex=False)  #left double quote
                    .str.replace('\u201d', '"', regex=False)) #right double quote

#(.+?) -> capture everything; (?:\s*\(|$) -> stop at either " (" or end of string
extracted_artist = df['full_title'].str.extract(r' by (.+?)(?:\s*\(|$)', expand=False).str.strip()

mismatches = df[extracted_artist != df['name_artist']]
print(f"number of name_artist mismatches inside full_title: {len(mismatches)}")

if len(mismatches) > 0:
    print("sample mismatches:")
    mismatches_display = mismatches.copy()
    mismatches_display['extracted_artist'] = extracted_artist[mismatches.index]
    display(mismatches_display[['full_title', 'name_artist', 'extracted_artist']].head(20))

number of name_artist mismatches inside full_title: 843
sample mismatches:

,full_title,name_artist,extracted_artist
36,"Mattonelle* by Rosa Chemical, Mehdi (ITA), Fri...",Rosa Chemical,"Rosa Chemical, Mehdi"
129,a me mi piace by Alfa & Manu Chao,Alfa,Alfa & Manu Chao
223,EGLI È IL RE by thasup & Mara Sattei,thasup,thasup & Mara Sattei
225,POSTO MIO by thasup & Mara Sattei,thasup,thasup & Mara Sattei
227,r()t()nda by thasup & Tiziano Ferro,thasup,thasup & Tiziano Ferro
231,SO CHE CI SEI by thasup & Mara Sattei,thasup,thasup & Mara Sattei
235,BLESS SU BLESS by thasup & Mara Sattei,thasup,thasup & Mara Sattei
238,ONE KING by thasup & Mara Sattei,thasup,thasup & Mara Sattei
241,COME POLVERE by thasup & Mara Sattei,thasup,thasup & Mara Sattei
244,OCCHI MIEI by thasup & Mara Sattei,thasup,thasup & Mara Sattei
246,BACK TO BACK by thasup & Mara Sattei,thasup,thasup & Mara Sattei
436,"The Exchange by Lazza, Murda, Beny Jr, Guy2Bez...",Lazza,"Lazza, Murda, Beny Jr, Guy2Bezbar & Elias"
521,Lasciami solo by Nerone & Biggie Paul (Ft. Nitro),Nerone,Nerone & Biggie Paul
528,"Six pack by Nerone & Ensi (Ft. Fabri Fibra, Ge...",Nerone,Nerone & Ensi
532,R2R by Nerone & Ensi (Ft. Salmo),Nerone,Nerone & Ensi
542,King Kong vs. Godzilla by Nerone & Ensi,Nerone,Nerone & Ensi
550,Cemento by Nerone & Ensi (Ft. Silent Bob),Nerone,Nerone & Ensi
551,DM by Nerone & Warez (Ft. G. Nano),Nerone,Nerone & Warez
552,Domino by Nerone & Ensi (Ft. Speranza),Nerone,Nerone & Ensi
558,Non è cosa by Nerone & Ensi,Nerone,Nerone & Ensi

In [15]:
multi_artist_indicators = ['&', ',', ' and ']

has_separator = df['primary_artist'].str.contains('|'.join(multi_artist_indicators), case=False, na=False)
potential_multi = df[has_separator]

print(f"records with single artist: {len(df) - len(potential_multi)}")

records with single artist: 11158

The name_artist column contains only one artist per track, even when multiple artists collaborated (excluding featured artists), likely due to a data collection system limitation. while some tracks include non-rapper collaborators not in the dataset (e.g. Tiziano Ferro, Mara Sattei), which is expected, other tracks list only one rapper despite having multiple rapper collaborators who are present in the dataset (e.g. Ensi in Cemento). this causes artist-based analyses to undercount songs, as tracks where an artist collaborated but wasn't listed as the primary artist will be excluded from their catalog.

### title

In [16]:
invalid_elems = df[df['title'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['title'])

nan_indexes = df.index[df['title'].isna()].tolist()
print(f"number of missing values in title: {len(nan_indexes)}")

Series([], Name: title, dtype: object)
number of missing values in title: 0

In [17]:
df['title'] = (df['title']
                .str.replace('\xa0', ' ', regex=False)
                .str.replace('\u2019', "'", regex=False)
                .str.replace('\u2018', "'", regex=False)
                .str.replace('\u201c', '"', regex=False)
                .str.replace('\u201d', '"', regex=False))

# ^(.+?) -> capture from start; \s+by\s+ -> stop at " by " (with flexible whitespace)
extracted_title = df['full_title'].str.extract(r'^(.+?)\s+by\s+', expand=False).str.strip()

mismatches = df[df['title'] != extracted_title]
print(f"number of title mismatches inside full_title: {len(mismatches)}")

if len(mismatches) > 0:
    print("remaining mismatches (likely titles containing 'by'):\n")
    mismatches_display = mismatches.copy()
    mismatches_display['extracted_title'] = extracted_title[mismatches.index]
    display(mismatches_display[['full_title', 'title', 'extracted_title']].head(10))

number of title mismatches inside full_title: 4
remaining mismatches (likely titles containing 'by'):

,full_title,title,extracted_title
2512,Bolo by Night RMX by Inoki,Bolo by Night RMX,Bolo
2577,Bolo by Night RMX (NewKingzTape) by Inoki (Ft....,Bolo by Night RMX (NewKingzTape),Bolo
2599,Bolo by Night (NewKingz RMX) by Inoki (Ft. Lil...,Bolo by Night (NewKingz RMX),Bolo
2641,Barona by Night (Red Bull Culture Clash dubpla...,Barona by Night (Red Bull Culture Clash dubplate),Barona

title is contained inside full_title with no errors. the missmatches appearing are titles containing the word 'by', which is what's used from the regex to split the string.

### featured_artists

In [18]:
invalid_elems = df[df['featured_artists'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['featured_artists'])

nan_indexes = df.index[df['featured_artists'].isna()].tolist()
print(f"number of missing values in featured_artists: {len(nan_indexes)}")

5        NaN
6        NaN
8        NaN
9        NaN
10       NaN
        ...
11151    NaN
11153    NaN
11155    NaN
11156    NaN
11157    NaN
Name: featured_artists, Length: 7642, dtype: object
number of missing values in featured_artists: 7642

this is expected, since not every track must have a featured artist. let's check if the featured artists of the column are the same listed in the full_title

In [19]:
df['featured_artists'] = (df['featured_artists']
                    .str.replace('\xa0', ' ', regex=False)
                    .str.replace('\u2019', "'", regex=False)
                    .str.replace('\u2018', "'", regex=False)
                    .str.replace('\u201c', '"', regex=False)
                    .str.replace('\u201d', '"', regex=False))

# \((?:Ft\.)\s*(.+?)\)\s*$ -> everything from "(Ft.)" until the closing ")"
extracted_featured = df['full_title'].str.extract(r'\((?:Ft\.)\s*(.+?)\)\s*$', expand=False).str.strip()
extracted_featured_normalized = extracted_featured.str.replace(' & ', ', ', regex=False)

def sort_splitted_by_comma(string):
    if pd.isna(string):
        return string
    ret = [a.strip() for a in string.split(',')]
    return ', '.join(sorted(ret))

extracted_sorted = extracted_featured_normalized.apply(sort_splitted_by_comma)
featured_sorted = df['featured_artists'].apply(sort_splitted_by_comma)

mismatches = df[
    extracted_sorted.fillna('') != featured_sorted.fillna('')
]

print(f"Rows with featured artists in full_title: {extracted_featured.notna().sum()}")
print(f"Rows with featured artists in column: {df['featured_artists'].notna().sum()}")
print(f"number of featured_artists mismatches (ignoring order): {len(mismatches)}\n")

if len(mismatches) > 0:
    print("Sample mismatches (actual differences, not just ordering):")
    mismatches_display = mismatches.copy()
    mismatches_display['featured_sorted'] = featured_sorted[mismatches.index]
    mismatches_display['extracted_sorted'] = extracted_sorted[mismatches.index]
    display(mismatches_display[['full_title', 'featured_sorted', 'extracted_sorted']].head(10))

Rows with featured artists in full_title: 3516
Rows with featured artists in column: 3516
number of featured_artists mismatches (ignoring order): 9

Sample mismatches (actual differences, not just ordering):

,full_title,featured_sorted,extracted_sorted
1565,Comunque vada... by Piotta (Ft. Turi & Compari),Turi & Compari,"Compari, Turi"
2426,Musica Vera by Mistaman (Ft. Stokka & MadBuddy),Stokka & MadBuddy,"MadBuddy, Stokka"
2460,Il giorno in cui ci siamo svegliati by Mistama...,Stokka & MadBuddy,"MadBuddy, Stokka"
2644,Lo Facciamo Così by Inoki (Ft. Stokka & MadBuddy),Stokka & MadBuddy,"MadBuddy, Stokka"
2843,Dreams by Johnny Marsiglia & Big Joe (Ft. Stok...,Stokka & MadBuddy,"MadBuddy, Stokka"
3300,Pace by Ghemon (Ft. Franco Negrè & Stokka & Ma...,"Franco Negrè, Stokka & MadBuddy","Franco Negrè, MadBuddy, Stokka"
3614,'O Sarracino by Neffa (Ft. Giuliano Palma & Th...,Giuliano Palma & The Bluebeaters,"Giuliano Palma, The Bluebeaters"
5571,CHIAGNE by Geolier (Ft. Lazza & Takagi & Ketra),"Lazza, Takagi & Ketra","Ketra, Lazza, Takagi"
9089,DONDURÈ by Dark Polo Gang (Ft. Ski & Wok),Ski & Wok,"Ski, Wok"

featured_artists is contained inside full_title with no errors. the missmatches are given from features made with group names including the character '&', which is what's used from the regex to split the string.

### primary_artist

In [20]:
invalid_elems = df[df['primary_artist'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['primary_artist'])

nan_indexes = df.index[df['primary_artist'].isna()].tolist()
print(f"number of missing values in primary_artist: {len(nan_indexes)}")

Series([], Name: primary_artist, dtype: object)
number of missing values in primary_artist: 0

In [21]:
mismatches = df[df['primary_artist'] != df['name_artist']]
print(f"mismatches between name_artist and primary_artist: {len(mismatches)}")

if len(mismatches) > 0:
    display(mismatches[['id', 'full_title', 'name_artist', 'primary_artist']].head(5))

mismatches between name_artist and primary_artist: 0

there are no mismatches betweem this column and the name_artist column, so it doesn't add new informations. regarding the multiple primary_artists issue highlighted during the full_title analysis, it could be possible to both use this column to list all the primary artists (if more are present, and they are also present in the artist dataset), or cut this column and add more rows for the primary artists not present in name_artist but are present as artist and are present in the artist dataset.

### lyrics

In [22]:
invalid_elems = df[df['lyrics'].apply(check_type_validity, expected_type=str)]
print(invalid_elems[['full_title', 'lyrics']])

nan_indexes = df.index[df['lyrics'].isna()].tolist()
print(f"number of missing values in lyrics: {len(nan_indexes)}")

                           full_title lyrics
6944   Consegnato.02 by Frah Quintale    NaN
6946   Consegnato.01 by Frah Quintale    NaN
9768  Introliberassociazione by Salmo    NaN
number of missing values in lyrics: 3

between the 3 trakcs with no lyrics, only 'Consegnato.01' is the one who actually is missing some lyrics, the other ones are instrumental tracks. While those two instrumental tracks have lyrics set to NaN, there are other instrumenal/base tracks with the following form "{n} Contributor/s{title}". In those tracks some columns such as language, n_tokens, n_sentences, tokens_per_sent, char_per_tok, avg_token_per_clause, lexical_density and swear columns would be meaningless, so the lyrics will be set to NaN and those values will be set to NaN/0.

A few of those records contain a description of the track, those will be set to NaN. 13 other tracks instead contain the lyrics in the following form "{n} Contributor(s){title} Lyrics{lyrics}". Those lyrics will be kept, but most of them are missing new lines, so they are stored in single lines.

In [23]:
#list of tracks with lyrics inside
rescue_list = [
    "Intro (Napolimanicomio)",
    "Dammi Ancora",
    "Cin Cin",
    "Tu Non Hai Mai",
    "Pronte A Tutto",
    "Non Dimentico Più",
    "Come Ti Senti?",
    "0 tempo e 0 vento",
    "Vita Vera - Story",
    "Meteoriti (english)",
    "24h Non Stop",
    "Dimmi Che Farai",
    "Se ti girassi"
]

#regex to find the "Lyrics" part and capture everything after
lyrics_pattern = re.compile(r'^\d+\s+Contributor(s)?.*?Lyrics(.*)', re.DOTALL)

def clean_contributor_lyrics(row):
    if pd.isna(row['lyrics']):
        return np.nan
        
    if row['title'] in rescue_list:
        match = lyrics_pattern.search(row['lyrics'])
        if match:
            rescued_text = match.group(2).strip()
            
            if not rescued_text: #if text after regex is empty
                return np.nan
            else:
                return rescued_text
        else:
            print(f"regex failed for target track: {row['title']}")
            return row['lyrics']
    else:
        #not a target track
        return row['lyrics']
    
target_mask = df['title'].isin(rescue_list)

lyrics_before = df.loc[target_mask, 'lyrics'].copy()
df['lyrics'] = df.apply(clean_contributor_lyrics, axis=1)
lyrics_after = df.loc[target_mask, 'lyrics']

rescued_count = (lyrics_before != lyrics_after).sum()

print(f"successfully rescued lyrics for {rescued_count} out of {len(rescue_list)} tracks.")

regex failed for target track: Cin Cin
successfully rescued lyrics for 13 out of 13 tracks.

the regex failed comes from another track named Cin Cin made from a different artist with correctly formatted lyrics, but the 13 tracks with the lyrics were mantained.

Now the others bad lyrics tracks will be nullified, along with meaningless fields without the lyrics:

In [24]:
def nullify_bad_lyrics(lyrics): #sets lyrics for instrumentals, metadata, and descriptions to NaN.
    if pd.isna(lyrics):
        return np.nan
    
    #nullify remaining "contributor"
    if 'Contributor' in lyrics:
        return np.nan
    
    return lyrics

nans_before = df['lyrics'].isna().sum()
df['lyrics'] = df['lyrics'].apply(nullify_bad_lyrics)
nans_after = df['lyrics'].isna().sum()

newly_nullified_count = nans_after - nans_before
print(f"nullified {newly_nullified_count} additional rows.")

nullified 125 additional rows.

In [25]:
#columns that are meaningless without lyrics
count_cols = [
    'n_tokens', 'n_sentences', 'swear_IT', 'swear_EN'
]

ratio_cols = [
    'tokens_per_sent', 'char_per_tok', 
    'avg_token_per_clause', 'lexical_density'
]

string_cols = [
    'language', 'swear_IT_words', 'swear_EN_words'
]

missing_lyrics_mask = df['lyrics'].isna()

df.loc[missing_lyrics_mask, count_cols] = 0
df.loc[missing_lyrics_mask, ratio_cols] = 0

# Use pd.NA for string/object columns
for col in string_cols:
    df.loc[missing_lyrics_mask, col] = pd.NA

print(f"Cleaned {missing_lyrics_mask.sum()} rows with missing lyrics.")

Cleaned 128 rows with missing lyrics.

### language

In [26]:
invalid_elems = df[df['language'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['language'])

nan_indexes = df.index[df['language'].isna()].tolist()
print(f"number of missing values in language: {len(nan_indexes)}")

58       <NA>
61       <NA>
65       <NA>
68       <NA>
198       NaN
         ...
10326    <NA>
10641    <NA>
10645    <NA>
10676    <NA>
10683    <NA>
Name: language, Length: 203, dtype: object
number of missing values in language: 203

In [27]:
language_counts = df['language'].value_counts(dropna=False)

for i, (lang, count) in enumerate(language_counts.items(), 1):
    percentage = (count / len(df)) * 100
    lang_display = lang if pd.notna(lang) else "NaN"
    print(f"{i:3d}. {lang_display:13s} : {count:5d} tracks")

  1. it            :  9281 tracks
  2. en            :   814 tracks
  3. pl            :   584 tracks
  4. NaN           :   128 tracks
  5. NaN           :    75 tracks
  6. es            :    63 tracks
  7. co            :    48 tracks
  8. pt            :    45 tracks
  9. da            :    18 tracks
 10. cs            :    14 tracks
 11. fr            :    13 tracks
 12. nl            :     9 tracks
 13. war           :     9 tracks
 14. sr            :     9 tracks
 15. eu            :     8 tracks
 16. no            :     6 tracks
 17. ca            :     5 tracks
 18. ia            :     5 tracks
 19. gl            :     3 tracks
 20. rm            :     2 tracks
 21. la            :     2 tracks
 22. de            :     2 tracks
 23. sco           :     2 tracks
 24. eo            :     2 tracks
 25. et            :     1 tracks
 26. lt            :     1 tracks
 27. rw            :     1 tracks
 28. aa            :     1 tracks
 29. ro            :     1 tracks
 30. ru            :     1 tracks
 31. mt            :     1 tracks
 32. cy            :     1 tracks
 33. qu            :     1 tracks
 34. bg            :     1 tracks
 35. sw            :     1 tracks

here are all the languages in the dataset. a lot of entries here are incorrect, and the criteria by which the language was assigned is not known. the following is a list of language codes that, upon manual inspection, actually correspond to Italian tracks: pl (Polish), da (Danish), cs (Czech), nl (Dutch), sr (Serbian), war (?), eu (?), no (?), ia (Interlingua), ca (Catalan), gl (Galician), sco (?), la (Latin), eo (Esperanto), rm (Romansh), et (Estonian), lt (Lithuanian), aa (?), ro (Romanian), rw (Kinyarwanda), chr (?), qu (Quechua), mt (Maltese), cy (Welsh), sq (Albanian), sw (Swahili).

The first NaN are the Pandas' NA that were introduced in the previous step for tracks with no lyrics, while the 75 others are original missing values from the dataset, which will try to be filled with langdetect.

In [28]:
# NaN language detection with langdetect
def detect_language(lyrics):
    #handle NaN, empty, or non-string lyrics
    if pd.isna(lyrics) or not isinstance(lyrics, str) or not lyrics.strip():
        return pd.NA

    try:
        return detect(lyrics)
    except LangDetectException:
        #handle cases with no detectable features (e.g., "!!!", "123")
        return pd.NA
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return pd.NA

#language missing and lyrics not missing
mask_to_check = df['language'].isna() & df['lyrics'].notna()
    
rows_to_check = df[mask_to_check]
print(f"Found {len(rows_to_check)} rows with missing language but existing lyrics")

if not rows_to_check.empty:
    detected_languages = rows_to_check['lyrics'].apply(detect_language)
    df.loc[detected_languages.index, 'language'] = detected_languages

# fix incorrect italian codes
incorrect_italian_codes = ['pl', 'da', 'cs', 'nl', 'sr', 'war', 'eu', 'no', 'ia', 'ca', 'gl', 'sco', 'la', 'eo', 'rm', 'et', 'lt', 'aa', 'ro', 'rw', 'chr', 'qu', 'mt', 'cy', 'sq', 'sw', 'co']
updated_rows = df[df['language'].isin(incorrect_italian_codes)]
print(f"updated rows: {len(updated_rows)}")

df.loc[df['language'].isin(incorrect_italian_codes), 'language'] = 'it'

language_counts = df['language'].value_counts(dropna=False)
for i, (lang, count) in enumerate(language_counts.items(), 1):
    percentage = (count / len(df)) * 100
    lang_display = lang if pd.notna(lang) else "NaN (missing)"
    print(f"{i:3d}. {lang_display:13s} : {count:5d} tracks")

Found 75 rows with missing language but existing lyrics
updated rows: 736
  1. it            : 10084 tracks
  2. en            :   818 tracks
  3. NaN (missing) :   128 tracks
  4. es            :    64 tracks
  5. pt            :    47 tracks
  6. fr            :    13 tracks
  7. de            :     2 tracks
  8. ru            :     1 tracks
  9. bg            :     1 tracks

some (en (English), es (Spanish), pt (Portuguese), fr (French)) are mixed, co (Corsican) is basically italian (merged with 'it' as well), while the rest (de (German), ru (Russian), bg (Bulgarian)) are good. langdetect will be used for the mixed columns to obtain better results.

Ref. for languages code: https://www.cambridge.org/core/books/abs/interaction-of-borrowing-and-word-formation/list-of-iso639-language-codes/624C593339914D4A7DDA1AC55AC4889F

In [29]:
mixed_languages = ['en', 'es', 'pt', 'fr']
mask_to_check = df['language'].isin(mixed_languages) & df['lyrics'].notna()
rows_to_check = df[mask_to_check]

if not rows_to_check.empty:
    detected_languages = rows_to_check['lyrics'].apply(detect_language)

    #detected langugage distribution
    new_counts = detected_languages.value_counts(dropna=False)
    print(new_counts)

    target_langs = ['sl', 'ca', 'nl', 'so']
    target_indices = detected_languages[detected_languages.isin(target_langs)].index
    if not target_indices.empty:
        print(f"target languages to manually check ({target_langs}):")
        
        target_tracks = df.loc[target_indices].copy()
        
        target_tracks['detected_language'] = detected_languages[target_indices]
        target_tracks['lyrics_snippet'] = target_tracks['lyrics'].str[:100] + "..."
        
        display(target_tracks[[
            'title', 
            'language',          
            'detected_language',
            'lyrics_snippet'
        ]])
    else:
        print(f"no tracks found matching {target_langs}.")
    
    #update rows where detection was successful
    update_mask = detected_languages.notna()
    rows_to_update = detected_languages[update_mask]

    if not rows_to_update.empty:
        print(f"updating {len(rows_to_update)} rows in the 'language' column")
        
        df.loc[rows_to_update.index, 'language'] = rows_to_update.values

else:
    print("No rows found to check.")

lyrics
it    745
en    143
es     39
pt      6
fr      5
sl      1
ca      1
nl      1
so      1
Name: count, dtype: int64
target languages to manually check (['sl', 'ca', 'nl', 'so']):

,title,language,detected_language,lyrics_snippet
2801,KI-KI,en,sl,"Soy yo, la Ferrari (Dímelo)\nAcelera color Cam..."
3477,The Banana Splits,en,ca,"Tra-la-la, la-la-la-la\nTra-la-la, la-la-la-la..."
4370,Intro (Monkee Bizniz Vol. 2),en,nl,Monkee Bizniz Vol. 2\n Busdeez\nYou know my na...
8527,FOXY,en,so,"Sex (Oh, ah, ah, ah, oh, ah)\nDrugs (Oh, ah, a..."

updating 942 rows in the 'language' column

in KI-KI the main language is spanish, in The Banana Splits, Intro (Monkee Bizniz Vol. 2), and FOXY the language was correctly english, so they will be updated accordingly

In [30]:
manual_updates = {
    "KI-KI": "es",
    "The Banana Splits": "en",
    "Intro (Monkee Bizniz Vol. 2)": "en",
    "FOXY": "en"
}

updated_count = 0

for title, lang in manual_updates.items():
    mask = (df['title'] == title)
    
    # Check if any rows were found
    if mask.any():
        df.loc[mask, 'language'] = lang
        updated_count += mask.sum()
    else:
        print(f"track with title '{title}' not found in dataset.")
        
print(f"rows updated: {updated_count}")

print(f"\nFinal language distribution:")
language_counts = df['language'].value_counts(dropna=False)

for i, (lang, count) in enumerate(language_counts.items(), 1):
    percentage = (count / len(df)) * 100
    lang_display = lang if pd.notna(lang) else "NaN (missing)"
    print(f"{i:3d}. {lang_display:13s} : {count:5d} tracks")

rows updated: 4

Final language distribution:
  1. it            : 10829 tracks
  2. en            :   146 tracks
  3. NaN (missing) :   128 tracks
  4. es            :    40 tracks
  5. pt            :     6 tracks
  6. fr            :     5 tracks
  7. de            :     2 tracks
  8. ru            :     1 tracks
  9. bg            :     1 tracks

### album

In [31]:
invalid_elems = df[df['album'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['album'])

nan_indexes = df.index[df['album'].isna()].tolist()
print(f"number of missing values in album: {len(nan_indexes)}")

10       NaN
21       NaN
22       NaN
23       NaN
24       NaN
        ...
11148    NaN
11149    NaN
11151    NaN
11156    NaN
11157    NaN
Name: album, Length: 1513, dtype: object
number of missing values in album: 1513

this is expected, since not every track must be inside an album. some albums list more tracks than they actually contain. my best guess is that a few standalone songs were mistakenly assigned to one of the artist’s albums.

In [32]:
tracks_per_album = df['album'].value_counts()

print('top 20 albums with most tracks:')
for i, (album, count) in enumerate(tracks_per_album.head(20).items(), 1):
    print(f"{i:3d}. {album[:50]:50s} : {count:3d} tracks")

top 20 albums with most tracks:
  1. Rimo Da Quando                                     :  47 tracks
  2. TAXI DRIVER (Deluxe)                               :  37 tracks
  3. Solo Un Uomo (Gold Edition)                        :  36 tracks
  4. Il tempo vola 2002-2020                            :  36 tracks
  5. Di vizi di forma virtù                             :  35 tracks
  6. Cose Dell’Altro Mondo Mondo Marcio: Special Editio :  34 tracks
  7. SurreAle                                           :  30 tracks
  8. Status (Vendetta Edition)                          :  30 tracks
  9. DIO LO SA - ATTO II                                :  30 tracks
 10. Re Mida: Aurum                                     :  29 tracks
 11. The NewKingzTape Vol. 1                            :  29 tracks
 12. Miracolo! (Deluxe Edition)                         :  28 tracks
 13. ’A Verità 2.0                                      :  27 tracks
 14. Una cosetta così                                   :  26 tracks
 15. N Mixtape                                          :  26 tracks
 16. Ferite (Deluxe Edition)                            :  25 tracks
 17. SignorHunt: Wake Up Edition                        :  25 tracks
 18. Quello Che Vi Consiglio Vol. 2                     :  25 tracks
 19. Mea Culpa (Gold Edition)                           :  24 tracks
 20. IL CORAGGIO DEI BAMBINI - ATTO II                  :  24 tracks

some albums list more tracks than they actually contain. my best guess is that a few standalone songs were mistakenly assigned to one of the artist’s albums.

### album_name

In [33]:
invalid_elems = df[df['album_name'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['album_name'])

nan_indexes = df.index[df['album_name'].isna()].tolist()
print(f"number of missing values in album_name: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: album_name, Length: 78, dtype: object
number of missing values in album_name: 78

let's analyze the differences between this column and the one named 'album', as the 'album' column also seems to contain album names.

In [34]:
matches = (df['album'] == df['album_name']).sum()
print(f"rows where 'album' == 'album_name': {matches}")

filled_mismatch = (df['album'].isna() & df['album_name'].notna()).sum()
print(f"rows where 'album' is NaN but 'album_name' is filled: {filled_mismatch}")

conflict_mask = (
        df['album'].notna() & 
        df['album_name'].notna() & 
        (df['album'] != df['album_name'])
    )
    
conflicts = df[conflict_mask].copy()

print(f"text conflicts (where both exist but differ): {len(conflicts)}")

mismatches = df[
    (df['album'] != df['album_name']) &
    df['album'].notna() &
    df['album_name'].notna()
]
mismatches_sample = mismatches.head(20)

print("sample of mismatches:")
mismatches_display = mismatches_sample.copy()
display(mismatches_display[['album', 'album_name']].head(10))

def check_similarity(row):
    a = str(row['album']).lower().strip()
    b = str(row['album_name']).lower().strip()
    if a in b:
        return 'album_in_album_name'
    elif b in a:
        return 'album_name_in_album'
    else:
        return 'completely_different'

conflicts.loc[:, 'similarity'] = conflicts.apply(check_similarity, axis=1)
print("similarity patterns:")
print(conflicts['similarity'].value_counts())

completely_diff = conflicts[conflicts['similarity'] == 'completely_different'] \
                               [['album', 'album_name']].head(20)

print("examples of completely different album vs album_name:")
completely_diff_display = completely_diff.copy()
display(completely_diff_display.head(10))

missing_album = df[
    df['album'].isna() &
    df['album_name'].notna()
][['album', 'album_name']].head(20)

print("examples where album is NaN but album_name is filled:")
missing_album_display = missing_album.copy()
display(missing_album_display.head(10))

rows where 'album' == 'album_name': 4204
rows where 'album' is NaN but 'album_name' is filled: 1508
text conflicts (where both exist but differ): 5368
sample of mismatches:

                       album     album_name
3          OKAY OKAY !! - EP    OKAY OKAY 2
4           FOREVER AND EVER        FOREVER
5           FOREVER AND EVER        FOREVER
6           FOREVER AND EVER        FOREVER
7           FOREVER AND EVER        FOREVER
8   Festival di Sanremo 2023  MADE IN ITALY
9           FOREVER AND EVER        FOREVER
11          FOREVER AND EVER        FOREVER
12          FOREVER AND EVER        FOREVER
13          FOREVER AND EVER        FOREVER

similarity patterns:
similarity
completely_different    3385
album_name_in_album     1175
album_in_album_name      808
Name: count, dtype: int64
examples of completely different album vs album_name:

                               album                   album_name
3                  OKAY OKAY !! - EP                  OKAY OKAY 2
8           Festival di Sanremo 2023                MADE IN ITALY
57                 Paranoise Mixtape                   Dead Again
59                 Paranoise Mixtape               Reversed Crash
62                 Paranoise Mixtape                          BV3
63                 Paranoise Mixtape  The Execution Of All Things
64                 Paranoise Mixtape                          BV3
66   One Take FM Free Mic - Season 6                ShapeShifters
67                 Paranoise Mixtape          Spaccio di Verità 1
108                    Joker Mixtape                        Intro

examples where album is NaN but album_name is filled:

   album    album_name
10   NaN       POLKA 3
21   NaN    Facciamolo
22   NaN   OKAY OKAY 2
23   NaN           BV3
24   NaN           BV3
25   NaN        Fatass
32   NaN  #digitalcity
33   NaN           BV3
34   NaN        ALIENO
36   NaN           BV3

as it's hard to say which column contains the right data, further analysis of other columns related to albums is required.

### id_album

In [35]:
invalid_elems = df[df['id_album'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['id_album'])

nan_indexes = df.index[df['id_album'].isna()].tolist()
print(f"number of missing values in id_album: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: id_album, Length: 78, dtype: object
number of missing values in id_album: 78

In [36]:
album_per_id = df.groupby('id_album')['album'].nunique()
album_name_per_id = df.groupby('id_album')['album_name'].nunique()

total_ids = len(df['id_album'].unique())

consistent_album = (album_per_id == 1).sum()
consistent_album_name = (album_name_per_id == 1).sum()
album_multi = (album_per_id > 1).sum()
album_name_multi = (album_name_per_id > 1).sum()

print(f"total unique album IDs: {total_ids}")

print(f"\nalbum 1:1 id mapping:  {consistent_album:4d}")
print(f"album with multiple id mappings:   {album_multi:4d}")

print(f"\nalbum name 1:1 id mapping:  {consistent_album_name:4d}")
print(f"album name with multiple id mappings:   {album_name_multi:4d}")

if album_name_multi > 0:
    print("\nshowing album name with multiple ids:")
    problematic_ids = album_name_per_id[album_name_per_id > 1].index
    for i, aid in enumerate(problematic_ids, 1):
        values = df[df['id_album'] == aid]['album_name'].dropna().unique()
        print(f"  {i}. {aid}: {list(values)}")

conflict_mask = (df['album'].notna() & df['album_name'].notna() & 
                 (df['album'] != df['album_name']))
conflicts = df[conflict_mask]

total unique album IDs: 3061

album 1:1 id mapping:  1647
album with multiple id mappings:    374

album name 1:1 id mapping:  3055
album name with multiple id mappings:      5

showing album name with multiple ids:
  1. ALB156429: ['Ma Vaffanculo', "It's Snowing, Motherfucker"]
  2. ALB275546: ['La maggior parte', 'Poco di Buono']
  3. ALB473208: ['MALAVITA, Pt. 2 / HeadShot, Vol. 3', 'Il mio lato peggiore']
  4. ALB504235: ['Affetto Illimitato', 'Handmade Cities']
  5. ALB877400: ['Allora ciao', 'Red Bull 64 Bars, The Album']

it seems like the id_album refers to the album_name column, so album_name will be take as reference. let's check if there are same album names sharing different id_album

In [37]:
albums_per_name = df.groupby('album_name')['id_album'].nunique()

shared_names = albums_per_name[albums_per_name > 1]

total_album_names = len(df['album_name'].dropna().unique())
shared_count = len(shared_names)

print(f"unique album names: {total_album_names}")
print(f"album names used by one album id: {total_album_names - shared_count:4d}")
print(f"album names shared by multiple album ids: {shared_count:4d}")

top_shared = shared_names.nlargest(5)
for i, (album_name, count) in enumerate(top_shared.items(), 1):
    print(f"\n{i}. '{album_name}' - used by {count} different albums")
    
    #example for this shared album name
    shared_albums = df[df['album_name'] == album_name][
        ['id_album', 'album_name', 'full_title', 'album_release_date']
    ].drop_duplicates().head(10)
    
    print(f"\nExamples of albums with name '{album_name}':")
    shared_albums_display = shared_albums.copy()
    display(shared_albums_display)

unique album names: 2420
album names used by one album id: 2083
album names shared by multiple album ids:  337

1. 'SANTANA MONEY GANG' - used by 38 different albums

Examples of albums with name 'SANTANA MONEY GANG':

,id_album,album_name,full_title,album_release_date
128,ALB563208,SANTANA MONEY GANG,Chiara Ferragni by Alfa (Ft. Matsby & Olly),2025-04-10
261,ALB338267,SANTANA MONEY GANG,Veri Fra* by thasup,2025-04-10
284,ALB338267,SANTANA MONEY GANG,Fuck 3x dalla traphouse a youtube by thasup,2025-04-10
303,ALB338267,SANTANA MONEY GANG,via da te by thasup,2025-04-10
447,ALB720097,SANTANA MONEY GANG,In Tilt by Lazza,2025-04-10
671,ALB536928,SANTANA MONEY GANG,Il Mio Ambiente Fantastico by Nerone,2025-04-10
712,ALB183034,SANTANA MONEY GANG,Dovevi essere mia by Babaman,2025-04-10
1388,ALB765227,SANTANA MONEY GANG,Porca ma donna by Skioffi,2025-04-10
1457,ALB765227,SANTANA MONEY GANG,Sei bellissima così by Skioffi,2025-04-10
1468,ALB765227,SANTANA MONEY GANG,Non posso dire un c**** Freestyle by Skioffi,2025-04-10

2. 'LA BELLAVITA' - used by 20 different albums

Examples of albums with name 'LA BELLAVITA':

,id_album,album_name,full_title,album_release_date
42,ALB538879,LA BELLAVITA,A te e famiglia Freestyle by Rosa Chemical,2025-03-28
282,ALB990792,LA BELLAVITA,baby dopo che uno sconosciuto t'ha venduto una...,2025-03-28
792,ALB727128,LA BELLAVITA,Oro Addosso* by Niky Savage (Ft. Capo Plaza),2025-03-28
1246,ALB882800,LA BELLAVITA,La Ca$$a by Capo Plaza (Ft. Artie 5ive),2025-03-28
2504,ALB730179,LA BELLAVITA,Lo Faccio Marcio by Mistaman & DJ Shocca,2025-03-28
3267,ALB535938,LA BELLAVITA,Ti Muovi Nella Mia Vita by Ghemon,2025-03-28
3851,ALB584928,LA BELLAVITA,Sono Su (Si Alternano) by Tedua,2025-03-28
3862,ALB584928,LA BELLAVITA,Il sole bacia i ribelli by Tedua,2025-03-28
4568,ALB400096,LA BELLAVITA,Non Rifarlo A Casa by Ensi,2025-03-28
4991,ALB432941,LA BELLAVITA,Scomodissimo by Il Tre,2025-03-28

3. 'Il mio lato peggiore' - used by 17 different albums

Examples of albums with name 'Il mio lato peggiore':

,id_album,album_name,full_title,album_release_date
1559,ALB626867,Il mio lato peggiore,Su di me (Outtake) by Piotta,2025-05-16
2219,ALB682065,Il mio lato peggiore,Stavo Pensando A Te (Re-Edit) by Fabri Fibra (...,2025-05-16
3271,ALB309096,Il mio lato peggiore,Ho Incontrato L'Amore Ma... by Ghemon,2025-05-16
3281,ALB309096,Il mio lato peggiore,Tutto si risolverà by Ghemon (Ft. Frank Sicili...,2025-05-16
3333,ALB309096,Il mio lato peggiore,Lavoro Sporco by Ghemon,2025-05-16
3991,ALB692464,Il mio lato peggiore,La sindrome di Lorena by Caparezza,2025-05-16
4034,ALB692464,Il mio lato peggiore,Fuck the violenza (Demo) by Caparezza,2025-05-16
4090,ALB930332,Il mio lato peggiore,P by Tony Effe,2025-05-16
5162,ALB473208,Il mio lato peggiore,Nessuna by Luchè,2025-05-16
5163,ALB473208,Il mio lato peggiore,Ginevra by Luchè (Ft. Geolier),2025-05-16

4. 'TUTTA VITA' - used by 12 different albums

Examples of albums with name 'TUTTA VITA':

,id_album,album_name,full_title,album_release_date
1081,ALB767259,TUTTA VITA,Dammi I Tuoi Milioni by Guè (Ft. Karkadan),2024-10-25
1299,ALB799480,TUTTA VITA,Forse sbaglio* by Capo Plaza (Ft. Lil Keed),2024-10-25
1403,ALB498675,TUTTA VITA,Zitta e baciami by Skioffi,2024-10-25
2877,ALB489164,TUTTA VITA,Se mai by Johnny Marsiglia (Ft. Louis Dee & Ma...,2024-10-25
3319,ALB846367,TUTTA VITA,Fate finta che Scienz non ci sia più by Ghemon,2024-10-25
4040,ALB208852,TUTTA VITA,Niente Paura (Outro) by Caparezza,2024-10-25
4460,ALB613326,TUTTA VITA,Il Bello Di Noi by Ghali (Ft. Maite),2024-10-25
5720,ALB163242,TUTTA VITA,Come litigare a San Valentino by Shade (Ft. Bo...,2024-10-25
5732,ALB163242,TUTTA VITA,Come litigare con l'arbitro by Shade,2024-10-25
7192,ALB434329,TUTTA VITA,Dimmelo Pure by Gemitaiz,2024-10-25

5. 'Red Bull 64 Bars, The Album' - used by 9 different albums

Examples of albums with name 'Red Bull 64 Bars, The Album':

,id_album,album_name,full_title,album_release_date
73,ALB670345,"Red Bull 64 Bars, The Album",WIMBLEDON (64 Bars) by Beba,2021-05-27
366,ALB888447,"Red Bull 64 Bars, The Album",MEZZO SPORT (64 Bars) by Lazza,2021-05-27
456,ALB888447,"Red Bull 64 Bars, The Album",A Me by Lazza (Ft. SHINE),2021-05-27
843,ALB517699,"Red Bull 64 Bars, The Album",VENEZUELA (64 Bars) by Guè,2021-05-27
3195,ALB940952,"Red Bull 64 Bars, The Album",64 Bars by Ghemon,2021-05-27
4636,ALB880954,"Red Bull 64 Bars, The Album",64 Bars by Madame,2021-05-27
6501,ALB497238,"Red Bull 64 Bars, The Album",LEWANDOWSKI VIII (64 Bars) by Ernia,2021-05-27
6506,ALB497238,"Red Bull 64 Bars, The Album",Lewandowski VI by Ernia,2021-05-27
6513,ALB497238,"Red Bull 64 Bars, The Album",Lewandowski VII by Ernia,2021-05-27
6542,ALB497238,"Red Bull 64 Bars, The Album",LEWANDOWSKI X by Ernia,2021-05-27

there are many albums with the same name but different ids, and it's more likely that those were imputing errors rathen than actual real different albums with the same name. They will be excluded from further album analysis.

In [38]:
shared_album_names = albums_per_name[albums_per_name > 1].index.tolist()
df_albums_filtered = df[~df['album_name'].isin(shared_album_names)]

Let's fix multiple ids per album.

In [39]:
problematic_album_ids = album_name_per_id[album_name_per_id > 1].index.tolist()

existing_numbers = (
    df['id_album']
    .dropna()
    .str.extract(r'ALB(\d+)')[0]
    .dropna()
    .astype(int)
)
max_existing_num = existing_numbers.max()
existing_ids = set(df['id_album'].dropna())

new_album_ids_assigned = {}

for dup_album_id in problematic_album_ids:
    dup_indices = df.index[df['id_album'] == dup_album_id].tolist()
    
    album_groups = df.loc[dup_indices].groupby('album_name').groups
    
    #keep the first group unchanged, assign new IDs to others
    first_group = True
    for album_name, indices in album_groups.items():
        if first_group:
            first_group = False
            continue
        
        while True:
            max_existing_num += 1
            new_album_id = f"ALB{max_existing_num:06d}"
            if new_album_id not in existing_ids:
                break
        
        for idx in indices:
            df.at[idx, 'id_album'] = new_album_id
            new_album_ids_assigned[idx] = new_album_id
        
        existing_ids.add(new_album_id)
        #print(f"assigned {new_album_id} to: '{album_name}' ({len(indices)} rows)")

print(f"assigned {len(new_album_ids_assigned)} new IDs to duplicates")

#album_name_per_id = df.groupby('id_album')['album_name'].nunique()

#consistent_album_name = (album_name_per_id == 1).sum()
#print(f"\nalbum name 1:1 id mapping:  {consistent_album_name:4d}")

#album_name_multi = (album_name_per_id > 1).sum()
#if album_name_multi > 0:
#    print("\nshowing album name with multiple ids:")
#    problematic_ids = album_name_per_id[album_name_per_id > 1].index
#    for i, aid in enumerate(problematic_ids, 1):
#        values = df[df['id_album'] == aid]['album_name'].dropna().unique()
#        print(f"  {i}. {aid}: {list(values)}")

assigned 5 new IDs to duplicates

### album_image

In [40]:
invalid_elems = df[df['album_image'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['album_image'])

nan_indexes = df.index[df['album_image'].isna()].tolist()
print(f"number of missing values in album_image: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: album_image, Length: 78, dtype: object
number of missing values in album_image: 78

In [41]:
images_per_id = df_albums_filtered.groupby('id_album')['album_image'].nunique()

multi_images = (images_per_id > 1).sum()
single_image = (images_per_id == 1).sum()

print(f"IDs with one image: {single_image:4d}")
print(f"IDs with multiple images: {multi_images:4d}")

if multi_images > 0:
    problematic_ids = images_per_id[images_per_id > 1].head(4).index
    
    for i, aid in enumerate(problematic_ids, 1):
        same_id = df_albums_filtered[df_albums_filtered['id_album'] == aid]
        unique_images = same_id['album_image'].dropna().unique()
        unique_names = same_id['album_name'].dropna().unique()
        
        print(f"\n{i}. {aid}")
        print(f"   Album name(s): {list(unique_names)}")
        print(f"   Number of different images: {len(unique_images)}")
        print(f"   Total rows with this ID: {len(same_id)}")
        
        #show first few image URLs
        for j, img in enumerate(unique_images[:3], 1):
            img_str = str(img)[:80] + "..." if len(str(img)) > 80 else str(img)
            print(f"     Image {j}: {img_str}")

IDs with one image: 2051
IDs with multiple images:   30

1. ALB140195
   Album name(s): ['NEI LETTI DEGLI ALTRI']
   Number of different images: 2
   Total rows with this ID: 14
     Image 1: https://i.scdn.co/image/ab67616d0000b2731166747444788eda482fbb30
     Image 2: https://i.scdn.co/image/ab67616d0000b2733d69e630bc865dfe13f60d51

2. ALB155169
   Album name(s): ['ICON']
   Number of different images: 2
   Total rows with this ID: 17
     Image 1: https://i.scdn.co/image/ab67616d0000b2736fa5dff2130a632bdf7076a7
     Image 2: https://i.scdn.co/image/ab67616d0000b273a4a49243dde25521f2fb5dea

3. ALB156429
   Album name(s): ['Ma Vaffanculo', "It's Snowing, Motherfucker"]
   Number of different images: 2
   Total rows with this ID: 2
     Image 1: https://i.scdn.co/image/ab67616d0000b273c9d295fd177dc053142a149c
     Image 2: https://i.scdn.co/image/ab67616d0000b2737c0ef785c86a869d7d7b71e3

4. ALB184496
   Album name(s): ['Lunga Vita a Sto']
   Number of different images: 2
   Total rows with this ID: 16
     Image 1: https://i.scdn.co/image/ab67616d0000b2735f2e03ef25683b06a2fdd920
     Image 2: https://i.scdn.co/image/ab67616d0000b27327d271a6f92b1b7f1ff8d521

even if there are IDs with multiple images, it looks like different url related to the same ID contain the same or a similar version of the same image.

### album_type

In [42]:
invalid_elems = df[df['album_type'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['album_type'])

nan_indexes = df.index[df['album_type'].isna()].tolist()
print(f"number of missing values in album_type: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: album_type, Length: 78, dtype: object
number of missing values in album_type: 78

In [43]:
print(df['album_type'].value_counts(dropna=False))

album_type
album          9346
single         1543
compilation     191
NaN              78
Name: count, dtype: int64

### album_release_date

In [44]:
invalid_elems = df[df['album_release_date'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['album_release_date'])

nan_indexes = df.index[df['album_release_date'].isna()].tolist()
print(f"number of missing values in album_type: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: album_release_date, Length: 78, dtype: object
number of missing values in album_type: 78

In [45]:
df['album_release_date'] = pd.to_datetime(df['album_release_date'], errors='coerce')

dates_per_id = df_albums_filtered.groupby('id_album')['album_release_date'].nunique()

multi_dates = (dates_per_id > 1).sum()
single_date = (dates_per_id == 1).sum()

total_ids = len(df_albums_filtered['id_album'].unique())
print(f"total unique album IDs: {total_ids}")

print(f"\nalbums with one release date:  {single_date:4d}")
print(f"album with multiple release dates:   {multi_dates:4d}")

missing_dates = df['album_release_date'].isna().sum()

if multi_dates > 0:
    problematic_ids = dates_per_id[dates_per_id > 1].head(10).index
    
    for i, aid in enumerate(problematic_ids, 1):
        same_id = df_albums_filtered[df_albums_filtered['id_album'] == aid]
        unique_dates = same_id['album_release_date'].dropna().unique()
        unique_names = same_id['album_name'].dropna().unique()
        
        print(f"\n{i}. {aid}")
        print(f"   Album name(s): {list(unique_names)}")
        print(f"   Number of different dates: {len(unique_dates)}")
        print(f"   Total rows with this album ID: {len(same_id)}")
        print(f"   Dates: {sorted([str(d) for d in unique_dates])}")

total unique album IDs: 2082

albums with one release date:  2063
album with multiple release dates:     18

1. ALB156429
   Album name(s): ['Ma Vaffanculo', "It's Snowing, Motherfucker"]
   Number of different dates: 2
   Total rows with this album ID: 2
   Dates: ['2019-12-09', '2020-07-17']

2. ALB213075
   Album name(s): ['Na.99.10']
   Number of different dates: 2
   Total rows with this album ID: 5
   Dates: ['2001-01-01', '2012-06-12']

3. ALB269248
   Album name(s): ['Rockstar (Popstar Edition)']
   Number of different dates: 2
   Total rows with this album ID: 7
   Dates: ['2018-11-30', '2018-12-07']

4. ALB334619
   Album name(s): ['Ciao America']
   Number of different dates: 2
   Total rows with this album ID: 11
   Dates: ['2024-02-01', '2024-02-02']

5. ALB342666
   Album name(s): ['Famoso']
   Number of different dates: 2
   Total rows with this album ID: 17
   Dates: ['2021-02-12', '2021-10-14']

6. ALB399662
   Album name(s): ['ALI']
   Number of different dates: 2
   Total rows with this album ID: 19
   Dates: ['2021-02-19', '2021-04-29']

7. ALB413159
   Album name(s): ['Unico']
   Number of different dates: 2
   Total rows with this album ID: 15
   Dates: ['2021-07-02', '2021-07-16']

8. ALB415773
   Album name(s): ['Potere (Il Giorno Dopo)']
   Number of different dates: 2
   Total rows with this album ID: 5
   Dates: ['2019-06-18', '2019-06-28']

9. ALB427259
   Album name(s): ['Sulla riva del fiume']
   Number of different dates: 2
   Total rows with this album ID: 13
   Dates: ['2025-02-13', '2025-02-27']

10. ALB481426
   Album name(s): ['PLAZA']
   Number of different dates: 2
   Total rows with this album ID: 15
   Dates: ['2021-01-22', '2021-04-16']

as the earliest date of pubblication seems to be the correct one, it'll be used as the official one.

In [46]:
problematic_album_ids = dates_per_id[dates_per_id > 1].index.tolist()

earliest_dates = {}

for aid in problematic_album_ids:
    album_dates = df[df['id_album'] == aid]['album_release_date'].dropna()
    
    if len(album_dates) > 0:
        #convert to datetime if not already, then find minimum
        album_dates_converted = pd.to_datetime(album_dates, errors='coerce')
        earliest_date = album_dates_converted.min()
        earliest_dates[aid] = earliest_date
        
        album_name = df[df['id_album'] == aid]['album_name'].iloc[0]
        all_dates = sorted(album_dates.unique())
        
        #print(f"{aid} - '{album_name}'")
        #print(f"  Original dates: {all_dates}")
        #print(f"  Assigned date: {earliest_date.strftime('%Y-%m-%d')}")

fixes_applied = 0

for aid, earliest_date in earliest_dates.items():
    #update all rows with this id_album to have the earliest date
    mask = df['id_album'] == aid
    df.loc[mask, 'album_release_date'] = earliest_date
    fixes_applied += (mask).sum()

#recreating the df filtered after the update
df_albums_filtered = df[~df['album_name'].isin(shared_album_names)]

dates_per_id_after = df_albums_filtered.groupby('id_album')['album_release_date'].nunique()
remaining_issues = (dates_per_id_after > 1).sum()

print(f"albums with multiple dates before: {len(problematic_album_ids)}")
print(f"albums with multiple dates after:  {remaining_issues}")

albums with multiple dates before: 18
albums with multiple dates after:  0

### stats_pageviews

In [47]:
invalid_elems = df[df['stats_pageviews'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['stats_pageviews'])

nan_indexes = df.index[df['stats_pageviews'].isna()].tolist()
print(f"number of missing values in stats_pageviews: {len(nan_indexes)}")

0        196033.0
1        164450.0
2         58313.0
3         39890.0
4         35432.0
           ...
11153         NaN
11154         NaN
11155         NaN
11156         NaN
11157         NaN
Name: stats_pageviews, Length: 11158, dtype: float64
number of missing values in stats_pageviews: 6521

In [48]:
df['stats_pageviews'] = df['stats_pageviews'].astype('Int64')

invalid_elems = df[df['stats_pageviews'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['stats_pageviews'])

nan_indexes = df.index[df['stats_pageviews'].isna()].tolist()
print(f"number of missing values in stats_pageviews: {len(nan_indexes)}")

0        196033
1        164450
2         58313
3         39890
4         35432
          ...
11153      <NA>
11154      <NA>
11155      <NA>
11156      <NA>
11157      <NA>
Name: stats_pageviews, Length: 11158, dtype: Int64
number of missing values in stats_pageviews: 6521

converted stats_pageviews to Int64 (nullable integer, NaN shown as <NA>), since the values in the column are without a decimal point.

In [49]:
invalid_pageviews = df[(df['stats_pageviews'] < 0)]
if len(invalid_pageviews) > 0:
    print(f"{len(invalid_pageviews)} rows with invalid pageviews (negative values):")
    display(invalid_pageviews[['id', 'title', 'name_artist', 'stats_pageviews']].head(10))

chart_data = df[['stats_pageviews']].dropna().copy()
chart_data['stats_pageviews'] = pd.to_numeric(chart_data['stats_pageviews']) #float is safer for Altair

base = alt.Chart(chart_data).encode(
    x=alt.X('stats_pageviews', bin=alt.Bin(maxbins=30), title='Pageviews Range'),
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Pageviews Range',
    width=1000,
    height=400
)

bars = base.mark_bar(color='steelblue', opacity=0.7)
# text labels on top of the bars
text = base.mark_text(
    dy=-5,
    color='black'
).encode(
    text=alt.Text('count()')
)

chart = (bars + text).interactive()

display(chart)

alt.LayerChart(...)

there seems to be outliers in the distribution, let's analyze the top pageviews tracks

In [50]:
top_10_tracks = df.sort_values(by='stats_pageviews', ascending=False).head(10)

print("top 10 tracks by pageviews:")
display(top_10_tracks[['title', 'name_artist', 'stats_pageviews']])

top 10 tracks by pageviews:

                       title    name_artist  stats_pageviews
8182                Veleno 6         MadMan          1971207
7022                Veleno 7       Gemitaiz           762450
3045                  Cupido  Sfera Ebbasta           692900
3046               Tran Tran  Sfera Ebbasta           499980
1197     Giovane fuoriclasse     Capo Plaza           484090
8183  Bolla papale Freestyle         MadMan           477926
3047                Sciroppo  Sfera Ebbasta           456566
3738  La legge del più forte          Tedua           448993
198        blun7 a swishland         thasup           448797
4371             Ninna Nanna          Ghali           423119

all the top stats_pageviews tracks are popular ones, so those high values seems to be realistic. these values probably indicate the number of track page views on the original website where the dataset was obtained.

### swear_IT_words

In [51]:
invalid_elems = df[df['swear_IT_words'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['swear_IT_words'])

nan_indexes = df.index[df['swear_IT_words'].isna()].tolist()
print(f"number of missing values in swear_IT_words: {len(nan_indexes)}")

58       <NA>
61       <NA>
65       <NA>
68       <NA>
264      <NA>
         ...
10326    <NA>
10641    <NA>
10645    <NA>
10676    <NA>
10683    <NA>
Name: swear_IT_words, Length: 128, dtype: object
number of missing values in swear_IT_words: 128

In [52]:
import ast

all_it_swear_words = set()

for value in df['swear_IT_words']:
    if pd.notna(value) and value != '[]':  #skip NaN and empty lists
        try:
            word_list = ast.literal_eval(value)
            all_it_swear_words.update(word_list)
        except:
            pass
        
sorted_words = sorted(all_it_swear_words)
print(sorted_words)
print("\n")
it_words_to_include = ['incazzati', 'fessi', 'fregne', 'cretino', 'maiale', 'mignotte', 'tette', 'seghe', 'porche', 'checche', 'cessa', 'cretini', 'cretina', 'fiche', 'chiappe', 'fottuto', 'farabutti', 'froci', 'stupide', 'minchione', 'scopate', 'sorche', 'minchiate', 'merde', 'scopate', 'bastarda']
sorted_include_words = sorted(it_words_to_include)
print(sorted_include_words)

['arrapante', 'arrapare', 'arrapato', 'bagascia', 'bastardi', 'bastardo', 'battona', 'bernarda', 'bischero', 'blowjob', 'bocchinaro', 'bocchino', 'bombare', 'cacare', 'cacata', 'cacca', 'cagare', 'cagata', 'cagna', 'cappella', 'cazzata', 'cazzeggiare', 'cazzeggio', 'cazzi', 'cazzo', 'cazzone', 'cazzuto', 'cesso', 'checca', 'chiappa', 'chiavare', 'chiavata', 'cogliona', 'coglionata', 'coglione', 'coglioni', 'controcazzi', 'controcoglioni', 'cornuto', 'cozza', 'cretina', 'cretini', 'cretino', 'culattone', 'culo', 'cunnu', 'deretano', 'escremento', 'farabutti', 'farabutto', 'fava', 'feci', 'fellatio', 'fesso', 'fica', 'fico', 'figa', 'figo', 'finocchio', 'fogna', 'fogne', 'fortuna', 'fottere', 'fottersi', 'fottio', 'fottuti', 'fottuto', 'fregare', 'fregarsene', 'fregna', 'frocio', 'gay', 'gigolo', 'glutei', 'gnocca', 'granchio', 'grilletto', 'handicappato', 'idiozia', 'incazzare', 'incazzarsi', 'incazzato', 'inculare', 'jug', 'leccaculo', 'madonna', 'maiala', 'maroni', 'mazzo', 'merda', 'merdaio', 'merdaiolo', 'merdata', 'merdina', 'mezzasega', 'mignotta', 'minchiata', 'minchioni', 'missionario', 'nerchia', 'palle', 'paraculo', 'pecorina', 'peluria', 'pene', 'piccione', 'pipa', 'pippa', 'pisciare', 'pisciata', 'piscio', 'pisello', 'pompinara', 'pompino', 'porca', 'pugnetta', 'puttana', 'puttanaio', 'puttanata', 'puttaniere', 'puttano', 'raspa', 'ricchione', 'rompicoglioni', 'rompipalle', 'rottinculo', 'sboccare', 'sborra', 'sborrare', 'scassare', 'scazzato', 'scazzo', 'schizzare', 'scopare', 'scopata', 'scoreggia', 'scrofa', 'seccatore', 'sedere', 'sega', 'segaiolo', 'selvaggio', 'sfiga', 'sfigata', 'sgualdrina', 'smerdare', 'sorca', 'spagnola', 'spompinare', 'sputtanare', 'strafottenza', 'stronzata', 'stronzo', 'stupida', 'stupido', 'sveltina', 'tetta', 'topa', 'toro', 'travestito', 'troia', 'troiaggine', 'troiaio', 'trombare', 'uccello', 'vacca', 'vaccata', 'vaffanculo', 'vagina', 'water', 'zanzara', 'zizza', 'zoccola']


['bastarda', 'cessa', 'checche', 'chiappe', 'cretina', 'cretini', 'cretino', 'farabutti', 'fessi', 'fiche', 'fottuto', 'fregne', 'froci', 'incazzati', 'maiale', 'merde', 'mignotte', 'minchiate', 'minchione', 'porche', 'scopate', 'scopate', 'seghe', 'sorche', 'stupide', 'tette']

there seems to be some english words among the italian swear words: "water, blowjob, jug"; "gay" is also english, but it doesn't appean in the swear_EN_words, so it was probably counted as an italian word. also there are words that are not swear words ("toro, fortuna, zanzara, granchio"), and other that are 'neutral' words ("pene, vagina, glutei, sedere, escremento, feci, peluria, selvaggio") but can sound vulgar in certain tracks. note that not all the swear words are taken into consideration, since some of them inside the lyrics can be a bit 'creative' (e.g. "apputtanamento")

In [53]:
it_words_to_exclude = ['water', 'blowjob', 'jug', 'toro', 'fortuna', 'zanzara', 'granchio']
filtered_it_swear_words = {word for word in all_it_swear_words if word not in it_words_to_exclude}

def find_swear_words_in_lyrics(lyrics, swear_words_list):
    if pd.isna(lyrics):
        return []

    lyrics_lower = lyrics.lower() #case-insensitive matching
    
    found_words = []
    for word in swear_words_list:
        pattern = r'\b' + re.escape(word) + r'\b'
        if re.search(pattern, lyrics_lower):
            found_words.append(word)
    
    return found_words
            
rows_changed = 0
rows_increased = 0
rows_decreased = 0
rows_both_changed = 0
rows_unchanged = 0
rows_processed = 0

for idx in df.index:
    lyrics = df.loc[idx, 'lyrics']
    
    found_words = find_swear_words_in_lyrics(lyrics, filtered_it_swear_words)
    new_words = set(found_words)
    
    old_value = df.loc[idx, 'swear_IT_words']
    
    #parse old swear words
    try:
        if pd.isna(old_value) or old_value == '[]':
            old_words = set()
        else:
            old_words = set(ast.literal_eval(old_value))
    except:
        old_words = set()
    
    new_value = str(found_words)
    df.loc[idx, 'swear_IT_words'] = new_value
    
    #track changes
    if old_words != new_words:
        rows_changed += 1
        
        words_added = new_words - old_words
        words_removed = old_words - new_words
        
        if words_added and words_removed:
            rows_both_changed += 1
        elif words_added:
            rows_increased += 1
        elif words_removed:
            rows_decreased += 1
    else:
        rows_unchanged += 1
    
    rows_processed += 1

print(f"unchanged rows: {rows_processed - rows_changed}")
print(f"rows where swear_IT_words was changed: {rows_changed}")

print(f"\t- words added only: {rows_increased}")
print(f"\t- words removed only: {rows_decreased}")
print(f"\t- both added and removed: {rows_both_changed}")

unchanged rows: 10651
rows where swear_IT_words was changed: 507
	- words added only: 0
	- words removed only: 507
	- both added and removed: 0

there are many more swear words, but an easy additional list can be obtained by considering the plural and gendered forms of many of those already in the set of swear words:

In [54]:
it_words_to_include = ['bastarda', 'battone', 'bocchini', 'cagate', 'cagne', 'cazzate', 'cazzoni', 'cessa', 'checche', 
                       'chiappe', 'fessi', 'fiche', 'fighe', 'finocchi', 'fregne', 'froci', 'incazzati', 'merde', 
                       'mignotte', 'minchiate', 'pompini', 'porche', 'puttane', 'ricchioni', 'scopate', 'seghe', 'sorche',
                       'stronzate', 'stronzi', 'stronza', 'stronze', 'stupide', 'stupidi', 'tette', 'troie', 'zoccole']
print(f"original filtered set size: {len(filtered_it_swear_words)}")
filtered_it_swear_words.update(it_words_to_include)
print(f"new filtered set size (after additions): {len(filtered_it_swear_words)}")

rows_changed = 0
rows_increased = 0
rows_decreased = 0
rows_both_changed = 0
rows_unchanged = 0
rows_processed = 0

for idx in df.index:
    lyrics = df.loc[idx, 'lyrics']
    
    found_words = find_swear_words_in_lyrics(lyrics, filtered_it_swear_words)
    new_words = set(found_words)
    
    old_value = df.loc[idx, 'swear_IT_words']
    
    #parse old swear words
    try:
        if pd.isna(old_value) or old_value == '[]':
            old_words = set()
        else:
            old_words = set(ast.literal_eval(old_value))
    except:
        old_words = set()
    
    new_value = str(found_words)
    df.loc[idx, 'swear_IT_words'] = new_value
    
    #track changes
    if old_words != new_words:
        rows_changed += 1
        
        words_added = new_words - old_words
        words_removed = old_words - new_words
        
        if words_added and words_removed:
            rows_both_changed += 1
        elif words_added:
            rows_increased += 1
        elif words_removed:
            rows_decreased += 1
    else:
        rows_unchanged += 1
    
    rows_processed += 1

print(f"unchanged rows: {rows_processed - rows_changed}")
print(f"rows where swear_IT_words was changed: {rows_changed}")

print(f"\t- words added only: {rows_increased}")
print(f"\t- words removed only: {rows_decreased}")
print(f"\t- both added and removed: {rows_both_changed}")

original filtered set size: 166
new filtered set size (after additions): 202
unchanged rows: 8680
rows where swear_IT_words was changed: 2478
	- words added only: 2478
	- words removed only: 0
	- both added and removed: 0

### swear_EN_words

In [55]:
invalid_elems = df[df['swear_EN_words'].apply(check_type_validity, expected_type=str)]
print(invalid_elems['swear_EN_words'])

nan_indexes = df.index[df['swear_EN_words'].isna()].tolist()
print(f"number of missing values in swear_EN_words: {len(nan_indexes)}")

58       <NA>
61       <NA>
65       <NA>
68       <NA>
264      <NA>
         ...
10326    <NA>
10641    <NA>
10645    <NA>
10676    <NA>
10683    <NA>
Name: swear_EN_words, Length: 128, dtype: object
number of missing values in swear_EN_words: 128

In [56]:
import ast

all_en_swear_words = set()

for value in df['swear_EN_words']:
    if pd.notna(value) and value != '[]':  #skip NaN and empty lists
        try:
            word_list = ast.literal_eval(value)
            all_en_swear_words.update(word_list)
        except:
            pass
        
print(all_en_swear_words)

{'sex', 'bastardo', 'bitches', 'pussy', 'nympho', 'busty', 'lolita', 'fellatio', 'porn', 'ecchi', 'nipple', 'nude', 'faggot', 'fuckin', 'dildo', 'rape', 'sexo', 'bondage', 'cunt', 'motherfucker', 'shitty', 'pissing', 'asshole', 'blowjob', 'xx', 'coon', 'snatch', 'sexy', 'fag', 'vagina', 'rimming', 'hardcore', 'cocks', 'fisting', 'shit', 'fuck', 'butt', 'punany', 'anus', 'suck', 'tit', 'bullshit', 'sexual', 'titty', 'spic', 'voyeur', 'nigga', 'horny', 'tranny', 'threesome', 'poof', 'tits', 'bastard', 'skeet', 'masturbation', 'hooker', 'fucking', 'dick', 'porno', 'xxx', 'cock', 'raping', 'doggystyle', 'escort', 'playboy', 'vulva', 'deepthroat', 'bitch', 'negro', 'cumming', 'bbw', 'panties', 'bukkake', 'kinky', 'cialis', 'scat', 'hentai', 'anal', 'rapist', 'topless', 'boobs', 'neonazi', 'cum', 'pedobear', 'semen', 'slut', 'cumshot', 'gangbang', 'ass', 'domination', 'clit', 'creampie', 'shibari', 'sucks', 'viagra', 'milf'}

there's an italian word "bastardo" among the english swear words. as in the italian set of swear words, there are words that aren't necessary swear words, but in certain tracks can be perceived as vulgar.

In [57]:
en_words_to_exclude = ['bastardo']
filtered_en_swear_words = {word for word in all_en_swear_words if word not in en_words_to_exclude}

In [58]:
rows_changed = 0
rows_increased = 0
rows_decreased = 0
rows_both_changed = 0
rows_unchanged = 0
rows_processed = 0

for idx in df.index:
    lyrics = df.loc[idx, 'lyrics']
    
    found_words = find_swear_words_in_lyrics(lyrics, filtered_en_swear_words)
    new_words = set(found_words)
    
    old_value = df.loc[idx, 'swear_EN_words']
    
    #parse old swear words
    try:
        if pd.isna(old_value) or old_value == '[]':
            old_words = set()
        else:
            old_words = set(ast.literal_eval(old_value))
    except:
        old_words = set()
    
    new_value = str(found_words)
    df.loc[idx, 'swear_EN_words'] = new_value
    
    #track changes
    if old_words != new_words:
        rows_changed += 1
        
        words_added = new_words - old_words
        words_removed = old_words - new_words
        
        if words_added and words_removed:
            rows_both_changed += 1
        elif words_added:
            rows_increased += 1
        elif words_removed:
            rows_decreased += 1
    else:
        rows_unchanged += 1
    
    rows_processed += 1

print(f"unchanged rows: {rows_processed - rows_changed}")
print(f"rows where swear_EN_words was changed: {rows_changed}")

print(f"\t- words added only: {rows_increased}")
print(f"\t- words removed only: {rows_decreased}")
print(f"\t- both added and removed: {rows_both_changed}")

unchanged rows: 10946
rows where swear_EN_words was changed: 212
	- words added only: 0
	- words removed only: 212
	- both added and removed: 0

### swear_IT

In [59]:
invalid_elems = df[df['swear_IT'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['swear_IT'])

nan_indexes = df.index[df['swear_IT'].isna()].tolist()
print(f"number of missing values in swear_IT: {len(nan_indexes)}")

Series([], Name: swear_IT, dtype: int64)
number of missing values in swear_IT: 0

In [60]:
def count_swear_words_in_lyrics(lyrics, swear_words_list):
    if pd.isna(lyrics):
        return 0
    
    lyrics_lower = lyrics.lower()
    total_count = 0
    
    for word in swear_words_list:
        pattern = r'\b' + re.escape(word) + r'\b'
        matches = re.findall(pattern, lyrics_lower)
        total_count += len(matches)
    
    return total_count

rows_processed = 0
rows_changed = 0

for idx in df.index:
    lyrics = df.loc[idx, 'lyrics']
    old_count = df.loc[idx, 'swear_IT']
    
    swear_words_value = df.loc[idx, 'swear_IT_words']
    
    try:
        if pd.isna(swear_words_value) or swear_words_value == '[]':
            words_to_count = []
        else:
            words_to_count = ast.literal_eval(swear_words_value)
    except:
        words_to_count = []
    
    new_count = count_swear_words_in_lyrics(lyrics, words_to_count)
    
    df.loc[idx, 'swear_IT'] = new_count
    
    if old_count != new_count:
        rows_changed += 1
    
    rows_processed += 1
    
print(f"unchanged rows: {rows_processed - rows_changed}")
print(f"rows where swear_IT_words was updated: {rows_changed}")

unchanged rows: 8397
rows where swear_IT_words was updated: 2761

### swear_EN

In [61]:
invalid_elems = df[df['swear_EN'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['swear_EN'])

nan_indexes = df.index[df['swear_EN'].isna()].tolist()
print(f"number of missing values in swear_EN: {len(nan_indexes)}")

Series([], Name: swear_EN, dtype: int64)
number of missing values in swear_EN: 0

In [62]:
rows_processed = 0
rows_changed = 0

for idx in df.index:
    lyrics = df.loc[idx, 'lyrics']
    old_count = df.loc[idx, 'swear_EN']
    
    swear_words_value = df.loc[idx, 'swear_EN_words']
    
    try:
        if pd.isna(swear_words_value) or swear_words_value == '[]':
            words_to_count = []
        else:
            words_to_count = ast.literal_eval(swear_words_value)
    except:
        words_to_count = []
    
    new_count = count_swear_words_in_lyrics(lyrics, words_to_count)
    
    df.loc[idx, 'swear_EN'] = new_count
    
    if old_count != new_count:
        rows_changed += 1
    
    rows_processed += 1
    
print(f"unchanged rows: {rows_processed - rows_changed}")
print(f"rows where swear_EN_words was updated: {rows_changed}")

unchanged rows: 10946
rows where swear_EN_words was updated: 212

### year

In [63]:
invalid_elems = df[df['year'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['year'])

nan_indexes = df.index[df['year'].isna()].tolist()
print(f"number of missing values in year: {len(nan_indexes)}")

0        2021.0
1        2020.0
2        2021.0
3        2019.0
4        2020.0
          ...
11153       NaN
11154    2015.0
11155       NaN
11156    2005.0
11157       NaN
Name: year, Length: 11157, dtype: object
number of missing values in year: 400

In [64]:
non_numeric = df[pd.to_numeric(df['year'], errors='coerce').isna() & df['year'].notna()]
print(f"non-numeric year values ({len(non_numeric)}):")
print(non_numeric['year'].unique())

df['year'] = pd.to_numeric(df['year'], errors='coerce').astype('Int64')

invalid_elems = df[df['year'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['year'])

nan_indexes = df.index[df['year'].isna()].tolist()
print(f"number of missing values in year: {len(nan_indexes)}")

non-numeric year values (38):
['nPmvFS' 'MoKKcY' 'PdLLvs' 'Tr5ghq' 'FZM9N5' '3KBIhx' '7arrc9' '0S4bYq'
 'Ww2RM0' 'YDWvPA' 'v9Gs4k' '1uWHmg' 's7ujOB' 'CeZdpY' 'DkWnRx' 'oiiWuy'
 'IlHfzv' 'uUsYUb' 'unxIUH' 'iW9Q9J' 'td0lg8' 'fNBiFf' 'RqnJ7g' 'VwVFFX'
 'Ise7dm' 'vgGgkT' 'QPNIJj' 'BMMnal' 'k2QnmQ' '6R1q9L' 'P03Hkq' 'tMcdp6'
 'epqCR2' 'Tl2Dgz' 'uiux8t' 'gZ2JDM' 'Gv70wC' '8i0piY']
0        2021
1        2020
2        2021
3        2019
4        2020
         ...
11153    <NA>
11154    2015
11155    <NA>
11156    2005
11157    <NA>
Name: year, Length: 11158, dtype: Int64
number of missing values in year: 438

In [65]:
invalid_years = df[(df['year'] < 1973) | (df['year'] > 2025)]

if len(invalid_years) > 0:
    print(f"found {len(invalid_years)} rows with invalid years (< 1973 or > 2025):")
    display(invalid_years[['id', 'title', 'name_artist', 'year']].head(10))
    
year_counts = df['year'].value_counts().sort_index()

year_counts_df = year_counts.reset_index()
year_counts_df.columns = ['Year', 'Number of Tracks']

chart = alt.Chart(year_counts_df).mark_bar(
    color='steelblue',
    opacity=0.7
).encode(
    x=alt.X('Year:Q', 
            axis=alt.Axis(format='d', labelAngle=-45), 
            title='Year'),
    y=alt.Y('Number of Tracks', title='Number of Tracks')
).properties(
    title='Distribution of Tracks per Year',
    width=1000,
    height=400
).interactive()

display(chart)

found 2151 rows with invalid years (< 1973 or > 2025):

          id                                 title    name_artist  year
6   TR170793                             LOBBY WAY  Rosa Chemical  2072
7   TR627195                                 SLATT  Rosa Chemical  2098
22  TR634516  Freestyle #redbullnext #essemagazine  Rosa Chemical  1917
29  TR242610                            Sono Io !!  Rosa Chemical  1920
34  TR344681                                ALIENO  Rosa Chemical  1901
35  TR945862                               Teschio  Rosa Chemical  2052
48  TR225367                             TIPO DI N  Rosa Chemical  2081
53  TR904495   Dovreicomprarmiunacollanacomeimigos  Rosa Chemical  2060
58  TR440692                               LATTE +  Rosa Chemical  1933
59  TR141416             I need some sleep (Intro)  Rosa Chemical  1928

alt.Chart(...)

there seems to be a lot of invalid years. the ones above the year 2025 are for obvious reasons wrong, but the ones below 1973 might be really old tracks. let's check this by using the lowest active_start field of the artists.csv dataset

In [66]:
artists_path = path.join('..', 'dataset', 'artists.csv')
df_artists = pd.read_csv(artists_path, sep=';')

df_artists['active_start'] = pd.to_datetime(df_artists['active_start'], errors='coerce')
missing_count = df_artists['active_start'].isna().sum()
print(f"missing active_start values: {missing_count}")

earliest_date = df_artists['active_start'].min()
print(f"earliest active_start: {earliest_date}")

missing active_start values: 54
earliest active_start: 1988-01-01 00:00:00

by checking them, we can notice that are there are no artist in the dataset with such low year of active_start. there might be one in the missing active_start values that is lower, but by checking some of the tracks with release year below 1973, i can say with enough confidence that those are all invalid years. the invalid years will be removed from the dataset, and the album date of the track will be used as a replacement.

In [67]:
missing_years = df['year'].isna()

df.loc[(df['year'] < 1973) | (df['year'] > 2025), 'year'] = None

print(f"total rows needing year fills: {df['year'].isna().sum()}")

mask_date_available = df['album_release_date'].notna()
mask_not_shared = ~df['album_name'].isin(shared_album_names)
mask_common = mask_date_available & mask_not_shared

mask_fill_year = df['year'].isna() & mask_common

df.loc[mask_fill_year, 'year'] = df.loc[mask_fill_year, 'album_release_date'].dt.year

df['year'] = df['year'].astype('Int64')

still_missing = df['year'].isna().sum()
fixed_count = missing_years.sum() + len(invalid_years) - still_missing

print(f"filled {fixed_count} rows")

year_counts = df['year'].value_counts().sort_index()

year_counts_df = year_counts.reset_index()
year_counts_df.columns = ['Year', 'Number of Tracks']

chart = alt.Chart(year_counts_df).mark_bar(
    color='steelblue',
    opacity=0.7
).encode(
    x=alt.X('Year:Q', 
            axis=alt.Axis(format='d', labelAngle=-45), 
            title='Year'),
    y=alt.Y('Number of Tracks', title='Number of Tracks')
).properties(
    title='Distribution of Tracks per Year',
    width=1000,
    height=400
).interactive()

display(chart)

total rows needing year fills: 2589
filled 1563 rows

alt.Chart(...)

### month

In [68]:
invalid_elems = df[df['month'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['month'])

nan_indexes = df.index[df['month'].isna()].tolist()
print(f"number of missing values in month: {len(nan_indexes)}")

0         4.0
1         3.0
2         2.0
3         3.0
4         5.0
         ...
11153     NaN
11154    11.0
11155     NaN
11156     1.0
11157     NaN
Name: month, Length: 11158, dtype: float64
number of missing values in month: 1196

In [69]:
df['month'] = pd.to_numeric(df['month'], errors='coerce').astype('Int64')

invalid_elems = df[df['month'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['month'])

nan_indexes = df.index[df['month'].isna()].tolist()
print(f"number of missing values in month: {len(nan_indexes)}")

0           4
1           3
2           2
3           3
4           5
         ...
11153    <NA>
11154      11
11155    <NA>
11156       1
11157    <NA>
Name: month, Length: 11158, dtype: Int64
number of missing values in month: 1196

In [70]:
invalid_months = df[(df['month'] < 1) | (df['month'] > 12)]

if len(invalid_months) > 0:
    print(f"found {len(invalid_months)} rows with invalid month (< 1 or > 12):")
    display(invalid_months[['id', 'title', 'name_artist', 'month']].head(10))

even though all the months have valid values, a lot of them are missing. they will be filled using the release date of the album associated to the track.

In [71]:
missing_months = df['month'].isna()

print(f"total rows needing month fills: {missing_months.sum()}")

mask_fill_month = df['month'].isna() & mask_common

df.loc[mask_fill_month, 'month'] = df.loc[mask_fill_month, 'album_release_date'].dt.month

rows_filled_months = mask_fill_month.sum()
print(f"filled {rows_filled_months} rows where month was missing.")

total rows needing month fills: 1196
filled 658 rows where month was missing.

### day

In [72]:
invalid_elems = df[df['day'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['day'])

nan_indexes = df.index[df['day'].isna()].tolist()
print(f"number of missing values in day: {len(nan_indexes)}")

0         2.0
1         6.0
2        19.0
3         8.0
4        29.0
         ...
11153     NaN
11154     9.0
11155     NaN
11156     1.0
11157     NaN
Name: day, Length: 11158, dtype: float64
number of missing values in day: 1322

In [73]:
df['day'] = pd.to_numeric(df['day'], errors='coerce').astype('Int64')

invalid_days = df[(df['month'] < 1) | (df['month'] > 31)]

if len(invalid_days) > 0:
    print(f"found {len(invalid_days)} rows with invalid days (< 1 or > 12):")
    display(invalid_days[['id', 'title', 'name_artist', 'day']].head(10))

even though all the days have valid values, a lot of them are missing. they will be filled using the release date of the album associated to the track.

In [74]:
missing_days = df['day'].isna()

print(f"total rows needing day fills: {missing_days.sum()}")

mask_fill_day = df['day'].isna() & mask_common

df.loc[mask_fill_day, 'day'] = df.loc[mask_fill_day, 'album_release_date'].dt.day

rows_filled_days = mask_fill_day.sum()
print(f"filled {rows_filled_days} rows where day was missing.")

total rows needing day fills: 1322
filled 704 rows where day was missing.

### n_sentences

In [75]:
invalid_elems = df[df['n_sentences'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['n_sentences'])

nan_indexes = df.index[df['n_sentences'].isna()].tolist()
print(f"number of missing values in n_sentences: {len(nan_indexes)}")

0        102.0
1         56.0
2         88.0
3         37.0
4         48.0
         ...
11153     75.0
11154     76.0
11155     74.0
11156     32.0
11157     45.0
Name: n_sentences, Length: 11158, dtype: float64
number of missing values in n_sentences: 70

In [76]:
df['n_sentences'] = pd.to_numeric(df['n_sentences'], errors='coerce').astype('Int64')

def count_sentences_in_lyrics(lyrics):
    if pd.isna(lyrics):
        return 0
    lines = lyrics.split('\n')
    count = sum(1 for line in lines if line.strip())
    return count

def count_empty_lines(lyrics):
    if pd.isna(lyrics):
        return 0
    lines = lyrics.split('\n')
    return sum(1 for line in lines if not line.strip())

def count_total_lines(lyrics):
    if pd.isna(lyrics):
        return 0
    return len(lyrics.split('\n'))

computed_sentences = df['lyrics'].apply(count_sentences_in_lyrics)
empty_lines = df['lyrics'].apply(count_empty_lines)
total_lines = df['lyrics'].apply(count_total_lines)

mismatches_sentences = df[df['n_sentences'] != computed_sentences]

print(f"matching rows: {len(df) - len(mismatches_sentences)}")
print(f"mismatching rows: {len(mismatches_sentences)}\n")

comparison_display = pd.DataFrame({
    'title': df['title'],
    'stored_n_sentences': df['n_sentences'],
    'computed_non_empty': computed_sentences,
    'empty_lines': empty_lines,
    'total_lines': total_lines,
    'diff': computed_sentences - df['n_sentences']
})
display(comparison_display.head(10))

matching rows: 4768
mismatching rows: 6390

,title,stored_n_sentences,computed_non_empty,empty_lines,total_lines,diff
0,polka 2 :-/,102,98,5,103,-4
1,POLKA,56,56,5,61,0
2,britney ;-),88,87,7,94,-1
3,CEO,37,37,4,41,0
4,LONDRA,48,48,6,54,0
5,BOHEME,62,62,8,70,0
6,LOBBY WAY,82,80,6,86,-2
7,SLATT,82,77,8,85,-5
8,MADE IN ITALY,82,82,8,90,0
9,ROSE & ROVI,50,49,3,52,-1

even if there are a lot of matching counting the lyric lines, and the mismatch looks close to the stored n_sentences value, we saw from the lyrics analysis that there are tracks stored in single lines, so it's not possible to count the number of sentences using the new lines. furthermore, there are many tracks containing more sentences for each line. let's try using a nlp library called spaCy:

In [77]:
def count_sentences_spacy(lyrics, lang, stored_n_sentences):
    if pd.isna(lyrics):
        return 0
    #only process italian and english (only two models used in the analysis)
    if lang not in ['it', 'en']:
        #return NA for missing language, otherwise keep stored value
        return 0 if pd.isna(lang) else stored_n_sentences
    
    nlp = models_tokenizers[lang]
    doc = nlp(lyrics)
    return len(list(doc.sents))

computed_sentences_spacy = df.apply(
    lambda row: count_sentences_spacy(row['lyrics'], row['language'], row['n_sentences']), 
    axis=1
)

#compare with stored values (only for rows where we computed sentences)
computed_mask = df['language'].isin(['it', 'en']) if 'language' in df.columns else pd.Series([True] * len(df))
mismatches_sentences_spacy = df[computed_mask & (df['n_sentences'] != computed_sentences_spacy)]

print(f"Rows computed (it/en): {computed_mask.sum()}")
print(f"Rows kept as stored (es/pt/fr/de/ru/bg): {(df['language'].notna() & ~computed_mask).sum()}")
print(f"Rows set to NA (missing language): {df['language'].isna().sum()}")
print(f"Matching rows: {computed_mask.sum() - len(mismatches_sentences_spacy)}")
print(f"Mismatching rows: {len(mismatches_sentences_spacy)}\n")

comparison_display = pd.DataFrame({
    'title': df['title'],
    'language': df['language'] if 'language' in df.columns else 'it',
    'stored_n_sentences': df['n_sentences'],
    'computed_spacy': computed_sentences_spacy,
    'computed_non_empty': computed_sentences,
    'diff_spacy': computed_sentences_spacy - df['n_sentences'],
    'diff_non_empty': computed_sentences - df['n_sentences']
})

# Sort by absolute difference in descending order and display top 10
display(comparison_display[computed_mask].head(10))

# cases where computed_non_empty is 1
print("\nCases where computed_non_empty = 1 (single line lyrics):")
single_line_mask = computed_sentences == 1
single_line_display = comparison_display[single_line_mask & computed_mask][
    ['title', 'language', 'stored_n_sentences', 'computed_spacy', 'computed_non_empty']
]
display(single_line_display.head(15))

Rows computed (it/en): 10975
Rows kept as stored (es/pt/fr/de/ru/bg): 55
Rows set to NA (missing language): 128
Matching rows: 96
Mismatching rows: 10879

,title,language,stored_n_sentences,computed_spacy,computed_non_empty,diff_spacy,diff_non_empty
0,polka 2 :-/,it,102,6,98,-96,-4
1,POLKA,it,56,1,56,-55,0
2,britney ;-),it,88,2,87,-86,-1
3,CEO,it,37,1,37,-36,0
4,LONDRA,it,48,1,48,-47,0
5,BOHEME,it,62,3,62,-59,0
6,LOBBY WAY,it,82,3,80,-79,-2
7,SLATT,it,82,4,77,-78,-5
8,MADE IN ITALY,it,82,1,82,-81,0
9,ROSE & ROVI,it,50,2,49,-48,-1

Cases where computed_non_empty = 1 (single line lyrics):

,title,language,stored_n_sentences,computed_spacy,computed_non_empty
497,Come Me,it,1,1,1
641,Escamotage,it,1,1,1
1776,Intro (Napolimanicomio),it,3,2,1
1928,Totòlude,it,8,8,1
1954,Dammi Ancora,it,11,11,1
1967,Cin Cin,it,1,1,1
1973,Tu Non Hai Mai,it,14,14,1
1974,Pronte A Tutto,it,3,2,1
1976,Non Dimentico Più,it,10,10,1
1977,Come Ti Senti?,it,6,6,1
3341,aspettative,it,39,33,1
3342,viaggio nei sentimenti,it,19,15,1
3343,testacoda,it,37,28,1
3344,l'amore rende ciechi,it,55,39,1
3346,ciro,it,36,24,1

since the puntuaction in some of this track is almost missing, spaCy can't obtain a real number of sentences. In order to fill n_sentences with a reasonable approssimation of the original column, lines will be count: if the lyric is in a single line (count == 1), then spaCy will be used

In [78]:
missing_n_sentences = ((df['n_sentences'].isna()) | (df['n_sentences'] == 0)) & df['lyrics'].notna()

print(f"rows with missing n_sentences but lyrics present: {missing_n_sentences.sum()}")

modified_rows = []

for idx in df[missing_n_sentences].index:
    lyrics = df.at[idx, 'lyrics']
    non_empty_count = count_sentences_in_lyrics(lyrics)
    
    #if only 1 non-empty line, use spaCy instead
    if non_empty_count == 1:
        lang = df.at[idx, 'language'] if 'language' in df.columns else 'it'
        if lang in ['it', 'en']:
            spacy_count = count_sentences_spacy(lyrics, lang, pd.NA)
            df.at[idx, 'n_sentences'] = spacy_count
            modified_rows.append({
                'index': idx,
                'title': df.at[idx, 'title'],
                'language': lang,
                'method': 'spacy',
                'n_sentences': spacy_count
            })
        else:
            df.at[idx, 'n_sentences'] = non_empty_count
            modified_rows.append({
                'index': idx,
                'title': df.at[idx, 'title'],
                'language': lang,
                'method': 'line_count',
                'n_sentences': non_empty_count
            })
    else:
        df.at[idx, 'n_sentences'] = non_empty_count
        modified_rows.append({
            'index': idx,
            'title': df.at[idx, 'title'],
            'language': df.at[idx, 'language'] if 'language' in df.columns else 'it',
            'method': 'line_count',
            'n_sentences': non_empty_count
        })

print(f"filled n_sentences for {missing_n_sentences.sum()} rows")
modified_df = pd.DataFrame(modified_rows)
display(modified_df.head(15))

rows with missing n_sentences but lyrics present: 70
filled n_sentences for 70 rows

    index                    title language      method  n_sentences
0    3665    Quelli che benpensano       it  line_count           79
1    3666                 Autodafè       it  line_count           67
2    3667           Fight da faida       it  line_count           97
3    3668     Giù le mani da Caino       it  line_count           89
4    3669                   Pedala       it  line_count           78
5    3670             Accendimi...       it  line_count          104
6    3671                     Fili       it  line_count           69
7    3672              Rap Lamento       it  line_count           76
8    3673         Cali di tensione       it  line_count           94
9    3674        Cubetti tricolori       it  line_count           14
10   3675       Faccio la mia cosa       it  line_count          103
11   3676          Libri Di Sangue       it  line_count           97
12   3677       Potere Alla Parola       it  line_count          107
13   3678                   Nuvole       it  line_count           66
14   3679  Il beat come anestetico       it  line_count           89

 ### n_tokens

In [79]:
invalid_elems = df[df['n_tokens'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['n_tokens'])

nan_indexes = df.index[df['n_tokens'].isna()].tolist()
print(f"number of missing values in n_tokens: {len(nan_indexes)}")

0        911.0
1        675.0
2        758.0
3        382.0
4        429.0
         ...
11153    624.0
11154    602.0
11155    570.0
11156    304.0
11157    338.0
Name: n_tokens, Length: 11158, dtype: float64
number of missing values in n_tokens: 70

In [80]:
df['n_tokens'] = pd.to_numeric(df['n_tokens'], errors='coerce').astype('Int64')

def count_words(lyrics):
    if pd.isna(lyrics):
        return 0
    return len(lyrics.split()) #split by whitespace

computed_words = df['lyrics'].apply(count_words)

matches_words = (df['n_tokens'] == computed_words).sum()
matching_tracks = df[computed_words == df['n_tokens']].copy()
diff_words = computed_words - df['n_tokens']

print(f"matches: {matches_words}")
print(f"mean difference: {diff_words.mean():+.2f}")
print(f"Variance: {diff_words.var():+.2f}")
print(f"Standard deviation: {diff_words.std():+.2f}")

matching_tracks = matching_tracks[matching_tracks['lyrics'].notna()]

print(f"\nsome matching tracks:")
display_cols = ['title', 'n_tokens', 'lyrics']
display(matching_tracks[display_cols].head(20))

matches: 141
mean difference: -79.53
Variance: +2668.66
Standard deviation: +51.66

some matching tracks:

,title,n_tokens,lyrics
641,Escamotage,8,Biggie Paul sopra il beat sta in alto
1981,Intro,12,La Pina\nPina\nLa Pina\nPina\nLa Pina\nPina\nL...
2670,Nobiltà Di Strada (Intro),4,Inoki\nNobiltà di strada
3179,Star*,26,Senorita sai che sono un giovane re\n\nOcchi a...
3482,Cantico Errante Di Due D.J. Notturni,14,Questo è il nostro stile\n\nMica male\nDue\nDJ...
4010,Prologo,32,Prima che il gallo canti due volte\nTu avrai n...
4481,Unknown 8,57,Solo paranoie\nPrima o poi so che tornerai\nSo...
5144,LA CADUTA DELL'ANGELO - Intro,18,Mi ero svegliata in un posto che non conoscevo...
8156,Intro,27,La strada è la mia seconda madre\nRappresent C...
8848,Non esistono risposte intelligenti,3,A domande stupide
10153,Unpodi,360,Un po' di figa un po' di figa un po' di figa\n...
10332,Musica,522,A me la musica mi fa volare\nA me la musica mi...
10335,Tekila,221,Bum bum bum Bum bum bum Bum bum bum Bum bum bu...

the number of tokens doesn't seem to count the tokens only by splitting by whitespace. From the mean difference, we can notice that there are missing tokens that are not getting counted. By analyzing some of the lyrics, all seem to have in common to be short (mostly errors) and with no punctuation, so i'll try to include it in the token count

In [81]:
def count_tokens_split_punctuation(lyrics):
    if pd.isna(lyrics):
        return 0
    import re
    #split on word boundaries - keeps alphanumeric sequences separate from punctuation
    # \w+ -> word characters (letters, numbers); [^\w\s] ->  punctuation (not words and not separators);
    tokens = re.findall(r'\w+|[^\w\s]', lyrics, flags=re.UNICODE)
    return len(tokens)

computed_split_punct = df['lyrics'].apply(count_tokens_split_punctuation)

matches_words = (df['n_tokens'] == computed_split_punct).sum()
matching_tracks = df[computed_split_punct == df['n_tokens']].copy()
diff_words = computed_split_punct - df['n_tokens']

print(f"matches: {matches_words}")
print(f"mean difference: {diff_words.mean():+.2f}")
print(f"Variance: {diff_words.var():+.2f}")
print(f"Standard deviation: {diff_words.std():+.2f}")

matching_tracks = matching_tracks[matching_tracks['lyrics'].notna()]

print(f"\nsome matching tracks:")
display_cols = ['title', 'n_tokens', 'lyrics']
display(matching_tracks[display_cols].head(20))

print("\nsome mismatching tracks:")
mismatch_tracks = df[computed_split_punct != df['n_tokens']].copy()
mismatch_tracks['computed_split_punct'] = computed_split_punct[mismatch_tracks.index]
mismatch_tracks['diff'] = mismatch_tracks['computed_split_punct'] - mismatch_tracks['n_tokens']
display_cols = ['title', 'n_tokens', 'computed_split_punct', 'diff', 'lyrics']
display(mismatch_tracks[display_cols].head(10))

matches: 591
mean difference: +3.49
Variance: +650.59
Standard deviation: +25.51

some matching tracks:

,title,n_tokens,lyrics
50,Blackout,241,"Chiusi dentro una stanza senza guardare l'ora,..."
62,Ritratti dell'odio,805,"Kranyo, ah, vai\n\nMi siedo e ripenso ""Mah, st..."
82,Chicas,333,Tutte matte le mie amiche\nTutte matte le mie ...
113,Mood Blu,396,"Tra tutte le scuse che mi racconto, mi circond..."
153,CI SARÒ,386,"Voglio guadagnarmi da vivere, ma non vivere pe..."
167,non so chi ha creato il mondo,45,Questa donna che riflette il cielo\nChe fa azz...
176,WNDLST Freestyle,219,"Eh, okay\nNon sono uno che parla tanto, ma sto..."
196,Omega (Outro),472,"Tranne una volta, lei ricorda bene\nSputo vele..."
235,BLESS SU BLESS,511,(Vedo bless) Da quando ero nella culla\n(Chied...
269,Cazzeggio Nella BV3 House,112,Probabilmente si tratta di un provino di BV3 s...
300,Nuova Car,46,"Yah,yah\nGuarda la mia nuova car\nVado avanti ..."
302,2ombie*,109,"\nYeah\n\nCerte volte mi sembro uno zombie, zo..."
303,via da te,59,Ah\nFumiamo le mura di sta casa\nSentivo le tu...
328,100 MESSAGGI,527,"Ti prego, non cominciare\nSai che per me è già..."
467,MOB (DJM),139,Sta giacca non è mia come Don Pietro\n\nSta gi...
478,Sto Bene,428,All the signs (All the signs)\nOf a dying nati...
490,Triplè,389,Se esiste una seconda vita vorrei essere un ga...
492,Freestyle Grezzo,356,"Lazzino, flow stellare, Guerra Stellare (yeah)..."
497,Come Me,16,"La produzione è opera di El Feo, all'epoca not..."
561,Oh Shit!,552,Ho i cavalli di una Benz e per strada non mi t...

some mismatching tracks:

,title,n_tokens,computed_split_punct,diff,lyrics
0,polka 2 :-/,911,945,34,"Oplà, ah\nBdope, chiama due b—\n\nMi candidere..."
1,POLKA,675,733,58,"Greg Willen, non dormire\n(Brr-poh)\n\nT-T-Tro..."
2,britney ;-),758,792,34,"Mothz\nYeah, yeah, yeah-yeah\nBdope, chiama du..."
3,CEO,382,390,8,Designer sui vestiti penso di essere un outlet...
4,LONDRA,429,438,9,"Bdope (Yeah)\n\nVuole solo me, non fare la gel..."
5,BOHEME,387,456,69,Uh-uh\nAh-li-ah\nUh-uh\n\nSenti la pioggia che...
6,LOBBY WAY,680,671,-9,"Dback in your head, motherfuckers\nBdope, chia..."
7,SLATT,657,697,40,"Bdope, chiama due bitches\nPe-pe-pe-pe-pe-pew\..."
8,MADE IN ITALY,584,672,88,"Damn (Shlet)\nAhah, Rosa\nBdope, chiama due –\..."
9,ROSE & ROVI,589,627,38,"Cambiare, sì, ma non è facile (Pow)\nMi bacia ..."

this produces a result similar to the one in the dataset (with even long songs matching), but it's hard to say which are the chars that counted as tokens and which are not. let's see the results of a nlp library (spaCy):

In [82]:
def analyze_n_tokens_nlp(lyrics, lang, models_tokenizers):
    if pd.isna(lyrics):
        return 0
    nlp = models_tokenizers.get(lang, models_tokenizers['it']) #it as default
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        doc = nlp(lyrics)
    return len([t for t in doc if not t.is_space])

print("Starting spaCy tokenization")

df['real_n_tokens'] = df.apply(
    lambda row: analyze_n_tokens_nlp(row['lyrics'], row['language'], models_tokenizers),
    axis=1
)

n_tokens_stored = pd.to_numeric(df['n_tokens'], errors='coerce').astype('Int64')
real_n_tokens_nullable = pd.to_numeric(df['real_n_tokens'], errors='coerce').astype('Int64')

matches = (n_tokens_stored.fillna(-1) == real_n_tokens_nullable.fillna(-1)).sum()
total_rows = len(df)
mismatches = total_rows - matches

diff_tokens = real_n_tokens_nullable.astype('float') - n_tokens_stored.astype('float')
mean_diff = diff_tokens.mean()

print(f"Total rows processed: {total_rows}")
print(f"Matching rows (stored 'n_tokens' == 'real_n_tokens'): {matches}")
print(f"Mismatching rows: {mismatches}")
print(f"Mean difference (real_n_tokens - n_tokens): {mean_diff:+.2f}")
print(f"Variance: {diff_tokens.var():+.2f}")
print(f"Standard deviation: {diff_tokens.std():+.2f}")

mismatch_tracks = df[n_tokens_stored != real_n_tokens_nullable].copy()
mismatch_tracks['diff'] = real_n_tokens_nullable[mismatch_tracks.index] - n_tokens_stored[mismatch_tracks.index]
display_cols = ['title', 'language', 'n_tokens', 'real_n_tokens', 'diff', 'lyrics']
display(mismatch_tracks[display_cols].head(10))

Starting spaCy tokenization
Total rows processed: 11158
Matching rows (stored 'n_tokens' == 'real_n_tokens'): 340
Mismatching rows: 10818
Mean difference (real_n_tokens - n_tokens): -8.39
Variance: +507.37
Standard deviation: +22.52

,title,language,n_tokens,real_n_tokens,diff,lyrics
0,polka 2 :-/,it,911,936,25,"Oplà, ah\nBdope, chiama due b—\n\nMi candidere..."
1,POLKA,it,675,674,-1,"Greg Willen, non dormire\n(Brr-poh)\n\nT-T-Tro..."
2,britney ;-),it,758,784,26,"Mothz\nYeah, yeah, yeah-yeah\nBdope, chiama du..."
4,LONDRA,it,429,437,8,"Bdope (Yeah)\n\nVuole solo me, non fare la gel..."
5,BOHEME,it,387,454,67,Uh-uh\nAh-li-ah\nUh-uh\n\nSenti la pioggia che...
6,LOBBY WAY,it,680,670,-10,"Dback in your head, motherfuckers\nBdope, chia..."
7,SLATT,it,657,689,32,"Bdope, chiama due bitches\nPe-pe-pe-pe-pe-pew\..."
8,MADE IN ITALY,it,584,660,76,"Damn (Shlet)\nAhah, Rosa\nBdope, chiama due –\..."
9,ROSE & ROVI,it,589,621,32,"Cambiare, sì, ma non è facile (Pow)\nMi bacia ..."
10,POLKA 3,it,487,484,-3,"Bdope, (Mmh, yeah) chiama due —\n\nBaciami in ..."

a simple regex seems to be more accurate (more matches and closer mean difference) compared to the spaCy tokenization. It's also faster to use regex compared to a nlp library, which is why the regex will be used on the missing values.

In [83]:
missing_n_tokens = ((df['n_tokens'].isna()) | (df['n_tokens'] == 0)) & df['lyrics'].notna()

print(f"rows with missing n_tokens but lyrics present: {missing_n_tokens.sum()}")

modified_rows = []

for idx in df[missing_n_tokens].index:
    lyrics = df.at[idx, 'lyrics']
    regex_token_count = count_tokens_split_punctuation(lyrics)
    
    df.at[idx, 'n_tokens'] = regex_token_count
    
    modified_rows.append({
        'index': idx,
        'title': df.at[idx, 'title'],
        'n_tokens_filled': regex_token_count
    })

print(f"filled n_tokens for {len(modified_rows)} rows.")

modified_df = pd.DataFrame(modified_rows)
display(modified_df.head(15))

rows with missing n_tokens but lyrics present: 70
filled n_tokens for 70 rows.

    index                    title  n_tokens_filled
0    3665    Quelli che benpensano              738
1    3666                 Autodafè              510
2    3667           Fight da faida              851
3    3668     Giù le mani da Caino              748
4    3669                   Pedala              565
5    3670             Accendimi...              932
6    3671                     Fili              444
7    3672              Rap Lamento              635
8    3673         Cali di tensione              845
9    3674        Cubetti tricolori              134
10   3675       Faccio la mia cosa             1078
11   3676          Libri Di Sangue              746
12   3677       Potere Alla Parola              724
13   3678                   Nuvole              546
14   3679  Il beat come anestetico              743

### tokens_per_sent

In [84]:
invalid_elems = df[df['tokens_per_sent'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['tokens_per_sent'])

nan_indexes = df.index[df['tokens_per_sent'].isna()].tolist()
print(f"number of missing values in tokens_per_sent: {len(nan_indexes)}")

0         8.931373
1        12.053571
2         8.613636
3        10.324324
4         8.937500
           ...
11153     8.320000
11154     7.921053
11155     7.702703
11156     9.500000
11157     7.511111
Name: tokens_per_sent, Length: 11158, dtype: float64
number of missing values in tokens_per_sent: 70

In [85]:
expected_tokens_per_sent = df['n_tokens'] / df['n_sentences']

tolerance = 1e-6
matches = (abs(df['tokens_per_sent'] - expected_tokens_per_sent) <= tolerance) | (df['tokens_per_sent'].isna() & expected_tokens_per_sent.isna())

total_rows = len(df)
num_matches = matches.sum()
num_mismatches = total_rows - num_matches

print(f"Matching rows (correct n_tokens over n_sentences): {num_matches}")
print(f"Mismatching rows: {num_mismatches}")

Matching rows (correct n_tokens over n_sentences): 10960
Mismatching rows: 198

this column is correctly computed, the 198 missing values are given by the missing 76 values of n_tokens and n_sentences + 128 NaN values. let's fill the missing values:

In [86]:
mask_to_fill = (
    (df['tokens_per_sent'].isna()) | (df['tokens_per_sent'] == 0) &
    df['n_tokens'].notna() &
    df['n_sentences'].notna() &
    (df['n_sentences'] != 0)
)

indices_to_fill = df[mask_to_fill].index

n_tokens = df.loc[indices_to_fill, 'n_tokens']
n_sentences = df.loc[indices_to_fill, 'n_sentences']

new_values = n_tokens / n_sentences
        
df.loc[indices_to_fill, 'tokens_per_sent'] = new_values

print(f"successfully filled {len(indices_to_fill)} rows")

successfully filled 70 rows

### char_per_tok

In [87]:
invalid_elems = df[df['char_per_tok'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['char_per_tok'])

nan_indexes = df.index[df['char_per_tok'].isna()].tolist()
print(f"number of missing values in char_per_tok: {len(nan_indexes)}")

Series([], Name: char_per_tok, dtype: float64)
number of missing values in char_per_tok: 70

In [88]:
def count_chars_no_whitespace(lyrics): #count characters excluding all whitespace
    if pd.isna(lyrics):
        return 0
    return len(re.sub(r'\s', '', lyrics))

total_chars_no_whitespace = df['lyrics'].apply(count_chars_no_whitespace)

n_tokens_safe = df['n_tokens'].replace(0, np.nan)

expected_cpt = total_chars_no_whitespace / n_tokens_safe

tolerance = 1e-6
matches = (abs(df['char_per_tok'] - expected_cpt) <= tolerance) | \
          (df['char_per_tok'].isna() & expected_cpt.isna())

num_matches = matches.sum()
num_mismatches = len(df) - num_matches

diff_series = (df['char_per_tok'] - expected_cpt).dropna()
mean_diff = diff_series.mean()
variance_diff = diff_series.var()
std_diff = diff_series.std()

print(f"matching rows: {num_matches}")
print(f"mismatching rows: {num_mismatches}")
print(f"Mean difference: {mean_diff:.6f}")
print(f"Variance: {variance_diff:.6f}")
print(f"Standard deviation: {std_diff:.6f}")
print(f"Mean absolute difference: {diff_series.abs().mean():.6f}\n")


if num_matches > 0:
    print("some matches:")

    has_lyrics = df['lyrics'].notna() & (df['lyrics'].str.strip() != "")
    matching_df = df[matches & has_lyrics].copy()
    matching_display = pd.DataFrame({
        'title': matching_df['title'],
        'computed_cpt': expected_cpt[matching_df.index],
        'n_tokens': matching_df['n_tokens'],
        'chars_no_ws': total_chars_no_whitespace[matching_df.index],
        'lyrics': matching_df['lyrics'],
    })
    display(matching_display.head(20))

if num_mismatches > 0:
    print("some mismatches:")
    
    mismatches_df = df[~matches].copy()
    mismatches_display = pd.DataFrame({
        'title': mismatches_df['title'],
        'stored_cpt': mismatches_df['char_per_tok'],
        'computed_cpt': expected_cpt[mismatches_df.index],
        'diff': (mismatches_df['char_per_tok'] - expected_cpt[mismatches_df.index]).abs()
    })
    
    display(mismatches_display.head(10))

matching rows: 45
mismatching rows: 11113
Mean difference: 0.320881
Variance: 0.038944
Standard deviation: 0.197343
Mean absolute difference: 0.321299

some matches:

,title,computed_cpt,n_tokens,chars_no_ws,lyrics
641,Escamotage,3.75,8,30,Biggie Paul sopra il beat sta in alto
758,Intro (Dinamite),4.4,5,22,violence\n rastaman\nI don't
964,Cose Non Sane (Interlude),3.962963,27,107,Facevamo l'amore per non litigare\nPer avere f...
1155,Balb & Tando,4.52459,122,552,Per le ragazze sono negato incapace impacciato...
1431,Ma vaffanculo,4.473684,19,85,Lasciami andare a dormire\nCome se avessi la s...
1926,Interlude 1 (Mi Fist),4.0,30,120,I just can't understand\nI just can't understa...
1981,Intro,3.333333,12,40,La Pina\nPina\nLa Pina\nPina\nLa Pina\nPina\nL...
2670,Nobiltà Di Strada (Intro),5.0,4,20,Inoki\nNobiltà di strada
3179,Star*,4.423077,26,115,Senorita sai che sono un giovane re\n\nOcchi a...
3201,Non Voglio Morire Qui,4.014634,205,823,Linee scritte sulla pelle\nCorri fino a che po...
3471,Fatti In Là,2.769231,13,36,E dj Jad è lì ai piatti ed è sempre più stiloso
3482,Cantico Errante Di Due D.J. Notturni,3.5,14,49,Questo è il nostro stile\n\nMica male\nDue\nDJ...
3516,Così e cosà (RMX '97 Strumentale),3.833333,42,161,Fare l'amore\nEvviva la vita\n\nFare l'amore\n...
3636,Tanta Luce,3.71519,158,587,Ero senza te \nPrima io \nEro senza te \nE una...
3640,"Dubai (Why, Oh Why)",3.994012,167,667,Che non ti fai viva con me\nChe ci posso fare ...
3647,Tutto Tu,4.2,130,546,Fai tutto tu\nC'hai tutto tu\nVuoi tutto tu\nE...
3649,Giorni e giorni,4.361111,72,314,Giorni e giorni\nGiorni così sempre fuori\nGio...
3650,Ma jolie,3.534562,217,767,Ritorna già di attualità la barba un po' più l...
3946,Prosopagno Sia! (Prisoner 709),3.214286,168,540,And if you call my name\nI don't recognize it\...
4010,Prologo,4.03125,32,129,Prima che il gallo canti due volte\nTu avrai n...

some mismatches:

           title  stored_cpt  computed_cpt      diff
0    polka 2 :-/    4.170455       3.45225  0.718204
1          POLKA    4.280851      3.285926  0.994925
2    britney ;-)    4.075251      3.411609  0.663641
3            CEO    4.023881      3.623037  0.400844
4         LONDRA    3.922857      3.379953  0.542904
5         BOHEME    4.160606      3.697674  0.462932
6      LOBBY WAY    3.817680      3.251471  0.566209
7          SLATT    4.031373      3.343988  0.687385
8  MADE IN ITALY    3.935841      3.263699  0.672142
9    ROSE & ROVI    3.851508      3.086587  0.764921

by counting the characters excluding all the white spaces, we find matches with tracks whose lyrics contain no punctuation (as we can notice in tracks such as "Non Voglio Morire Qui"). However, methods that ignore all punctuation perform worse: there are most likely some punctuation that are counted in the chars/token analysis and others that are not.

The rows with empty char_per_tok will be filled by doing all_chars / n_tokens

In [89]:
mask_to_fill = (
    (df['char_per_tok'].isna()) | (df['char_per_tok'] == 0) &
    df['n_tokens'].notna() &
    df['n_sentences'].notna() &
    (df['n_tokens'] != 0)
)

indices_to_fill = df[mask_to_fill].index

chars_no_ws = df.loc[indices_to_fill, 'lyrics'].apply(count_chars_no_whitespace)
n_tokens = df.loc[indices_to_fill, 'n_tokens']

new_values = chars_no_ws / n_tokens

#fill in the missing values
df.loc[indices_to_fill, 'char_per_tok'] = new_values

print(f"successfully filled {len(indices_to_fill)} rows")

successfully filled 70 rows

### lexical_density

In [90]:
invalid_elems = df[df['lexical_density'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['lexical_density'])

nan_indexes = df.index[df['lexical_density'].isna()].tolist()
print(f"number of missing values in lexical_density: {len(nan_indexes)}")

Series([], Name: lexical_density, dtype: float64)
number of missing values in lexical_density: 70

In [91]:
invalid_density = df[(df['lexical_density'] < 0) | (df['lexical_density'] > 1)]
print(f"rows with invalid density (not in [0, 1] range): {len(invalid_density)}")

def compute_lexical_density_regex(lyrics):
    if pd.isna(lyrics):
        return 0
    
    all_tokens = re.findall(r"[^\W\d_]+(?:['’-][^\W\d_]+)*", lyrics.lower(), flags=re.UNICODE) #finds both words and numbers
    
    all_words = all_tokens #filter out any tokens that are just numbers
    
    total_words = len(all_words)
    if total_words == 0:
        return 0
    
    unique_words = len(set(all_words)) #count of unique words
    
    return unique_words / total_words

computed_ld_regex = df['lyrics'].apply(compute_lexical_density_regex)

tolerance = 1e-3
matches_regex = (abs(df['lexical_density'] - computed_ld_regex) <= tolerance) | \
               (df['lexical_density'].isna() & computed_ld_regex.isna())

num_matches_regex = matches_regex.sum()
total_rows = len(df)

diff_ld = computed_ld_regex - df['lexical_density']
mean_diff_ld = diff_ld.mean()

print("\nVerifying calculation (Regex: unique_alpha_words / total_alpha_words):")
print(f"Total rows: {total_rows}")
print(f"Matching rows: {num_matches_regex}")
print(f"Mismatching rows: {total_rows - num_matches_regex}")
print(f"mean difference: {mean_diff_ld:+.6f}")
print(f"Variance: {diff_ld.var():.6f}")
print(f"Standard deviation: {diff_ld.std():.6f}")

# 5. Display Mismatches
if (total_rows - num_matches_regex) > 0:
    mismatches = df[~matches_regex].copy()
    mismatches_display = pd.DataFrame({
        'title': mismatches['title'],
        'language': mismatches['language'],
        'stored_lexical_density': mismatches['lexical_density'],
        'computed_ld_regex': computed_ld_regex[mismatches.index]
    })
    print("\nSample mismatches (Regex):")
    display(mismatches_display.head(10))

rows with invalid density (not in [0, 1] range): 0

Verifying calculation (Regex: unique_alpha_words / total_alpha_words):
Total rows: 11158
Matching rows: 213
Mismatching rows: 10945
mean difference: -0.023543
Variance: 0.013464
Standard deviation: 0.116035

Sample mismatches (Regex):

           title language  stored_lexical_density  computed_ld_regex
0    polka 2 :-/       it                0.575284           0.536296
1          POLKA       it                0.648936           0.476852
2    britney ;-)       it                0.556856           0.473684
3            CEO       it                0.534328           0.595541
4         LONDRA       it                0.491429           0.494083
5         BOHEME       it                0.506061           0.509434
6      LOBBY WAY       it                0.438306           0.382129
7          SLATT       it                0.535294           0.469636
8  MADE IN ITALY       it                0.537611           0.370098
9    ROSE & ROVI       it                0.554524           0.265060

even if the mean result is close, the variance seems high. let's see the results of a spaCy:

In [92]:
def analyze_lexical_density_nlp(lyrics, lang, models_tokenizers, stored_lexical_density):
    if pd.isna(lyrics):
        return 0 #return 0 for missing lyrics

    #return the stored value for non supported languages
    if lang not in ['it', 'en']:
        return stored_lexical_density

    nlp = models_tokenizers[lang]

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        doc = nlp(lyrics)
    
    all_alpha_words = [t.lower_ for t in doc if t.is_alpha]
    total_alpha = len(all_alpha_words)
    
    if total_alpha == 0:
        return 0
    else:
        unique_alpha = len(set(all_alpha_words))
        return unique_alpha / total_alpha

df['nlp_lexical_density'] = df.apply(
    lambda row: analyze_lexical_density_nlp(
        row['lyrics'], 
        row['language'], 
        models_tokenizers,
        row['lexical_density']
    ),
    axis=1
)

computed_mask = df['language'].isin(['it', 'en'])

computed_stored_ld = df.loc[computed_mask, 'lexical_density']
computed_nlp_ld = df.loc[computed_mask, 'nlp_lexical_density']

tolerance = 1e-3
matches_ld = (abs(computed_stored_ld - computed_nlp_ld) <= tolerance) | \
             (computed_stored_ld.isna() & computed_nlp_ld.isna())

num_computed_rows = computed_mask.sum()
num_matches_ld = matches_ld.sum()
mismatches = num_computed_rows - num_matches_ld

diff_ld_computed = computed_nlp_ld - computed_stored_ld

valid_diffs = diff_ld_computed.dropna() 

mean_diff_ld = valid_diffs.mean()
variance_diff = valid_diffs.var()
std_diff = valid_diffs.std()

total_rows = len(df)

print(f"rows in DataFrame: {total_rows}")
print(f"rows computed (it/en): {num_computed_rows}")
print(f"rows kept as stored (other langs + 0s): {total_rows - num_computed_rows}")

print(f"matching rows: {num_matches_ld}")
print(f"mismatching rows: {mismatches}")

print(f"Mean difference (over {len(valid_diffs)} non-NA rows): {mean_diff_ld:+.6f}")
print(f"Variance: {variance_diff:.6f}")
print(f"Standard deviation: {std_diff:.6f}\n")

stored_density = df['lexical_density']
computed_density_spacy = df['nlp_lexical_density']

diff_spacy = computed_density_spacy - stored_density
diff_regex = computed_ld_regex - stored_density

comparison_display = pd.DataFrame({
    'title': df['title'],
    'language': df['language'] if 'language' in df.columns else 'it',
    'stored_lexical_density': stored_density,
    'computed_spacy': computed_density_spacy,
    'computed_regex': computed_ld_regex,
    'diff_spacy': diff_spacy,
    'diff_regex': diff_regex
})

display(comparison_display[computed_mask].head(10))

valid_comparison_mask = (
    computed_mask & 
    stored_density.notna() & 
    computed_density_spacy.notna() & 
    computed_ld_regex.notna()
)

abs_diff_spacy = abs(diff_spacy[valid_comparison_mask])
abs_diff_regex = abs(diff_regex[valid_comparison_mask])

closer_to_spacy = (abs_diff_spacy < abs_diff_regex).sum()
closer_to_regex = (abs_diff_regex < abs_diff_spacy).sum()
ties = (abs_diff_spacy == abs_diff_regex).sum()

print(f"rows where spaCy density is closer:   {closer_to_spacy}")
print(f"rows where regex density is closer:  {closer_to_regex}")
print(f"rows with equal difference (ties): {ties}")

rows in DataFrame: 11158
rows computed (it/en): 10975
rows kept as stored (other langs + 0s): 183
matching rows: 76
mismatching rows: 10899
Mean difference (over 10905 non-NA rows): -0.031125
Variance: 0.013604
Standard deviation: 0.116635

,title,language,stored_lexical_density,computed_spacy,computed_regex,diff_spacy,diff_regex
0,polka 2 :-/,it,0.575284,0.509380,0.536296,-0.065905,-0.038988
1,POLKA,it,0.648936,0.444954,0.476852,-0.203982,-0.172084
2,britney ;-),it,0.556856,0.447635,0.473684,-0.109221,-0.083172
3,CEO,it,0.534328,0.572327,0.595541,0.037999,0.061213
4,LONDRA,it,0.491429,0.474138,0.494083,-0.017291,0.002654
5,BOHEME,it,0.506061,0.444134,0.509434,-0.061927,0.003373
6,LOBBY WAY,it,0.438306,0.376894,0.382129,-0.061412,-0.056176
7,SLATT,it,0.535294,0.444444,0.469636,-0.090850,-0.065658
8,MADE IN ITALY,it,0.537611,0.309979,0.370098,-0.227632,-0.167513
9,ROSE & ROVI,it,0.554524,0.240826,0.265060,-0.313699,-0.289464

rows where spaCy density is closer:   3639
rows where regex density is closer:  6151
rows with equal difference (ties): 1115

they both have similar results, so for performances reasons the regex version will be instead to fill the missing rows.

In [93]:
mask_to_fill = (
    (df['lexical_density'].isna()) | (df['lexical_density'] == 0) &
    computed_ld_regex.notna()
)

num_filled = mask_to_fill.sum()

new_values = computed_ld_regex[mask_to_fill]

df.loc[mask_to_fill, 'lexical_density'] = new_values

print(f"successfully filled {num_filled} 'lexical_density' rows")

successfully filled 198 'lexical_density' rows

### avg_token_per_clause

In [94]:
invalid_elems = df[df['avg_token_per_clause'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['avg_token_per_clause'])

nan_indexes = df.index[df['avg_token_per_clause'].isna()].tolist()
print(f"number of missing values in avg_token_per_clause: {len(nan_indexes)}")

Series([], Name: avg_token_per_clause, dtype: float64)
number of missing values in avg_token_per_clause: 70

In [95]:
def analyze_avg_token_per_clause(lyrics, lang, models_pos_taggers, stored_avg_token_per_clause):
    if pd.isna(lyrics):
        return 0

    if lang not in ['it', 'en']:
        return stored_avg_token_per_clause
    
    nlp = models_pos_taggers[lang]
    
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        doc = nlp(lyrics)
        
    total_non_punct_tokens = len([t for t in doc if not t.is_punct and not t.is_space])
    num_predicates = len([t for t in doc if t.pos_ in ('VERB', 'AUX')])
    
    if num_predicates == 0:
        return 0
    else:
        return total_non_punct_tokens / num_predicates


df['cmp_avg_token_per_clause'] = df.apply(
    lambda row: analyze_avg_token_per_clause(row['lyrics'], row['language'], models_pos_taggers, row['avg_token_per_clause']),
    axis=1
)

computed_mask = df['language'].isin(['it', 'en'])

computed_stored = df.loc[computed_mask, 'avg_token_per_clause']
computed_real = df.loc[computed_mask, 'cmp_avg_token_per_clause']

tolerance = 1e-3
matches_clause = (abs(computed_stored - computed_real) <= tolerance) | \
                 (computed_stored.isna() & computed_real.isna())

num_computed_rows = computed_mask.sum()
num_matches_clause = matches_clause.sum()
mismatches = num_computed_rows - num_matches_clause

diff_clause_computed = computed_real - computed_stored
    
valid_diffs = diff_clause_computed.dropna() 

mean_diff_clause = valid_diffs.mean()
variance_diff = valid_diffs.var()
std_diff = valid_diffs.std()

print(f"rows kept as stored (other langs + 0s): {total_rows - num_computed_rows}")
print(f"matching rows: {num_matches_clause}")
print(f"mismatching rows: {mismatches}")
print(f"mean difference (real - stored): {mean_diff_clause:+.6f}\n")
print(f"variance (real - stored): {variance_diff:.6f}")
print(f"std. Deviation (real - stored): {std_diff:.6f}\n")

if mismatches > 0:
        mismatch_indices = matches_clause[~matches_clause].index
        mismatches_df = df.loc[mismatch_indices].copy()
        mismatches_df['diff'] = diff_clause_computed[mismatch_indices]
        
        print("sample mismatches (from 'it'/'en' rows)")
        display(mismatches_df[['title', 'language', 'avg_token_per_clause', 'cmp_avg_token_per_clause', 'diff']].head(10))

rows kept as stored (other langs + 0s): 183
matching rows: 19
mismatching rows: 10956
mean difference (real - stored): -2.273068

variance (real - stored): 136.321990
std. Deviation (real - stored): 11.675701

sample mismatches (from 'it'/'en' rows)

,title,language,avg_token_per_clause,cmp_avg_token_per_clause,diff
0,polka 2 :-/,it,8.133929,6.805825,-1.328103
1,POLKA,it,12.500000,7.387097,-5.112903
2,britney ;-),it,8.422222,6.270833,-2.151389
3,CEO,it,6.701754,4.880597,-1.821157
4,LONDRA,it,8.411765,5.932203,-2.479561
5,BOHEME,it,6.450000,5.901639,-0.548361
6,LOBBY WAY,it,12.142857,8.265625,-3.877232
7,SLATT,it,10.265625,7.123288,-3.142337
8,MADE IN ITALY,it,11.018868,7.208955,-3.809913
9,ROSE & ROVI,it,9.349206,6.138889,-3.210317

here we don't have much choise other than relying on spaCy to identify the clauses.

In [96]:
mask_to_fill = (
    (df['avg_token_per_clause'].isna()) | (df['avg_token_per_clause'] == 0) &
    df['cmp_avg_token_per_clause'].notna() &
    df['cmp_avg_token_per_clause'] != 0
)

num_filled = mask_to_fill.sum()

new_values = df.loc[mask_to_fill, 'cmp_avg_token_per_clause']

df.loc[mask_to_fill, 'avg_token_per_clause'] = new_values

print(f"Successfully filled {num_filled} 'avg_token_per_clause' rows.")

Successfully filled 81 'avg_token_per_clause' rows.

### bmp

In [97]:
invalid_elems = df[df['bpm'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['bpm'])

nan_indexes = df.index[df['bpm'].isna()].tolist()
print(f"number of missing values in bpm: {len(nan_indexes)}")

Series([], Name: bpm, dtype: float64)
number of missing values in bpm: 64

In [98]:
invalid_bpm = df[(df['bpm'] < 0)]
if len(invalid_bpm) > 0:
    print(f"{len(invalid_bpm)} rows with invalid invalid_bpm (negative values):")
    display(invalid_bpm[['id', 'title', 'name_artist', 'bpm']].head(10))

chart_data = df[['bpm']].dropna().copy()
chart_data['bpm'] = pd.to_numeric(chart_data['bpm'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkred', 
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('bpm', bin=alt.Bin(maxbins=40), title='BPM (Beats Per Minute)'),
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by BPM',
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('bpm', title='BPM (Beats Per Minute)'),
    tooltip=[
        alt.Tooltip('min(bpm)', title='Min BPM'),
        alt.Tooltip('q1(bpm)', title='Q1 BPM'),
        alt.Tooltip('median(bpm)', title='Median BPM'),
        alt.Tooltip('q3(bpm)', title='Q3 BPM'),
        alt.Tooltip('max(bpm)', title='Max BPM')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [99]:
print(f"Top 10 tracks with the highest BPM:")
top_10_bpm = df.sort_values(by='bpm', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'bpm']])

Top 10 tracks with the highest BPM:

            id                    title    name_artist     bpm
8311  TR591502           Madtadone 2015         MadMan  738.27
4617  TR818482            Carta E Penna        Mistico  191.41
358   TR891506  L'ERBA VOGLIO (Geordie)          Lazza  184.57
6150  TR680749    Covid freestyle - Jax           J-Ax  184.57
2507  TR976307             The Banfator       Mistaman  184.57
5556  TR718501              UNA COME TE        Geolier  184.57
2995  TR686820                 ADDERALL    Rondodasosa  184.57
8457  TR988860      Hollywood Boulevard  Achille Lauro  184.57
971   TR963623           Ruggine E Ossa            Guè  184.57
9705  TR212098                   L'ODIO          Salmo  184.57

while the other tracks have reasonable bmp values, Madtadone 2015 by MadMan have an error value which will be set to NaN

In [100]:
condition = (df['id'] == 'TR591502')
print("removed error track:")
display(df[condition][['id', 'title', 'name_artist', 'bpm']])
df.loc[condition, 'bpm'] = np.nan

chart_data = df[['bpm']].dropna().copy()
chart_data['bpm'] = pd.to_numeric(chart_data['bpm'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkred', 
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('bpm', bin=alt.Bin(maxbins=40), title='BPM (Beats Per Minute)'),
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by BPM',
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('bpm', title='BPM (Beats Per Minute)'),
    tooltip=[
        alt.Tooltip('min(bpm)', title='Min BPM'),
        alt.Tooltip('q1(bpm)', title='Q1 BPM'),
        alt.Tooltip('median(bpm)', title='Median BPM'),
        alt.Tooltip('q3(bpm)', title='Q3 BPM'),
        alt.Tooltip('max(bpm)', title='Max BPM')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

removed error track:

            id           title name_artist     bpm
8311  TR591502  Madtadone 2015      MadMan  738.27

alt.VConcatChart(...)

### centroid

In [101]:
invalid_elems = df[df['centroid'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['centroid'])

nan_indexes = df.index[df['centroid'].isna()].tolist()
print(f"number of missing values in centroid: {len(nan_indexes)}")

Series([], Name: centroid, dtype: float64)
number of missing values in centroid: 64

In [102]:
chart_data = df[['centroid']].dropna().copy()
chart_data['centroid'] = pd.to_numeric(chart_data['centroid'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkblue',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('centroid', bin=alt.Bin(maxbins=40), title='Spectral Centroid (Hz)'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Spectral Centroid', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('centroid', title='Spectral Centroid (Hz)'),
    tooltip=[
        alt.Tooltip('min(centroid)', title='Min Centroid'),
        alt.Tooltip('q1(centroid)', title='Q1 Centroid'),
        alt.Tooltip('median(centroid)', title='Median Centroid'),
        alt.Tooltip('q3(centroid)', title='Q3 Centroid'),
        alt.Tooltip('max(centroid)', title='Max Centroid')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [103]:
print(f"Top 10 tracks with the highest Spectral Centroid:")
top_10_bpm = df.sort_values(by='centroid', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'centroid']])

print(f"Bottom 10 tracks with the lowest Spectral Centroid:")
top_10_bpm = df.sort_values(by='centroid', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'centroid']])

Top 10 tracks with the highest Spectral Centroid:

            id                title     name_artist  centroid
8326  TR274157  Una Più Del Diavolo          MadMan    0.2982
8333  TR158401   Notti Di Provincia          MadMan    0.2643
9394  TR235215             Drive By          Papa V    0.2596
1084  TR679925              Cartier             Guè    0.2509
5026  TR190083        Dimmi Come Fa          Il Tre    0.2421
8338  TR406392         La Rinascita          MadMan    0.2417
6620  TR552730          Guarda bene         Don Joe    0.2410
9074  TR467260       Branco di iene  Dark Polo Gang    0.2397
1057  TR655499       Il Sesto Senso             Guè    0.2383
6611  TR309605   Il resto del mondo         Don Joe    0.2352

Bottom 10 tracks with the lowest Spectral Centroid:

             id                 title    name_artist  centroid
8311   TR591502        Madtadone 2015         MadMan    0.0000
4877   TR508832                 In Tv          Vacca    0.0004
3158   TR485347               Squali*  Sfera Ebbasta    0.0148
1950   TR234003         Le Mie Amiche        La Pina    0.0322
365    TR609656  -3 (PERDERE IL VOLO)          Lazza    0.0386
3572   TR834246            Wicked Man          Neffa    0.0391
5067   TR636547       100 ROSE PER TE      M¥SS KETA    0.0396
7663   TR485111              Spin it*       Tony Boy    0.0397
10140  TR521844     Back In Blood RMX          Shiva    0.0400
2691   TR293661             Disstacco        Eva Rea    0.0472

the same track in the bpm analysis have also an error value in the spectral centroid, as well as another track named 'In Tv'. 'Una Più Del Diavolo' might be an outlier, as there are more MadMan songs with high spectral centroid.

In [104]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error centroid from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'centroid']])

df.loc[condition, 'centroid'] = np.nan

Removed error centroid from tracks:

            id           title name_artist  centroid
4877  TR508832           In Tv       Vacca    0.0004
8311  TR591502  Madtadone 2015      MadMan    0.0000

### rolloff

In [105]:
invalid_elems = df[df['rolloff'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['rolloff'])

nan_indexes = df.index[df['rolloff'].isna()].tolist()
print(f"number of missing values in rolloff: {len(nan_indexes)}")

Series([], Name: rolloff, dtype: float64)
number of missing values in rolloff: 64

In [106]:
chart_data = df[['rolloff']].dropna().copy()
chart_data['rolloff'] = pd.to_numeric(chart_data['rolloff'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkgreen',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('rolloff', bin=alt.Bin(maxbins=40), title='Spectral Rolloff (Hz)'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Spectral Rolloff', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('rolloff', title='Spectral Rolloff (Hz)'),
    tooltip=[
        alt.Tooltip('min(rolloff)', title='Min Rolloff'),
        alt.Tooltip('q1(rolloff)', title='Q1 Rolloff'),
        alt.Tooltip('median(rolloff)', title='Median Rolloff'),
        alt.Tooltip('q3(rolloff)', title='Q3 Rolloff'),
        alt.Tooltip('max(rolloff)', title='Max Rolloff')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [107]:
print(f"Top 10 tracks with the highest Spectral Rolloff:")
top_10_bpm = df.sort_values(by='rolloff', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'rolloff']])

print(f"Bottom 10 tracks with the lowest Spectral Rolloff:")
top_10_bpm = df.sort_values(by='rolloff', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'rolloff']])

Top 10 tracks with the highest Spectral Rolloff:

            id                title     name_artist    rolloff
8326  TR274157  Una Più Del Diavolo          MadMan  8635.9542
8333  TR158401   Notti Di Provincia          MadMan  6602.6082
254   TR106485   COVID-19 Freestyle          thasup  6209.2182
55    TR600518    BRITISH PROV 2014   Rosa Chemical  5476.3469
1084  TR679925              Cartier             Guè  5311.0667
1057  TR655499       Il Sesto Senso             Guè  5257.4073
4666  TR397721       2020 Freestyle          Madame  5179.1962
9074  TR467260       Branco di iene  Dark Polo Gang  5082.3203
9394  TR235215             Drive By          Papa V  4728.1250
3175  TR226953            Ice Cream   Sfera Ebbasta  4710.7121

Bottom 10 tracks with the lowest Spectral Rolloff:

            id                 title    name_artist   rolloff
8311  TR591502        Madtadone 2015         MadMan    0.0000
4877  TR508832                 In Tv          Vacca   14.4718
7544  TR930774         Fino a domani       Tony Boy  132.3839
3158  TR485347               Squali*  Sfera Ebbasta  140.7022
2775  TR826415                   187      Doll Kill  223.4683
7572  TR565053                 Si si       Tony Boy  228.5769
365   TR609656  -3 (PERDERE IL VOLO)          Lazza  234.6066
261   TR432428             Veri Fra*         thasup  250.7364
5141  TR406692            INTERMEZZO      M¥SS KETA  251.9674
3562  TR963213         El Chico Loco          Neffa  258.8036

the same tracks in the spectral centroid analysis have also an error value in the spectral rolloff. 'Una Più Del Diavolo' might be again an outlier, as there are more MadMan songs with high spectral centroid.

In [108]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error rolloff from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'rolloff']])

df.loc[condition, 'rolloff'] = np.nan

Removed error rolloff from tracks:

            id           title name_artist  rolloff
4877  TR508832           In Tv       Vacca  14.4718
8311  TR591502  Madtadone 2015      MadMan   0.0000

### flux

In [109]:
invalid_elems = df[df['flux'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['flux'])

nan_indexes = df.index[df['flux'].isna()].tolist()
print(f"number of missing values in flux: {len(nan_indexes)}")

Series([], Name: flux, dtype: float64)
number of missing values in flux: 64

In [110]:
chart_data = df[['flux']].dropna().copy()
chart_data['flux'] = pd.to_numeric(chart_data['flux'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkorange',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('flux', bin=alt.Bin(maxbins=40), title='Spectral Flux'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Spectral Flux', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('flux', title='Spectral Flux'),
    tooltip=[
        alt.Tooltip('min(flux)', title='Min Flux'),
        alt.Tooltip('q1(flux)', title='Q1 Flux'),
        alt.Tooltip('median(flux)', title='Median Flux'),
        alt.Tooltip('q3(flux)', title='Q3 Flux'),
        alt.Tooltip('max(flux)', title='Max Flux')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [111]:
print(f"Top 10 tracks with the highest Spectral Flux:")
top_10_bpm = df.sort_values(by='flux', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'flux']])

print(f"Bottom 10 tracks with the lowest Spectral Flux:")
top_10_bpm = df.sort_values(by='flux', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'flux']])

Top 10 tracks with the highest Spectral Flux:

            id                        title   name_artist    flux
3513  TR501665  Beat Box (Per Improvvisare)   Articolo 31  1.9285
9434  TR373731                         KLK!  Samuel Costa  1.8700
9563  TR533699                       Rapido     Dani Faiv  1.8439
295   TR416283                    Wickedboi        thasup  1.8344
9432  TR708868                    PICAPOLLO  Samuel Costa  1.7944
7085  TR757407                   Fuck/Peace      Gemitaiz  1.7860
497   TR868282                      Come Me         Lazza  1.7739
4811  TR183135                  Lady Sexxxy         Vacca  1.7278
6320  TR993661                    La Scelta      99 Posse  1.7249
4845  TR311526              Cosa Vuoi Da Me         Vacca  1.7182

Bottom 10 tracks with the lowest Spectral Flux:

             id                 title     name_artist    flux
8311   TR591502        Madtadone 2015          MadMan  0.0000
4877   TR508832                 In Tv           Vacca  0.0000
3158   TR485347               Squali*   Sfera Ebbasta  0.1893
8810   TR141303             Balaclava        Highsnob  0.3108
8828   TR719913               Rooftop        Highsnob  0.4026
5512   TR651038               40 anni  Dargen D’Amico  0.5742
10622  TR444933     Patto col diavolo    Mondo Marcio  0.5954
2215   TR408042          2031 (Intro)     Fabri Fibra  0.7251
1574   TR425349              Overture          Piotta  0.7549
8024   TR443378  Le parole più grandi            Coez  0.7696

the same tracks in the spectral rolloff analysis have also an error value in the spectral flux.

### flatness

In [112]:
invalid_elems = df[df['flatness'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['flatness'])

nan_indexes = df.index[df['flatness'].isna()].tolist()
print(f"number of missing values in flatness: {len(nan_indexes)}")

Series([], Name: flatness, dtype: float64)
number of missing values in flatness: 64

In [113]:
chart_data = df[['flatness']].dropna().copy()
chart_data['flatness'] = pd.to_numeric(chart_data['flatness'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='purple',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('flatness', bin=alt.Bin(maxbins=40), title='Spectral Flatness'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Spectral Flatness', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('flatness', title='Spectral Flatness'),
    tooltip=[
        alt.Tooltip('min(flatness)', title='Min Flatness'),
        alt.Tooltip('q1(flatness)', title='Q1 Flatness'),
        alt.Tooltip('median(flatness)', title='Median Flatness'),
        alt.Tooltip('q3(flatness)', title='Q3 Flatness'),
        alt.Tooltip('max(flatness)', title='Max Flatness')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [114]:
print(f"Bottom 15 tracks with the lowest Spectral Flatness:")
top_10_bpm = df.sort_values(by='flatness', ascending=True).head(15)
display(top_10_bpm[['id', 'title', 'name_artist', 'flatness']])

Bottom 15 tracks with the lowest Spectral Flatness:

,id,title,name_artist,flatness
8810,TR141303,Balaclava,Highsnob,0.1094
10961,TR935995,Faccio Brutto (2nd Roof RMX),Fedez,0.1707
10962,TR693094,Pensavo fosse amore e invece... (Roofio RMX),Fedez,0.1764
8326,TR274157,Una Più Del Diavolo,MadMan,0.1841
7351,TR107407,Haterproof (Detto Fatto RMX),Gemitaiz,0.1884
10307,TR789473,Troppo piccola,Caneda,0.1929
6423,TR460697,Casa,Entics,0.1951
10653,TR999958,Uno a Cento,Mondo Marcio,0.1968
1379,TR118045,Benji & Fede,Skioffi,0.1983
6382,TR880812,Fresh flash,Entics,0.2014
2214,TR376662,Certe Cose Si Sanno,Fabri Fibra,0.2021
8489,TR329592,Armani,Achille Lauro,0.2029
2211,TR282407,Fabri Fibra A Spit 2011,Fabri Fibra,0.2034
1110,TR378457,Nun Ce Provà,Guè,0.2036
4599,TR596529,Street,Ensi,0.2048

based on those values alone, it's hard to say if some of those outliers are errors, so in this preprocessing step nothing will be done

###  spectral_complexity

In [115]:
invalid_elems = df[df['spectral_complexity'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['spectral_complexity'])

nan_indexes = df.index[df['spectral_complexity'].isna()].tolist()
print(f"number of missing values in spectral_complexity: {len(nan_indexes)}")

Series([], Name: spectral_complexity, dtype: float64)
number of missing values in spectral_complexity: 64

In [116]:
chart_data = df[['spectral_complexity']].dropna().copy()
chart_data['spectral_complexity'] = pd.to_numeric(chart_data['spectral_complexity'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='hotpink',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('spectral_complexity', bin=alt.Bin(maxbins=40), title='Spectral Complexity'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Spectral Complexity', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('spectral_complexity', title='Spectral Complexity'),
    tooltip=[
        alt.Tooltip('min(spectral_complexity)', title='Min Complexity'),
        alt.Tooltip('q1(spectral_complexity)', title='Q1 Complexity'),
        alt.Tooltip('median(spectral_complexity)', title='Median Complexity'),
        alt.Tooltip('q3(spectral_complexity)', title='Q3 Complexity'),
        alt.Tooltip('max(spectral_complexity)', title='Max Complexity')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [117]:
print(f"Top 10 tracks with the highest Spectral Complexity:")
top_10_bpm = df.sort_values(by='spectral_complexity', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'spectral_complexity']])

print(f"Bottom 10 tracks with the lowest Spectral Complexity:")
top_10_bpm = df.sort_values(by='spectral_complexity', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'spectral_complexity']])

Top 10 tracks with the highest Spectral Complexity:

             id                title  name_artist  spectral_complexity
177    TR805380         Alfa (Intro)         Alfa              61.2225
6065   TR843425      Miss & Mr. Hyde         J-Ax              56.9958
7498   TR678089           Plenilunio        Slait              54.4348
3389   TR327271      SoldiSoldiSoldi  Articolo 31              54.2955
3411   TR423812  LA FIERA DEL CRINGE  Articolo 31              54.0795
6108   TR894140         Sono di moda         J-Ax              53.9999
10915  TR424160        Santa Madonna        Fedez              53.9990
5752   TR609176           Brain Suck        Shade              53.6906
8817   TR245407         No Boyfriend     Highsnob              53.5247
6104   TR927094            Reci-divo         J-Ax              53.0098

Bottom 10 tracks with the lowest Spectral Complexity:

,id,title,name_artist,spectral_complexity
4877,TR508832,In Tv,Vacca,0.0000
8311,TR591502,Madtadone 2015,MadMan,0.0000
10961,TR935995,Faccio Brutto (2nd Roof RMX),Fedez,0.3083
8828,TR719913,Rooftop,Highsnob,0.3816
8155,TR544070,Timeless Spirit,Shablo,0.6682
10962,TR693094,Pensavo fosse amore e invece... (Roofio RMX),Fedez,0.9473
1099,TR179203,MM & Guè Pequeno,Guè,0.9565
10648,TR866390,Freestyle,Mondo Marcio,1.2338
3682,TR_985675,Chiedi Chiedi,Frankie hi-nrg mc,1.2534
8793,TR290265,Fisher Price,Highsnob,1.3735

the same tracks in the spectral flux analysis have also an error value in the spectral complexity.

In [118]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error spectral_complexity from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'spectral_complexity']])

df.loc[condition, 'spectral_complexity'] = np.nan

Removed error spectral_complexity from tracks:

            id           title name_artist  spectral_complexity
4877  TR508832           In Tv       Vacca                  0.0
8311  TR591502  Madtadone 2015      MadMan                  0.0

### rms

In [119]:
invalid_elems = df[df['rms'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['rms'])

nan_indexes = df.index[df['rms'].isna()].tolist()
print(f"number of missing values in rms: {len(nan_indexes)}")

Series([], Name: rms, dtype: float64)
number of missing values in rms: 64

In [120]:
chart_data = df[['rms']].dropna().copy()
chart_data['rms'] = pd.to_numeric(chart_data['rms'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='yellowgreen',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('rms', bin=alt.Bin(maxbins=40), title='Root Mean Square'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Root Mean Square', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('rms', title='Root Mean Square'),
    tooltip=[
        alt.Tooltip('min(rms)', title='Min Root Mean Square'),
        alt.Tooltip('q1(rms)', title='Q1 Root Mean Square'),
        alt.Tooltip('median(rms)', title='Median Root Mean Square'),
        alt.Tooltip('q3(rms)', title='Q3 Root Mean Square'),
        alt.Tooltip('max(rms)', title='Max Root Mean Square')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [121]:
print(f"Top 10 tracks with the highest Root Mean Square:")
top_10_bpm = df.sort_values(by='rms', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'rms']])

print(f"Bottom 10 tracks with the lowest Root Mean Square:")
top_10_bpm = df.sort_values(by='rms', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'rms']])

Top 10 tracks with the highest Root Mean Square:

             id                    title     name_artist     rms
10723  TR411053       Non tornare a casa   Fred De Palma  0.6219
177    TR805380             Alfa (Intro)            Alfa  0.5916
7572   TR565053                    Si si        Tony Boy  0.5273
7544   TR930774            Fino a domani        Tony Boy  0.4712
9781   TR439677             Vuoto (2007)           Salmo  0.4561
9547   TR200420                  POPCORN       Dani Faiv  0.4487
9847   TR572270          The Bootyshaker        Tormento  0.4454
252    TR807338  6 1 akkollino freestyle          thasup  0.4407
5482   TR978886            Ode Con Creta  Dargen D’Amico  0.4273
10062  TR429962                 100 OPPS           Shiva  0.4221

Bottom 10 tracks with the lowest Root Mean Square:

,id,title,name_artist,rms
8311,TR591502,Madtadone 2015,MadMan,0.0000
4877,TR508832,In Tv,Vacca,0.0000
8828,TR719913,Rooftop,Highsnob,0.0041
1099,TR179203,MM & Guè Pequeno,Guè,0.0085
10961,TR935995,Faccio Brutto (2nd Roof RMX),Fedez,0.0093
10648,TR866390,Freestyle,Mondo Marcio,0.0103
10962,TR693094,Pensavo fosse amore e invece... (Roofio RMX),Fedez,0.0106
3682,TR_985675,Chiedi Chiedi,Frankie hi-nrg mc,0.0112
8155,TR544070,Timeless Spirit,Shablo,0.0114
7019,TR108035,OUTRO [2024],Mr.Rain,0.0123

the same tracks in the spectral complexity analysis have also an error value in the root mean square

In [122]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error rms from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'rms']])

df.loc[condition, 'rms'] = np.nan

Removed error rms from tracks:

            id           title name_artist  rms
4877  TR508832           In Tv       Vacca  0.0
8311  TR591502  Madtadone 2015      MadMan  0.0

### zcr

In [123]:
invalid_elems = df[df['zcr'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['zcr'])

nan_indexes = df.index[df['zcr'].isna()].tolist()
print(f"number of missing values in zcr: {len(nan_indexes)}")

Series([], Name: zcr, dtype: float64)
number of missing values in zcr: 64

In [124]:
chart_data = df[['zcr']].dropna().copy()
chart_data['zcr'] = pd.to_numeric(chart_data['zcr'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='darkturquoise',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('zcr', bin=alt.Bin(maxbins=40), title='Zero Crossing Rate'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Zero Crossing Rate', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('zcr', title='Zero Crossing Rate'),
    tooltip=[
        alt.Tooltip('min(zcr)', title='Min Zero Crossing Rate'),
        alt.Tooltip('q1(zcr)', title='Q1 Zero Crossing Rate'),
        alt.Tooltip('median(zcr)', title='Median Zero Crossing Rate'),
        alt.Tooltip('q3(zcr)', title='Q3 Zero Crossing Rate'),
        alt.Tooltip('max(zcr)', title='Max Zero Crossing Rate')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [125]:
print(f"Top 10 tracks with the highest Zero Crossing Rate:")
top_10_bpm = df.sort_values(by='zcr', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'zcr']])

print(f"Bottom 10 tracks with the lowest Zero Crossing Rate:")
top_10_bpm = df.sort_values(by='zcr', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'zcr']])

Top 10 tracks with the highest Zero Crossing Rate:

            id                title     name_artist     zcr
8326  TR274157  Una Più Del Diavolo          MadMan  0.2683
8333  TR158401   Notti Di Provincia          MadMan  0.2158
254   TR106485   COVID-19 Freestyle          thasup  0.2050
55    TR600518    BRITISH PROV 2014   Rosa Chemical  0.1856
8972  TR682142        Rifletti Bene         Rancore  0.1778
9074  TR467260       Branco di iene  Dark Polo Gang  0.1692
1057  TR655499       Il Sesto Senso             Guè  0.1673
4666  TR397721       2020 Freestyle          Madame  0.1629
1084  TR679925              Cartier             Guè  0.1564
3175  TR226953            Ice Cream   Sfera Ebbasta  0.1476

Bottom 10 tracks with the lowest Zero Crossing Rate:

             id                 title    name_artist     zcr
8311   TR591502        Madtadone 2015         MadMan  0.0000
4877   TR508832                 In Tv          Vacca  0.0000
3158   TR485347               Squali*  Sfera Ebbasta  0.0083
1950   TR234003         Le Mie Amiche        La Pina  0.0106
365    TR609656  -3 (PERDERE IL VOLO)          Lazza  0.0117
261    TR432428             Veri Fra*         thasup  0.0118
7544   TR930774         Fino a domani       Tony Boy  0.0136
10140  TR521844     Back In Blood RMX          Shiva  0.0138
3562   TR963213         El Chico Loco          Neffa  0.0147
368    TR270089              Silenzio          Lazza  0.0155

the same tracks in the root mean square analysis have also an error value in the zero crossing rate

In [126]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error zcr from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'zcr']])

df.loc[condition, 'zcr'] = np.nan

Removed error zcr from tracks:

            id           title name_artist  zcr
4877  TR508832           In Tv       Vacca  0.0
8311  TR591502  Madtadone 2015      MadMan  0.0

### pitch

In [127]:
invalid_elems = df[df['pitch'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['pitch'])

nan_indexes = df.index[df['pitch'].isna()].tolist()
print(f"number of missing values in pitch: {len(nan_indexes)}")

Series([], Name: pitch, dtype: float64)
number of missing values in pitch: 64

In [128]:
chart_data = df[['pitch']].dropna().copy()
chart_data['pitch'] = pd.to_numeric(chart_data['pitch'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='tan',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('pitch', bin=alt.Bin(maxbins=40), title='Pitch'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Pitch', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('pitch', title='Zero Crossing Rate'),
    tooltip=[
        alt.Tooltip('min(pitch)', title='Min Pitch'),
        alt.Tooltip('q1(pitch)', title='Q1 Pitch'),
        alt.Tooltip('median(pitch)', title='Median Pitch'),
        alt.Tooltip('q3(pitch)', title='Q3 Pitch'),
        alt.Tooltip('max(pitch)', title='Max Pitch')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [129]:
print(f"Top 10 tracks with the highest Pitch:")
top_10_bpm = df.sort_values(by='pitch', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'pitch']])

print(f"Bottom 10 tracks with the lowest Pitch:")
top_10_bpm = df.sort_values(by='pitch', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'pitch']])

Top 10 tracks with the highest Pitch:

             id                        title        name_artist      pitch
5063   TR235594          MILANO SUSHI & COCA          M¥SS KETA  3993.0203
8424   TR725309                CCL (Prequel)      Achille Lauro  3813.9158
7016   TR482427                  Talent Show            Mr.Rain  3804.6853
3513   TR501665  Beat Box (Per Improvvisare)        Articolo 31  3793.3868
28     TR933222                   Ramoscelli      Rosa Chemical  3779.4293
6277   TR874084                Ripetutamente           99 Posse  3760.3648
6320   TR993661                    La Scelta           99 Posse  3744.9862
3694  TR_670292            Calma... Calma...  Frankie hi-nrg mc  3733.1982
6638   TR102586   Ombre Cinesi (Strumentale)            Don Joe  3723.3517
3719  TR_672575            O Tempora O Mores  Frankie hi-nrg mc  3701.5820

Bottom 10 tracks with the lowest Pitch:

             id              title    name_artist      pitch
8311   TR591502     Madtadone 2015         MadMan     0.0000
4877   TR508832              In Tv          Vacca     2.8762
3158   TR485347            Squali*  Sfera Ebbasta   491.2475
7019   TR108035       OUTRO [2024]        Mr.Rain   814.3465
5238   TR917416              Intro          Luchè   849.8850
10622  TR444933  Patto col diavolo   Mondo Marcio  1006.4606
6776   TR177248         L'Eternità          Nesli  1016.7426
10326  TR686662   Il peggior night         Caneda  1020.8130
10317  TR764338         Strichnina         Caneda  1051.3296
8510   TR690085    Malato Di Vuoto  Achille Lauro  1054.5274

the same tracks in the zero crossing rate analysis have also an error value in the pitch

In [130]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error pitch from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'pitch']])

df.loc[condition, 'pitch'] = np.nan

Removed error pitch from tracks:

            id           title name_artist   pitch
4877  TR508832           In Tv       Vacca  2.8762
8311  TR591502  Madtadone 2015      MadMan  0.0000

### loudness

In [131]:
invalid_elems = df[df['loudness'].apply(check_type_validity, expected_type=float)]
print(invalid_elems['loudness'])

nan_indexes = df.index[df['loudness'].isna()].tolist()
print(f"number of missing values in loudness: {len(nan_indexes)}")

Series([], Name: loudness, dtype: float64)
number of missing values in loudness: 64

In [132]:
chart_data = df[['loudness']].dropna().copy()
chart_data['loudness'] = pd.to_numeric(chart_data['loudness'])

histogram_chart = alt.Chart(chart_data).mark_bar(
    color='silver',
    opacity=0.7,
    tooltip=True
).encode(
    x=alt.X('loudness', bin=alt.Bin(maxbins=40), title='Loudness'), 
    y=alt.Y('count()', title='Number of Tracks')
).properties(
    title='Distribution of Tracks by Loudness', 
    width=1000,
    height=400
)

boxplot_chart = alt.Chart(chart_data).mark_boxplot().encode(
    x=alt.X('loudness', title='Loudness'),
    tooltip=[
        alt.Tooltip('min(loudness)', title='Min Loudness'),
        alt.Tooltip('q1(loudness)', title='Q1 Loudness'),
        alt.Tooltip('median(loudness)', title='Median Loudness'),
        alt.Tooltip('q3(loudness)', title='Q3 Loudness'),
        alt.Tooltip('max(loudness)', title='Max Loudness')
    ]
).properties(width=1000, height=100)

final_chart = histogram_chart & boxplot_chart
display(final_chart)

alt.VConcatChart(...)

In [133]:
print(f"Top 10 tracks with the highest Loudness:")
top_10_bpm = df.sort_values(by='loudness', ascending=False).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'loudness']])

print(f"Bottom 10 tracks with the lowest Loudness:")
top_10_bpm = df.sort_values(by='loudness', ascending=True).head(10)
display(top_10_bpm[['id', 'title', 'name_artist', 'loudness']])

Top 10 tracks with the highest Loudness:

             id                    title     name_artist  loudness
177    TR805380             Alfa (Intro)            Alfa   81.9478
7572   TR565053                    Si si        Tony Boy   70.6590
10723  TR411053       Non tornare a casa   Fred De Palma   69.7137
7544   TR930774            Fino a domani        Tony Boy   61.5836
9781   TR439677             Vuoto (2007)           Salmo   61.0195
252    TR807338  6 1 akkollino freestyle          thasup   58.9279
9547   TR200420                  POPCORN       Dani Faiv   58.4856
9847   TR572270          The Bootyshaker        Tormento   58.0158
10062  TR429962                 100 OPPS           Shiva   54.2572
5482   TR978886            Ode Con Creta  Dargen D’Amico   54.1857

Bottom 10 tracks with the lowest Loudness:

,id,title,name_artist,loudness
8311,TR591502,Madtadone 2015,MadMan,0.0000
4877,TR508832,In Tv,Vacca,0.0000
8828,TR719913,Rooftop,Highsnob,0.2030
10961,TR935995,Faccio Brutto (2nd Roof RMX),Fedez,0.3390
1099,TR179203,MM & Guè Pequeno,Guè,0.3712
10962,TR693094,Pensavo fosse amore e invece... (Roofio RMX),Fedez,0.3980
10648,TR866390,Freestyle,Mondo Marcio,0.4179
3682,TR_985675,Chiedi Chiedi,Frankie hi-nrg mc,0.4360
8155,TR544070,Timeless Spirit,Shablo,0.4364
7019,TR108035,OUTRO [2024],Mr.Rain,0.5082

the same tracks in the pitch analysis have also an error value in the loudness

In [134]:
ids_to_fix = ['TR591502', 'TR508832']
condition = df['id'].isin(ids_to_fix)

print("Removed error loudness from tracks:")
display(df[condition][['id', 'title', 'name_artist', 'loudness']])

df.loc[condition, 'loudness'] = np.nan

Removed error loudness from tracks:

            id           title name_artist  loudness
4877  TR508832           In Tv       Vacca       0.0
8311  TR591502  Madtadone 2015      MadMan       0.0

### popularity

In [135]:
invalid_elems = df[df['popularity'].apply(check_type_validity, expected_type=int)]
print(invalid_elems['popularity'])

nan_indexes = df.index[df['popularity'].isna()].tolist()
print(f"number of missing values in popularity: {len(nan_indexes)}")

0        46.0
1        46.0
2        39.0
3        47.0
4        41.0
         ...
11153    57.0
11154    24.0
11155    57.0
11156    37.0
11157    30.0
Name: popularity, Length: 11158, dtype: object
number of missing values in popularity: 2

In [136]:
nans_before = df['popularity'].isna().sum()
temp_numeric_pop = pd.to_numeric(df['popularity'], errors='coerce')
nans_after = temp_numeric_pop.isna().sum()
newly_coerced_count = nans_after - nans_before
print(f"rows with non-numeric text to be coerced to NaN: {newly_coerced_count}")

df['popularity'] = temp_numeric_pop

invalid_range_mask = (df['popularity'] < 0) | (df['popularity'] > 100)
invalid_popularity = df[invalid_range_mask]

if not invalid_popularity.empty:
    print(f"found {len(invalid_popularity)} rows with invalid popularity (< 0 or > 100). They will be set to NaN")

    display(invalid_popularity[['id', 'title', 'name_artist', 'popularity']].head(10))
    
    df.loc[invalid_range_mask, 'popularity'] = np.nan

df['popularity'] = df['popularity'].astype('Int64')

rows with non-numeric text to be coerced to NaN: 27
found 49 rows with invalid popularity (< 0 or > 100). They will be set to NaN

,id,title,name_artist,popularity
3285,TR171180,PTS (PoiTiSpiego/PostTraumaticStress),Ghemon,-654.0
3665,TR_408376,Quelli che benpensano,Frankie hi-nrg mc,147413.0
3666,TR_519170,Autodafè,Frankie hi-nrg mc,164032.0
3668,TR_881302,Giù le mani da Caino,Frankie hi-nrg mc,-479.0
3669,TR_122537,Pedala,Frankie hi-nrg mc,736911.0
3672,TR_705072,Rap Lamento,Frankie hi-nrg mc,-223.0
3676,TR_178115,Libri Di Sangue,Frankie hi-nrg mc,225643.0
3677,TR_123558,Potere Alla Parola,Frankie hi-nrg mc,625834.0
3678,TR_120588,Nuvole,Frankie hi-nrg mc,476435.0
3679,TR_670088,Il beat come anestetico,Frankie hi-nrg mc,-238.0

### modified_popularity

In [137]:
invalid_elems = df[df['modified_popularity'].apply(check_type_validity, expected_type=bool)]
print(invalid_elems['modified_popularity'])

nan_indexes = df.index[df['modified_popularity'].isna()].tolist()
print(f"number of missing values in modified_popularity: {len(nan_indexes)}")

Series([], Name: modified_popularity, dtype: bool)
number of missing values in modified_popularity: 0

In [138]:
mod_true_mask = (df['modified_popularity'] == True)
mod_true_count = mod_true_mask.sum()

print(f"rows with modified_popularity=True: {mod_true_count}")

if mod_true_count > 0:
    pop_values_in_mod_true = df.loc[mod_true_mask, 'popularity']
    
    #count how many of the modified_popularity = TRUE are now NaN because of cleaning from previous step
    nans_in_mod_true = pop_values_in_mod_true.isna().sum()
    
    print(f"rows with modified_popularity=True that now have popularity=NaN: {nans_in_mod_true}")
    
    if nans_in_mod_true == mod_true_count:
        print("all 'modified_popularity=TRUE' rows correspond to NaN 'popularity' values.")

rows with modified_popularity=True: 78
rows with modified_popularity=True that now have popularity=NaN: 78
all 'modified_popularity=TRUE' rows correspond to NaN 'popularity' values.

### explicit

In [139]:
invalid_elems = df[df['explicit'].apply(check_type_validity, expected_type=bool)]
print(invalid_elems['explicit'])

nan_indexes = df.index[df['explicit'].isna()].tolist()
print(f"number of missing values in explicit: {len(nan_indexes)}")

1931    NaN
2303    NaN
3285    NaN
3665    NaN
3666    NaN
       ...
3735    NaN
3736    NaN
3737    NaN
6385    NaN
9255    NaN
Name: explicit, Length: 78, dtype: object
number of missing values in explicit: 78

In [140]:
explicit_counts = df['explicit'].value_counts(dropna=False)

print(f"explicit tracks (True):     {explicit_counts.get(True, 0)}")
print(f"non-explicit tracks (False): {explicit_counts.get(False, 0)}")

df['total_swear_words'] = df['swear_IT'] + df['swear_EN']

non_explicit_mask = (df['explicit'] == False)
non_explicit_tracks = df[non_explicit_mask]

if not non_explicit_tracks.empty:
    mismatches = non_explicit_tracks[non_explicit_tracks['total_swear_words'] > 0]
        
    mismatch_count = len(mismatches)
    
    if mismatch_count > 0:
        print(f"found {mismatch_count} non-explicit (False) tracks with a swear word count > 0.")
        print("samples:")
        display(mismatches[['title', 'name_artist', 'explicit', 'swear_IT', 'swear_EN', 'total_swear_words']].head(10))
    else:
        print("all non-explicit (False) tracks have a swear word count of 0.")

explicit tracks (True):     5626
non-explicit tracks (False): 5454
found 3199 non-explicit (False) tracks with a swear word count > 0.
samples:

,title,name_artist,explicit,swear_IT,swear_EN,total_swear_words
10,POLKA 3,Rosa Chemical,False,12,0,12
32,Lil Peep,Rosa Chemical,False,5,2,7
45,Rosa Chemical,Rosa Chemical,False,4,1,5
55,BRITISH PROV 2014,Rosa Chemical,False,2,5,7
63,Keep on driving,Rosa Chemical,False,9,0,9
69,RASTAFARI_freestyle,Rosa Chemical,False,5,1,6
85,Dip Freestyle,Beba,False,2,1,3
94,Meno Male,Beba,False,3,0,3
99,Regole,Beba,False,1,0,1
108,Intro,Beba,False,3,0,3

by definition of explicit tracks: "songs that contain language, sounds, or imagery that may be considered offensive, such as profanity, violence, or sexual content", non-explicit tracks should contain no swear word, so the column will be updated accordingly (even for empty rows)

In [141]:
mask_no_swears = (df['total_swear_words'] == 0)
mask_has_swears = (df['total_swear_words'] > 0)

df.loc[(df['total_swear_words'] == 0), 'explicit'] = False
df.loc[(df['total_swear_words'] > 0), 'explicit'] = True

new_true_count = df['explicit'].eq(True).sum()
new_false_count = df['explicit'].eq(False).sum()

print(f"new 'True' explicit count:       {new_true_count}")
print(f"new 'False' explicit count:      {new_false_count}")

new 'True' explicit count:       7772
new 'False' explicit count:      3386